// Generated by panelkit from tools/panels/Repossession.py. Do not edit; edit the spec.
//
// Everything the panel's C++ needs to agree with res/Repossession.svg: the millimetre
// grid, the widget positions and the whole silkscreen. Rack's nanosvg discards
// <text>, so labels cannot live in the SVG -- they are drawn at runtime from
// the table below, generated from the same spec that drew the artwork.
//
// Every declaration here is `static`, i.e. private to the translation unit, so
// the three panels in this plugin cannot collide. That also means no
// translation unit may include two of these.
#pragma once
#include "../PanelTheme.hpp"

namespace panel {

// --- identity --------------------------------------------------------------
static const int   HP = 34;
static const float W  = 172.7200f;  // mm
static const float H  = 128.5000f;  // mm

// --- the read-out well: the spec's numbers, not the widget's ---------------
// A display used to be positioned by hand in the module's C++, in the same
// millimetres the spec had already chosen -- two copies of one number, and
// they drifted. The widget takes them from here now.
static const float GLASS_X = 4.2000f;
static const float GLASS_Y = 9.8000f;
static const float GLASS_W = 164.3200f;
static const float GLASS_H = 39.0000f;

// --- panel metrics, mirrored from tools/panels/Repossession.py ---
static const float INFO_H         = 23.6000f;
static const float INFO_W         = 100.2200f;
static const float INFO_X         = 66.0000f;
static const float INFO_Y         = 19.2000f;
static const float IW             = 159.7200f;
static const float M              = 6.5000f;
static const int   NUM_SLOTS      = 8;
static const float TL_H           = 4.9000f;
static const float TL_W           = 159.7200f;
static const float TL_X           = 6.5000f;
static const float TL_Y           = 43.6000f;
static const float URL_H          = 7.0000f;
static const float URL_W          = 100.2200f;
static const float URL_X          = 66.0000f;
static const float URL_Y          = 11.3000f;
static const float VID_H          = 31.5000f;
static const float VID_W          = 56.0000f;
static const float VID_X          = 6.5000f;
static const float VID_Y          = 11.3000f;

// --- silkscreen ------------------------------------------------------------
static const Label LABELS[] = {
	{ 11.5600f,   5.5000f, 10.50f, 1.50f, PAPER    , NVG_ALIGN_LEFT | NVG_ALIGN_BASELINE, false, "REPOSSESSION"},
	{161.1600f,   5.5000f,  6.00f, 0.00f, SAGE     , NVG_ALIGN_RIGHT | NVG_ALIGN_BASELINE, false, "SECURED PROPERTY"},
	{ 11.5600f,   8.2500f,  7.40f, 0.00f, LIME     , NVG_ALIGN_LEFT | NVG_ALIGN_BASELINE, true,  "$"},
	{ 13.7637f,   8.0000f,  4.60f, 0.40f, SAGE     , NVG_ALIGN_LEFT | NVG_ALIGN_BASELINE, false, "MOON TECHNOLOGIES"},
	{168.5200f,   8.0000f,  4.60f, 0.40f, SAGE     , NVG_ALIGN_RIGHT | NVG_ALIGN_BASELINE, false, "FORM 1099-A"},
	{ 86.3600f,  52.3000f,  6.00f, 0.60f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "SEIZED ASSETS"},
	{ 86.3600f,  70.1328f,  6.00f, 0.60f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "LIENS"},
	{ 18.2463f,  84.8396f,  7.00f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "REGION"},
	{ 34.5213f,  84.8396f,  7.00f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "SPEED"},
	{ 50.7963f,  84.8396f,  7.00f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "GAIN"},
	{ 77.4504f,  84.8396f,  6.20f, 0.00f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "LOOP"},
	{ 87.5004f,  84.8396f,  6.20f, 0.00f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "REV"},
	{114.1546f,  84.8396f,  7.00f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "MODE"},
	{130.4296f,  84.8396f,  7.00f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "TEMPO"},
	{156.9937f,  84.8396f,  6.20f, 0.00f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "RUN"},
	{ 86.3600f,  91.7639f,  6.00f, 0.60f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "COLLECTIONS"},
	{ 30.7202f,  96.0098f,  6.20f, 0.00f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "CLOCK"},
	{ 47.1498f,  96.0098f,  6.20f, 0.00f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "RESET"},
	{ 60.6998f,  96.0098f,  6.20f, 0.00f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "REGION"},
	{ 74.2498f,  96.0098f,  6.20f, 0.00f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "SCAN"},
	{ 87.7998f,  96.0098f,  6.20f, 0.00f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "FIRE"},
	{101.3498f,  96.0098f,  6.20f, 0.00f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "SPEED"},
	{114.8998f,  96.0098f,  6.20f, 0.00f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "GAIN"},
	{128.4498f,  96.0098f,  6.20f, 0.00f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "START"},
	{141.9998f,  96.0098f,  6.20f, 0.00f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "LENGTH"},
	{ 45.7100f, 113.4100f,  6.20f, 0.00f, MINT     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "OUT L"},
	{ 59.2600f, 113.4100f,  6.20f, 0.00f, MINT     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "OUT R"},
	{ 72.8100f, 113.4100f,  6.20f, 0.00f, MINT     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "STEPS"},
	{ 86.3600f, 113.4100f,  6.20f, 0.00f, MINT     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "POS"},
	{ 99.9100f, 113.4100f,  6.20f, 0.00f, MINT     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "GATE"},
	{113.4600f, 113.4100f,  6.20f, 0.00f, MINT     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "EOR"},
	{127.0100f, 113.4100f,  6.20f, 0.00f, MINT     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "REGION"},
};

/** Draws this panel's silkscreen. `static` so each module keeps its own,
    bound to its own table. */
static inline void addLabels(app::ModuleWidget* mw) {
	addLabels(mw, LABELS, sizeof(LABELS) / sizeof(LABELS[0]));
}

// --- widget positions, by the names used in tools/panels/Repossession.py -----
// Positions are mm; feed them to mm() or createParamCentered.
static const Vec BUSY_POS = Vec(98.2456, 51.5685);
static const Vec SLOT1_POS = Vec(38.9350, 58.7085);
static const Vec SLOT2_POS = Vec(52.4850, 58.7085);
static const Vec SLOT3_POS = Vec(66.0350, 58.7085);
static const Vec SLOT4_POS = Vec(79.5850, 58.7085);
static const Vec SLOT5_POS = Vec(93.1350, 58.7085);
static const Vec SLOT6_POS = Vec(106.6850, 58.7085);
static const Vec SLOT7_POS = Vec(120.2350, 58.7085);
static const Vec SLOT8_POS = Vec(133.7850, 58.7085);
static const Vec REGION_POS = Vec(18.2463, 76.7328);
static const Vec SPEED_POS = Vec(34.5213, 76.7328);
static const Vec GAIN_POS = Vec(50.7963, 76.7328);
static const Vec LOOP_POS = Vec(77.4504, 76.7328);
static const Vec REV_POS = Vec(87.5004, 76.7328);
static const Vec MODE_POS = Vec(114.1546, 76.7328);
static const Vec TEMPO_POS = Vec(130.4296, 76.7328);
static const Vec RUNMODE_POS = Vec(156.9937, 76.7328);
static const Vec CLOCK_IN_POS = Vec(30.7202, 101.6839);
static const Vec RESET_IN_POS = Vec(47.1498, 101.6839);
static const Vec REGION_IN_POS = Vec(60.6998, 101.6839);
static const Vec SCAN_IN_POS = Vec(74.2498, 101.6839);
static const Vec FIRE_IN_POS = Vec(87.7998, 101.6839);
static const Vec SPEED_IN_POS = Vec(101.3498, 101.6839);
static const Vec GAIN_IN_POS = Vec(114.8998, 101.6839);
static const Vec START_IN_POS = Vec(128.4498, 101.6839);
static const Vec LEN_IN_POS = Vec(141.9998, 101.6839);
static const Vec CLOCK_LED_POS = Vec(36.5098, 95.2539);
static const Vec OUT_L_POS = Vec(45.7100, 118.6000);
static const Vec OUT_R_POS = Vec(59.2600, 118.6000);
static const Vec STEPS_OUT_POS = Vec(72.8100, 118.6000);
static const Vec POS_OUT_POS = Vec(86.3600, 118.6000);
static const Vec GATE_OUT_POS = Vec(99.9100, 118.6000);
static const Vec EOR_OUT_POS = Vec(113.4600, 118.6000);
static const Vec REG_OUT_POS = Vec(127.0100, 118.6000);

} // namespace panel
