// Generated by panelkit from tools/panels/SignHere.py. Do not edit; edit the spec.
//
// Everything the panel's C++ needs to agree with res/SignHere.svg: the millimetre
// grid, the widget positions and the whole silkscreen. Rack's nanosvg discards
// <text>, so labels cannot live in the SVG -- they are drawn at runtime from
// the table below, generated from the same spec that drew the artwork.
//
// Every declaration here is `static`, i.e. private to the translation unit, so
// the three panels in this plugin cannot collide. That also means no
// translation unit may include two of these.
#pragma once
#include "../PanelTheme.hpp"

namespace panel {

// --- identity --------------------------------------------------------------
static const int   HP = 20;
static const float W  = 101.6000f;  // mm
static const float H  = 128.5000f;  // mm

// --- the read-out well: the spec's numbers, not the widget's ---------------
// A display used to be positioned by hand in the module's C++, in the same
// millimetres the spec had already chosen -- two copies of one number, and
// they drifted. The widget takes them from here now.
static const float GLASS_X = 4.2000f;
static const float GLASS_Y = 9.8000f;
static const float GLASS_W = 93.2000f;
static const float GLASS_H = 21.5000f;

// --- panel metrics, mirrored from tools/panels/SignHere.py ---
static const float IW             = 89.6000f;
static const float JOY_H          = 20.6000f;
static const float JOY_W          = 24.0000f;
static const float JOY_X          = 6.0000f;
static const float JOY_Y          = 10.3000f;
static const float M              = 6.0000f;
static const float TP_H           = 9.7000f;
static const float TP_W           = 25.0000f;
static const float TP_X0          = 34.0000f;
static const float TP_X1          = 60.4000f;
static const float TP_Y0          = 10.3000f;
static const float TP_Y1          = 21.4000f;

// --- silkscreen ------------------------------------------------------------
static const Label LABELS[] = {
	{ 11.5600f,   5.5000f, 10.50f, 1.50f, PAPER    , NVG_ALIGN_LEFT | NVG_ALIGN_BASELINE, false, "SIGN HERE"},
	{ 90.0400f,   5.5000f,  6.00f, 0.00f, SAGE     , NVG_ALIGN_RIGHT | NVG_ALIGN_BASELINE, false, "E-FILE SIGNATURE"},
	{ 11.5600f,   8.2500f,  7.40f, 0.00f, LIME     , NVG_ALIGN_LEFT | NVG_ALIGN_BASELINE, true,  "$"},
	{ 13.7637f,   8.0000f,  4.60f, 0.40f, SAGE     , NVG_ALIGN_LEFT | NVG_ALIGN_BASELINE, false, "MOON TECHNOLOGIES"},
	{ 97.4000f,   8.0000f,  4.60f, 0.40f, SAGE     , NVG_ALIGN_RIGHT | NVG_ALIGN_BASELINE, false, "FORM 8879"},
	{ 50.8000f,  34.8000f,  6.00f, 0.60f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "SIGNATURE"},
	{ 10.8000f,  50.4149f,  7.00f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "X SCALE"},
	{ 26.8000f,  50.4149f,  7.00f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "X OFFSET"},
	{ 42.8000f,  50.4149f,  7.00f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "Y SCALE"},
	{ 58.8000f,  50.4149f,  7.00f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "Y OFFSET"},
	{ 74.8000f,  50.4149f,  7.00f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "GLIDE"},
	{ 90.8000f,  50.4149f,  7.00f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "AMOUNT"},
	{ 22.3477f,  66.2644f,  6.60f, 0.00f, LIME_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "BUTTON"},
	{ 46.9527f,  66.2644f,  7.00f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "LEVEL"},
	{ 81.4823f,  66.2644f,  6.20f, 0.00f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "INV"},
	{  9.7000f,  69.9189f,  6.20f, 0.00f, MINT_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "X CV"},
	{ 21.4429f,  69.9189f,  6.20f, 0.00f, MINT_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "Y CV"},
	{ 33.1857f,  69.9189f,  6.20f, 0.00f, MINT_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "TOUCH"},
	{ 44.9286f,  69.9189f,  6.20f, 0.00f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "PEDAL"},
	{ 56.6714f,  69.9189f,  6.20f, 0.00f, MINT_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "GATE"},
	{ 68.4143f,  69.9189f,  6.20f, 0.00f, MINT_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "TRIG"},
	{ 80.1571f,  69.9189f,  6.20f, 0.00f, MINT_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "FLIP"},
	{ 91.9000f,  69.9189f,  6.20f, 0.00f, MINT_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "CV"},
	{  9.7000f,  83.3056f,  6.20f, 0.00f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "GATE"},
	{ 26.9000f,  83.3056f,  6.20f, 0.00f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "TRIG"},
	{ 44.1000f,  83.3056f,  6.20f, 0.00f, MINT_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "CV"},
	{ 57.5000f,  83.3056f,  6.20f, 0.00f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "GATE"},
	{ 74.7000f,  83.3056f,  6.20f, 0.00f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "TRIG"},
	{ 91.9000f,  83.3056f,  6.20f, 0.00f, MINT_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "CV"},
	{  9.7000f,  96.6924f,  6.20f, 0.00f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "GATE"},
	{ 26.9000f,  96.6924f,  6.20f, 0.00f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "TRIG"},
	{ 44.1000f,  96.6924f,  6.20f, 0.00f, MINT_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "CV"},
	{ 57.5000f,  96.6924f,  6.20f, 0.00f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "GATE"},
	{ 74.7000f,  96.6924f,  6.20f, 0.00f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "TRIG"},
	{ 91.9000f,  96.6924f,  6.20f, 0.00f, MINT_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "CV"},
	{ 40.3475f, 112.4751f,  6.20f, 0.00f, SAGE     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "IN"},
	{ 61.2525f, 112.4751f,  6.20f, 0.00f, MINT     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "OUT"},
};

/** Draws this panel's silkscreen. `static` so each module keeps its own,
    bound to its own table. */
static inline void addLabels(app::ModuleWidget* mw) {
	addLabels(mw, LABELS, sizeof(LABELS) / sizeof(LABELS[0]));
}

// --- widget positions, by the names used in tools/panels/SignHere.py -----
// Positions are mm; feed them to mm() or createParamCentered.
static const Vec X_SCALE_POS = Vec(10.8000, 42.0080);
static const Vec X_OFFSET_POS = Vec(26.8000, 42.0080);
static const Vec Y_SCALE_POS = Vec(42.8000, 42.0080);
static const Vec Y_OFFSET_POS = Vec(58.8000, 42.0080);
static const Vec GLIDE_POS = Vec(74.8000, 42.0080);
static const Vec AMOUNT_POS = Vec(90.8000, 42.0080);
static const Vec BUTTON_POS = Vec(22.3477, 57.8575);
static const Vec LEVEL_POS = Vec(46.9527, 57.8575);
static const Vec INV_POS = Vec(81.4823, 57.8575);
static const Vec X_CV_OUT_POS = Vec(9.7000, 76.0438);
static const Vec Y_CV_OUT_POS = Vec(21.4429, 76.0438);
static const Vec TOUCH_GATE_OUT_POS = Vec(33.1857, 76.0438);
static const Vec PEDAL_IN_POS = Vec(44.9286, 76.0438);
static const Vec BTN_GATE_OUT_POS = Vec(56.6714, 76.0438);
static const Vec BTN_TRIG_OUT_POS = Vec(68.4143, 76.0438);
static const Vec BTN_FLIP_OUT_POS = Vec(80.1571, 76.0438);
static const Vec BTN_CV_OUT_POS = Vec(91.9000, 76.0438);
static const Vec GATE1_POS = Vec(9.7000, 89.4306);
static const Vec TRIG1_POS = Vec(26.9000, 89.4306);
static const Vec CV1_POS = Vec(44.1000, 89.4306);
static const Vec GATE2_POS = Vec(57.5000, 89.4306);
static const Vec TRIG2_POS = Vec(74.7000, 89.4306);
static const Vec CV2_POS = Vec(91.9000, 89.4306);
static const Vec GATE3_POS = Vec(9.7000, 102.8173);
static const Vec TRIG3_POS = Vec(26.9000, 102.8173);
static const Vec CV3_POS = Vec(44.1000, 102.8173);
static const Vec GATE4_POS = Vec(57.5000, 102.8173);
static const Vec TRIG4_POS = Vec(74.7000, 102.8173);
static const Vec CV4_POS = Vec(91.9000, 102.8173);
static const Vec UTIL_IN_POS = Vec(40.3475, 118.6000);
static const Vec UTIL_OUT_POS = Vec(61.2525, 118.6000);

} // namespace panel
