// Generated by panelkit from tools/panels/Volatility.py. Do not edit; edit the spec.
//
// Everything the panel's C++ needs to agree with res/Volatility.svg: the millimetre
// grid, the widget positions and the whole silkscreen. Rack's nanosvg discards
// <text>, so labels cannot live in the SVG -- they are drawn at runtime from
// the table below, generated from the same spec that drew the artwork.
//
// Every declaration here is `static`, i.e. private to the translation unit, so
// the three panels in this plugin cannot collide. That also means no
// translation unit may include two of these.
#pragma once
#include "../PanelTheme.hpp"

namespace panel {

// --- identity --------------------------------------------------------------
static const int   HP = 9;
static const float W  = 45.7200f;  // mm
static const float H  = 128.5000f;  // mm
//: What the module is, as the masthead's second line says it.
static const char* const WHAT = "NOISE, S&H & RANDOM";

// --- silkscreen ------------------------------------------------------------
static const Label LABELS[] = {
	{ 22.8600f,   5.5000f,  9.02f, 1.50f, PAPER    , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "VOLATILITY"},
	{  1.4000f,   8.2500f,  7.40f, 0.00f, LIME     , NVG_ALIGN_LEFT | NVG_ALIGN_BASELINE, 1,     "$"},
	{ 22.8600f,   8.0000f,  5.40f, 0.40f, LIME     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "NOISE, S&H & RANDOM"},
	{  2.1717f,  60.0500f,  4.60f, 0.40f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 2,     "MOON TECHNOLOGIES"},
	{ 43.5483f,  60.0500f,  4.60f, 0.40f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 3,     "SCHEDULE D"},
	{ 22.8600f,  13.3000f,  6.00f, 0.60f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "NOISE"},
	{  9.1000f,  28.0069f,  7.00f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "RATE"},
	{ 22.8600f,  28.0069f,  7.00f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "COLOR"},
	{ 36.6200f,  28.0069f,  7.00f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "BITS"},
	{  9.1000f,  31.0687f,  6.20f, 0.00f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "RATE CV"},
	{ 22.8600f,  31.0687f,  6.20f, 0.00f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "CLOCK IN"},
	{ 36.6200f,  31.0687f,  6.20f, 0.00f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "BITS CV"},
	{  9.1000f,  43.5997f,  6.20f, 0.00f, MINT_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "NOISE"},
	{ 22.8600f,  43.5997f,  6.20f, 0.00f, MINT_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "DAC"},
	{ 36.6200f,  43.5997f,  6.20f, 0.00f, MINT_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "CLK"},
	{ 22.8600f,  58.5690f,  6.00f, 0.60f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "SAMPLE & HOLD"},
	{ 10.2925f,  61.6308f,  6.20f, 0.00f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "SRC"},
	{ 23.6100f,  61.6308f,  6.20f, 0.00f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "TRIG"},
	{ 35.9975f,  72.9526f,  6.20f, 0.00f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "SLEW"},
	{ 22.8600f,  78.2418f,  6.00f, 0.60f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "RND GATE"},
	{  9.1000f,  92.9487f,  7.00f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "PROB"},
	{ 24.5550f,  92.9487f,  6.20f, 0.00f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "SRC"},
	{ 37.8300f,  92.9487f,  6.20f, 0.00f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "PROB CV"},
	{  9.1000f, 107.3323f,  6.20f, 0.00f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "LENGTH"},
	{ 24.5550f,  96.0105f,  6.20f, 0.00f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "SRC IN"},
	{  9.3100f, 113.4100f,  6.20f, 0.00f, MINT     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "RND"},
	{ 22.8600f, 113.4100f,  6.20f, 0.00f, MINT     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "S&H"},
	{ 36.4100f, 113.4100f,  6.20f, 0.00f, MINT     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "GATE"},
};

/** Draws this panel's silkscreen. `static` so each module keeps its own,
    bound to its own table. */
static inline void addLabels(app::ModuleWidget* mw) {
	addLabels(mw, LABELS, sizeof(LABELS) / sizeof(LABELS[0]));
}

// --- widget positions, by the names used in tools/panels/Volatility.py -----
// Positions are mm; feed them to mm() or createParamCentered.
static const Vec RATE_POS = Vec(9.1000, 19.9000);
static const Vec COLOR_POS = Vec(22.8600, 19.9000);
static const Vec BITS_POS = Vec(36.6200, 19.9000);
static const Vec RATE_CV_IN_POS = Vec(9.1000, 36.2587);
static const Vec CLOCK_IN_POS = Vec(22.8600, 36.2587);
static const Vec BITS_CV_IN_POS = Vec(36.6200, 36.2587);
static const Vec NOISE_OUT_POS = Vec(9.1000, 48.7897);
static const Vec DAC_OUT_POS = Vec(22.8600, 48.7897);
static const Vec CLOCK_OUT_POS = Vec(36.6200, 48.7897);
static const Vec SH_SRC_IN_POS = Vec(10.2925, 66.8208);
static const Vec SH_TRIG_IN_POS = Vec(23.6100, 66.8208);
static const Vec SH_SLEW_POS = Vec(35.9975, 66.8208);
static const Vec PROBABILITY_POS = Vec(9.1000, 84.8418);
static const Vec RND_SRC_POS = Vec(24.5550, 84.8418);
static const Vec PROB_CV_AMT_POS = Vec(37.8300, 84.8418);
static const Vec LENGTH_POS = Vec(9.1000, 101.2005);
static const Vec RND_SRC_IN_POS = Vec(24.5550, 101.2005);
static const Vec PROB_CV_IN_POS = Vec(37.8300, 101.2005);
static const Vec RND_OUT_POS = Vec(9.3100, 118.6000);
static const Vec SH_OUT_POS = Vec(22.8600, 118.6000);
static const Vec GATE_OUT_POS = Vec(36.4100, 118.6000);

} // namespace panel
