// Generated by panelkit from tools/panels/Reconciliation.py. Do not edit; edit the spec.
//
// Everything the panel's C++ needs to agree with res/Reconciliation.svg: the millimetre
// grid, the widget positions and the whole silkscreen. Rack's nanosvg discards
// <text>, so labels cannot live in the SVG -- they are drawn at runtime from
// the table below, generated from the same spec that drew the artwork.
//
// Every declaration here is `static`, i.e. private to the translation unit, so
// the three panels in this plugin cannot collide. That also means no
// translation unit may include two of these.
#pragma once
#include "../PanelTheme.hpp"

namespace panel {

// --- identity --------------------------------------------------------------
static const int   HP = 21;
static const float W  = 106.6800f;  // mm
static const float H  = 128.5000f;  // mm

// --- the read-out well: the spec's numbers, not the widget's ---------------
// A display used to be positioned by hand in the module's C++, in the same
// millimetres the spec had already chosen -- two copies of one number, and
// they drifted. The widget takes them from here now.
static const float GLASS_X = 4.2000f;
static const float GLASS_Y = 9.8000f;
static const float GLASS_W = 98.2800f;
static const float GLASS_H = 9.2000f;

// --- silkscreen ------------------------------------------------------------
static const Label LABELS[] = {
	{ 53.3400f,   5.5000f, 10.50f, 1.50f, PAPER    , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "RECONCILIATION"},
	{ 11.5600f,   8.2500f,  7.40f, 0.00f, LIME     , NVG_ALIGN_LEFT | NVG_ALIGN_BASELINE, true,  "$"},
	{ 13.7637f,   8.0000f,  4.60f, 0.40f, SAGE     , NVG_ALIGN_LEFT | NVG_ALIGN_BASELINE, false, "MOON TECHNOLOGIES"},
	{102.4800f,   8.0000f,  4.60f, 0.40f, SAGE     , NVG_ALIGN_RIGHT | NVG_ALIGN_BASELINE, false, "SCHEDULE M-1"},
	{ 53.3400f,  22.5000f,  6.00f, 0.60f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "BASIS"},
	{ 16.7162f,  38.1149f,  7.00f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "SET"},
	{ 41.6912f,  38.1149f,  7.00f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "NEXUS"},
	{ 65.8275f,  38.1149f,  6.20f, 0.00f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "UTONAL"},
	{ 89.9638f,  38.1149f,  7.00f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "PRIME"},
	{ 53.3400f,  45.9075f,  6.00f, 0.60f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "RECONCILE"},
	{ 10.8000f,  66.1224f,  7.00f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "RULE"},
	{ 29.3200f,  66.1224f,  7.00f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "BIAS"},
	{ 47.8400f,  66.1224f,  7.00f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "WINDOW"},
	{ 63.4400f,  66.1224f,  7.00f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "DEGREE"},
	{ 79.6600f,  66.1224f,  7.00f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "HYST"},
	{ 95.8800f,  66.1224f,  7.00f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "SLEW"},
	{ 53.3400f,  73.9151f,  6.00f, 0.60f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "ALLOWANCES"},
	{ 21.9825f,  85.7749f,  6.20f, 0.00f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "NEXUS"},
	{ 42.8875f,  85.7749f,  6.20f, 0.00f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "WINDOW"},
	{ 63.7925f,  85.7749f,  6.20f, 0.00f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "BIAS"},
	{ 84.6975f,  85.7749f,  6.20f, 0.00f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "DEGREE"},
	{  7.7000f, 112.2659f,  6.20f, 0.00f, SAGE     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "IN"},
	{ 22.3584f, 112.2659f,  6.20f, 0.00f, SAGE     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "ROOT"},
	{ 37.0168f, 112.2659f,  6.20f, 0.00f, SAGE     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "RESET"},
	{ 51.6752f, 112.2659f,  6.20f, 0.00f, MINT     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "OUT"},
	{ 66.3336f, 112.2659f,  6.20f, 0.00f, MINT     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "TRIG"},
	{ 80.9920f, 112.2659f,  6.20f, 0.00f, MINT     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "PURITY"},
	{ 95.6504f, 112.2659f,  6.20f, 0.00f, MINT     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "DRIFT"},
};

/** Draws this panel's silkscreen. `static` so each module keeps its own,
    bound to its own table. */
static inline void addLabels(app::ModuleWidget* mw) {
	addLabels(mw, LABELS, sizeof(LABELS) / sizeof(LABELS[0]));
}

// --- widget positions, by the names used in tools/panels/Reconciliation.py -----
// Positions are mm; feed them to mm() or createParamCentered.
static const Vec SET_POS = Vec(16.7162, 29.7080);
static const Vec NEXUS_POS = Vec(41.6912, 29.7080);
static const Vec UTONAL_POS = Vec(65.8275, 29.7080);
static const Vec PRIME_POS = Vec(89.9638, 29.7080);
static const Vec RULE_POS = Vec(10.8000, 55.4155);
static const Vec BIAS_POS = Vec(29.3200, 55.4155);
static const Vec WINDOW_POS = Vec(47.8400, 55.4155);
static const Vec DEGREE_POS = Vec(63.4400, 55.4155);
static const Vec HYST_POS = Vec(79.6600, 55.4155);
static const Vec SLEW_POS = Vec(95.8800, 55.4155);
static const Vec NEXUS_CV_POS = Vec(21.9825, 79.3431);
static const Vec WINDOW_CV_POS = Vec(42.8875, 79.3431);
static const Vec BIAS_CV_POS = Vec(63.7925, 79.3431);
static const Vec DEGREE_CV_POS = Vec(84.6975, 79.3431);
static const Vec NEXUS_IN_POS = Vec(21.9825, 91.8998);
static const Vec WINDOW_IN_POS = Vec(42.8875, 91.8998);
static const Vec BIAS_IN_POS = Vec(63.7925, 91.8998);
static const Vec DEGREE_IN_POS = Vec(84.6975, 91.8998);
static const Vec PITCH_IN_POS = Vec(7.7000, 118.6000);
static const Vec ROOT_IN_POS = Vec(22.3584, 118.6000);
static const Vec RESET_IN_POS = Vec(37.0168, 118.6000);
static const Vec PITCH_OUT_POS = Vec(51.6752, 118.6000);
static const Vec TRIG_OUT_POS = Vec(66.3336, 118.6000);
static const Vec PURITY_OUT_POS = Vec(80.9920, 118.6000);
static const Vec DRIFT_OUT_POS = Vec(95.6504, 118.6000);
static const Vec TRIG_LED_POS = Vec(71.7433, 111.5100);
static const Vec DRIFT_LED_POS = Vec(101.6900, 111.5100);

} // namespace panel
