// Generated by panelkit from tools/panels/Reconciliation.py. Do not edit; edit the spec.
//
// Everything the panel's C++ needs to agree with res/Reconciliation.svg: the millimetre
// grid, the widget positions and the whole silkscreen. Rack's nanosvg discards
// <text>, so labels cannot live in the SVG -- they are drawn at runtime from
// the table below, generated from the same spec that drew the artwork.
//
// Every declaration here is `static`, i.e. private to the translation unit, so
// the three panels in this plugin cannot collide. That also means no
// translation unit may include two of these.
#pragma once
#include "../PanelTheme.hpp"

namespace panel {

// --- identity --------------------------------------------------------------
static const int   HP = 11;
static const float W  = 55.8800f;  // mm
static const float H  = 128.5000f;  // mm
//: What the module is, as the masthead's second line says it.
static const char* const WHAT = "JUST-INTONATION QUANTIZER";

// --- the read-out well: the spec's numbers, not the widget's ---------------
// A display used to be positioned by hand in the module's C++, in the same
// millimetres the spec had already chosen -- two copies of one number, and
// they drifted. The widget takes them from here now.
static const float GLASS_X = 3.6000f;
static const float GLASS_Y = 9.8000f;
static const float GLASS_W = 48.6800f;
static const float GLASS_H = 24.0000f;

// --- controls on the glass: where each is drawn and where it is grabbed --
// One rectangle per Field in the spec, in panel mm. Place the widget with
// createField<Screen...>(FIELD_X, ...) -- or createMenuField for a "menu" --
// and draw the value in
// inGlass(FIELD_X), the same rectangle in the display's own pixels.
static const Rect FIELD_SET = Rect(Vec(4.4000f, 15.1800f), Vec(17.3425f, 4.0800f));  // select: ScreenSelect
static const Rect FIELD_UTONAL = Rect(Vec(22.2425f, 15.1800f), Vec(5.4475f, 4.0800f));  // toggle: ScreenSwitch
static const Rect FIELD_NEXUS = Rect(Vec(28.1900f, 15.1800f), Vec(5.4475f, 4.0800f));  // select: ScreenSelect
static const Rect FIELD_RULE = Rect(Vec(34.1375f, 15.1800f), Vec(17.3425f, 4.0800f));  // select: ScreenSelect
static const Rect FIELD_PRIME = Rect(Vec(4.4000f, 19.7600f), Vec(23.2900f, 4.0800f));  // select: ScreenSelect
static const Rect FIELD_DEGREE = Rect(Vec(28.1900f, 19.7600f), Vec(23.2900f, 4.0800f));  // value: ScreenKnob
static const Rect FIELD_HYST = Rect(Vec(4.4000f, 24.3400f), Vec(23.2900f, 4.0800f));  // value: ScreenKnob
static const Rect FIELD_SLEW = Rect(Vec(28.1900f, 24.3400f), Vec(23.2900f, 4.0800f));  // value: ScreenKnob

/** A field's rectangle in the display's pixels, for a display placed on the glass. */
static inline Rect inGlass(const Rect& f) {
	return mmRect(f.pos.x - GLASS_X, f.pos.y - GLASS_Y, f.size.x, f.size.y);
}

// --- silkscreen ------------------------------------------------------------
static const Label LABELS[] = {
	{ 27.9400f,   5.5000f,  9.30f, 1.50f, PAPER    , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "RECONCILIATION"},
	{  1.4000f,   8.2500f,  7.40f, 0.00f, LIME     , NVG_ALIGN_LEFT | NVG_ALIGN_BASELINE, 1,     "$"},
	{ 27.9400f,   8.0000f,  5.40f, 0.40f, LIME     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "JUST-INTONATION QUANTIZER"},
	{  2.1717f,  60.0500f,  4.60f, 0.40f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 2,     "MOON TECHNOLOGIES"},
	{ 53.7083f,  60.0500f,  4.60f, 0.40f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 3,     "SCHEDULE M-1"},
	{ 20.0500f,  37.3000f,  6.00f, 0.60f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "RECONCILE"},
	{ 11.7000f,  57.2069f,  7.00f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "BIAS"},
	{ 31.0000f,  57.2069f,  7.00f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "WINDOW"},
	{ 20.0500f,  62.0069f,  6.00f, 0.60f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "ALLOWANCES"},
	{ 13.2750f,  74.3587f,  6.20f, 0.00f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "NEXUS"},
	{ 26.8250f,  74.3587f,  6.20f, 0.00f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "WINDOW"},
	{ 13.2750f,  97.7405f,  6.20f, 0.00f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "BIAS"},
	{ 26.8250f,  97.7405f,  6.20f, 0.00f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "DEGREE"},
	{ 46.3900f,  37.3000f,  6.00f, 0.60f, MINT     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "OUT"},
	{ 46.3900f,  40.3618f,  6.20f, 0.00f, MINT     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "OUT"},
	{ 46.3900f,  59.9547f,  6.20f, 0.00f, MINT     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "TRIG"},
	{ 46.3900f,  79.5476f,  6.20f, 0.00f, MINT     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "PURITY"},
	{ 46.3900f,  99.1405f,  6.20f, 0.00f, MINT     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "DRIFT"},
	{ 14.3900f, 113.4100f,  6.20f, 0.00f, SAGE     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "IN"},
	{ 27.9400f, 113.4100f,  6.20f, 0.00f, SAGE     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "ROOT"},
	{ 41.4900f, 113.4100f,  6.20f, 0.00f, SAGE     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "RESET"},
};

/** Draws this panel's silkscreen. `static` so each module keeps its own,
    bound to its own table. */
static inline void addLabels(app::ModuleWidget* mw) {
	addLabels(mw, LABELS, sizeof(LABELS) / sizeof(LABELS[0]));
}

// --- widget positions, by the names used in tools/panels/Reconciliation.py -----
// Positions are mm; feed them to mm() or createParamCentered.
static const Vec BIAS_POS = Vec(11.7000, 46.5000);
static const Vec WINDOW_POS = Vec(31.0000, 46.5000);
static const Vec NEXUS_CV_POS = Vec(13.2750, 66.8269);
static const Vec WINDOW_CV_POS = Vec(26.8250, 66.8269);
static const Vec NEXUS_IN_POS = Vec(13.2750, 80.9487);
static const Vec WINDOW_IN_POS = Vec(26.8250, 80.9487);
static const Vec BIAS_CV_POS = Vec(13.2750, 90.2087);
static const Vec DEGREE_CV_POS = Vec(26.8250, 90.2087);
static const Vec BIAS_IN_POS = Vec(13.2750, 104.3305);
static const Vec DEGREE_IN_POS = Vec(26.8250, 104.3305);
static const Vec PITCH_OUT_POS = Vec(46.3900, 45.5518);
static const Vec TRIG_OUT_POS = Vec(46.3900, 65.1447);
static const Vec PURITY_OUT_POS = Vec(46.3900, 84.7376);
static const Vec DRIFT_OUT_POS = Vec(46.3900, 104.3305);
static const Vec PITCH_IN_POS = Vec(14.3900, 118.6000);
static const Vec ROOT_IN_POS = Vec(27.9400, 118.6000);
static const Vec RESET_IN_POS = Vec(41.4900, 118.6000);

} // namespace panel
