// Generated by panelkit from tools/panels/TaxBracket.py. Do not edit; edit the spec.
//
// Everything the panel's C++ needs to agree with res/TaxBracket.svg: the millimetre
// grid, the widget positions and the whole silkscreen. Rack's nanosvg discards
// <text>, so labels cannot live in the SVG -- they are drawn at runtime from
// the table below, generated from the same spec that drew the artwork.
//
// Every declaration here is `static`, i.e. private to the translation unit, so
// the three panels in this plugin cannot collide. That also means no
// translation unit may include two of these.
#pragma once
#include "../PanelTheme.hpp"

namespace panel {

// --- identity --------------------------------------------------------------
static const int   HP = 12;
static const float W  = 60.9600f;  // mm
static const float H  = 128.5000f;  // mm

// --- silkscreen ------------------------------------------------------------
static const Label LABELS[] = {
	{ 30.4800f,   5.5000f, 10.50f, 1.50f, PAPER    , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "TAX BRACKET"},
	{ 11.5600f,   8.2500f,  7.40f, 0.00f, LIME     , NVG_ALIGN_LEFT | NVG_ALIGN_BASELINE, true,  "$"},
	{ 13.7637f,   8.0000f,  4.60f, 0.40f, SAGE     , NVG_ALIGN_LEFT | NVG_ALIGN_BASELINE, false, "MOON TECHNOLOGIES"},
	{ 56.7600f,   8.0000f,  4.60f, 0.40f, SAGE     , NVG_ALIGN_RIGHT | NVG_ALIGN_BASELINE, false, "TAX RATE SCHEDULE X"},
	{ 30.4800f,  21.4000f,  6.00f, 0.60f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "BRACKETS"},
	{  8.0000f,  25.6118f,  6.20f, 0.00f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "1"},
	{ 22.9867f,  25.6118f,  6.20f, 0.00f, MINT_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "1"},
	{ 37.9733f,  25.6118f,  6.20f, 0.00f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "16"},
	{ 52.9600f,  25.6118f,  6.20f, 0.00f, MINT_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "16"},
	{  8.0000f,  39.2685f,  6.20f, 0.00f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "2"},
	{ 22.9867f,  39.2685f,  6.20f, 0.00f, MINT_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "2"},
	{ 37.9733f,  39.2685f,  6.20f, 0.00f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "32"},
	{ 52.9600f,  39.2685f,  6.20f, 0.00f, MINT_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "32"},
	{  8.0000f,  52.9253f,  6.20f, 0.00f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "4"},
	{ 22.9867f,  52.9253f,  6.20f, 0.00f, MINT_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "4"},
	{ 37.9733f,  52.9253f,  6.20f, 0.00f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "64"},
	{ 52.9600f,  52.9253f,  6.20f, 0.00f, MINT_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "64"},
	{  8.0000f,  66.5820f,  6.20f, 0.00f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "8"},
	{ 22.9867f,  66.5820f,  6.20f, 0.00f, MINT_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "8"},
	{ 37.9733f,  66.5820f,  6.20f, 0.00f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "128"},
	{ 52.9600f,  66.5820f,  6.20f, 0.00f, MINT_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "128"},
	{ 30.4800f,  87.2270f,  6.00f, 0.60f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "ADJUSTMENTS"},
	{ 17.0000f, 100.5270f,  6.20f, 0.00f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "GROUND"},
	{ 43.9600f, 100.5270f,  6.20f, 0.00f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "SCALE"},
	{ 17.0000f, 112.4651f,  6.20f, 0.00f, SAGE     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "I/O"},
	{ 43.9600f, 112.4651f,  6.20f, 0.00f, MINT     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "I/O"},
};

/** Draws this panel's silkscreen. `static` so each module keeps its own,
    bound to its own table. */
static inline void addLabels(app::ModuleWidget* mw) {
	addLabels(mw, LABELS, sizeof(LABELS) / sizeof(LABELS[0]));
}

// --- widget positions, by the names used in tools/panels/TaxBracket.py -----
// Positions are mm; feed them to mm() or createParamCentered.
static const Vec IN1_POS = Vec(8.0000, 31.7467);
static const Vec OUT1_POS = Vec(22.9867, 31.7467);
static const Vec IN16_POS = Vec(37.9733, 31.7467);
static const Vec OUT16_POS = Vec(52.9600, 31.7467);
static const Vec IN2_POS = Vec(8.0000, 45.4035);
static const Vec OUT2_POS = Vec(22.9867, 45.4035);
static const Vec IN32_POS = Vec(37.9733, 45.4035);
static const Vec OUT32_POS = Vec(52.9600, 45.4035);
static const Vec IN4_POS = Vec(8.0000, 59.0602);
static const Vec OUT4_POS = Vec(22.9867, 59.0602);
static const Vec IN64_POS = Vec(37.9733, 59.0602);
static const Vec OUT64_POS = Vec(52.9600, 59.0602);
static const Vec IN8_POS = Vec(8.0000, 72.7170);
static const Vec OUT8_POS = Vec(22.9867, 72.7170);
static const Vec IN128_POS = Vec(37.9733, 72.7170);
static const Vec OUT128_POS = Vec(52.9600, 72.7170);
static const Vec GROUND_POS = Vec(17.0000, 93.4270);
static const Vec SCALE_POS = Vec(43.9600, 93.4270);
static const Vec IO_IN_POS = Vec(17.0000, 118.6000);
static const Vec IO_OUT_POS = Vec(43.9600, 118.6000);

} // namespace panel
