;==========================================================================================
; Variable-mode CV quantizer for the PIC16F684 -- Moon Technologies' own firmware.
;
; A drop-in for the Modular in a Week Day 10 quantizer board's job, written for this
; repository (the course's firmware is third-party and is loaded at runtime, never carried
; here), and corrected where that one is not:
;
;   * the PWM steps are exactly 1/12 V: duty = round(note * 1024 / 60), where the course's
;     table is up to 4 counts off (a quarter of a semitone) and uneven;
;   * the input is read at 10 bits, not 8, so a note boundary falls where the voltage says;
;   * every input has an output: at the top of the range the course's tables can fall through
;     (major, minor and minor pentatonic keep the last note above 253 of 255, and major
;     pentatonic runs on into the minor table);
;   * each scale picks the true nearest degree, with exact ties going up.
;
; Hardware: exactly the course's. 20 MHz external clock (EC oscillator; the configuration word is
; set when the part is programmed, not by this file: EC clock, watchdog off, code protect off).
;   RC0/AN4  pin 10  CV in, 0..5 V, 1 V/octave, 60 semitones over the range
;   RC1/AN5  pin  9  mode select, 0..5 V; the band of the top 8 bits picks the scale:
;                      0..52 major, 53..104 major pentatonic, 105..153 minor,
;                      154..204 minor pentatonic, 205..255 chromatic
;   RC5/CCP1 pin  5  PWM out, 19.5 kHz, 10 bits; filter it to get the CV
; The output is 5 V * duty / 1024, so note n is n/12 volts.
;
; Method, per pass of the main loop (about 170 us):
;   1. mode  <- ADRESH of AN5 (8 bits, left-justified)
;   2. code  <- 10-bit conversion of AN4 (right-justified)
;   3. h = floor(code * 60 / 512), a position in half-semitones (0..119): 60*code is built from
;      four shifted copies of code, and h is the high byte of it halved
;   4. octave = h / 24, hp = h mod 24, by subtraction
;   5. degree <- MODETBL[mode*24 + hp]: the nearest scale degree, in semitones (0..12)
;   6. note = octave*12 + degree
;   7. CCPR1L, DC1B <- DUTYH[note], DUTYL[note]
; The tables are generated by tools/varimode_tables.py and checked against an independent
; quantizer, for every input in every mode, by tests/Pic16.
;==========================================================================================

PCL     EQU     02h
STATUS  EQU     03h
PORTC   EQU     07h
PCLATH  EQU     0Ah
T2CON   EQU     12h
CCPR1L  EQU     13h
CCP1CON EQU     15h
ADRESH  EQU     1Eh
ADCON0  EQU     1Fh
TRISC   EQU     87h
ANSEL   EQU     91h
PR2     EQU     92h
ADRESL  EQU     9Eh
ADCON1  EQU     9Fh

CODEH   EQU     20h             ; the 10-bit input code
CODEL   EQU     21h
ARGH    EQU     22h             ; code, shifted left
ARGL    EQU     23h
TOTH    EQU     24h             ; 60 * code
TOTL    EQU     25h
MODE8   EQU     26h             ; the top 8 bits of the mode pin
MBASE   EQU     27h             ; 24 * mode
HALF    EQU     28h             ; position in half-semitones
OCT     EQU     29h
IDX     EQU     2Ah
NOTE    EQU     2Bh
TMP     EQU     2Ch
DLY     EQU     2Dh
VH      EQU     2Eh             ; the duty's high byte, and its two low bits
VL      EQU     2Fh

        ORG     0
        GOTO    START

START   MOVLW   B'00000100'     ; TMR2 on, 1:1
        MOVWF   T2CON
        CLRF    PORTC
        CLRF    CCPR1L
        MOVLW   B'00001100'     ; CCP1 in PWM mode, DC1B = 00
        MOVWF   CCP1CON
        BSF     STATUS,5
        MOVLW   D'255'          ; PR2: a 256-cycle period, 51.2 us, 19.5 kHz
        MOVWF   PR2
        MOVLW   B'11011111'     ; RC5 (CCP1) an output; the rest inputs
        MOVWF   TRISC
        MOVLW   B'00110000'     ; AN4 and AN5 analog
        MOVWF   ANSEL
        MOVLW   B'01100000'     ; A/D clock Fosc/64: TAD 3.2 us
        MOVWF   ADCON1
        BCF     STATUS,5

LOOP    MOVLW   B'00010101'     ; mode: AN5, left-justified
        MOVWF   ADCON0
        CALL    ACQUIRE
        BSF     ADCON0,1
WAITM   BTFSC   ADCON0,1
        GOTO    WAITM
        MOVF    ADRESH,W
        MOVWF   MODE8

        MOVLW   B'10010001'     ; input: AN4, right-justified, 10 bits
        MOVWF   ADCON0
        CALL    ACQUIRE
        BSF     ADCON0,1
WAITC   BTFSC   ADCON0,1
        GOTO    WAITC
        MOVF    ADRESH,W
        MOVWF   CODEH
        BSF     STATUS,5
        MOVF    ADRESL,W        ; ADRESL lives in bank 1
        BCF     STATUS,5
        MOVWF   CODEL

; --- h = floor(60 * code / 512) -------------------------------------------------
        MOVF    CODEH,W
        MOVWF   ARGH
        MOVF    CODEL,W
        MOVWF   ARGL
        BCF     STATUS,0
        RLF     ARGL,F          ; code * 2
        RLF     ARGH,F
        BCF     STATUS,0
        RLF     ARGL,F          ; code * 4
        RLF     ARGH,F
        MOVF    ARGL,W
        MOVWF   TOTL
        MOVF    ARGH,W
        MOVWF   TOTH            ; total = code * 4
        CALL    SHIFTADD        ; + code * 8
        CALL    SHIFTADD        ; + code * 16
        CALL    SHIFTADD        ; + code * 32 = code * 60
        BCF     STATUS,0
        RRF     TOTH,W          ; high byte / 2 = floor(60 * code / 512)
        MOVWF   HALF

; --- octave and position in the octave: HALF / 24 -------------------------------
        CLRF    OCT
        MOVF    HALF,W
        MOVWF   IDX
DIV24   MOVLW   D'24'
        SUBWF   IDX,W           ; W = IDX - 24, carry set if IDX >= 24
        BTFSS   STATUS,0
        GOTO    DIVDONE
        MOVWF   IDX
        INCF    OCT,F
        GOTO    DIV24
DIVDONE

; --- which scale: the band of the mode pin's top 8 bits -------------------------
        MOVF    MODE8,W
        SUBLW   D'52'           ; carry set if mode <= 52
        MOVLW   D'0'            ; (MOVLW leaves the carry alone)
        BTFSC   STATUS,0
        GOTO    HAVEMODE
        MOVF    MODE8,W
        SUBLW   D'104'
        MOVLW   D'24'
        BTFSC   STATUS,0
        GOTO    HAVEMODE
        MOVF    MODE8,W
        SUBLW   D'153'
        MOVLW   D'48'
        BTFSC   STATUS,0
        GOTO    HAVEMODE
        MOVF    MODE8,W
        SUBLW   D'204'
        MOVLW   D'72'
        BTFSC   STATUS,0
        GOTO    HAVEMODE
        MOVLW   D'96'
HAVEMODE
        MOVWF   MBASE

; --- the nearest degree of that scale -------------------------------------------
        MOVF    MBASE,W
        ADDWF   IDX,W
        MOVWF   TMP
        MOVLW   HIGH(MODETBL)
        MOVWF   PCLATH
        MOVF    TMP,W
        CALL    MODETBL
        MOVWF   NOTE            ; the degree, 0..12

; --- note = octave * 12 + degree ------------------------------------------------
        MOVF    OCT,W
        BTFSC   STATUS,2
        GOTO    HAVENOTE
        MOVWF   DLY
ADD12   MOVLW   D'12'
        ADDWF   NOTE,F
        DECFSZ  DLY,F
        GOTO    ADD12
HAVENOTE

; --- the duty for that note -----------------------------------------------------
        MOVLW   HIGH(DUTYH)
        MOVWF   PCLATH
        MOVF    NOTE,W
        CALL    DUTYH
        MOVWF   VH
        MOVF    NOTE,W
        CALL    DUTYL
        MOVWF   VL
        CLRF    PCLATH

        MOVF    VH,W
        MOVWF   CCPR1L
        SWAPF   VL,W            ; the two DC1B bits go to CCP1CON<5:4>
        IORLW   B'00001100'
        MOVWF   CCP1CON
        GOTO    LOOP

; --- subroutines ----------------------------------------------------------------
SHIFTADD
        BCF     STATUS,0
        RLF     ARGL,F          ; arg * 2
        RLF     ARGH,F
        MOVF    ARGL,W
        ADDWF   TOTL,F
        BTFSC   STATUS,0
        INCF    TOTH,F
        MOVF    ARGH,W
        ADDWF   TOTH,F
        RETURN

ACQUIRE MOVLW   D'40'           ; about 24 us for the sample capacitor to charge after a channel change
        MOVWF   DLY
ACQ1    DECFSZ  DLY,F
        GOTO    ACQ1
        RETURN

; --- tables ----------------------------------------------------------------------
        ORG     0300h
MODETBL ADDWF   PCL,F
        DT      0,0,2,2,2,2,4,4,4,5,5,5      ; MAJOR, first half
        DT      7,7,7,7,9,9,9,9,11,11,11,12      ; MAJOR, second half
        DT      0,0,2,2,2,2,4,4,4,4,4,7      ; MAJOR PENTATONIC, first half
        DT      7,7,7,7,9,9,9,9,9,12,12,12      ; MAJOR PENTATONIC, second half
        DT      0,0,2,2,2,3,3,3,5,5,5,5      ; MINOR, first half
        DT      7,7,7,8,8,8,10,10,10,10,12,12      ; MINOR, second half
        DT      0,0,0,3,3,3,3,3,5,5,5,5      ; MINOR PENTATONIC, first half
        DT      7,7,7,7,7,10,10,10,10,10,12,12      ; MINOR PENTATONIC, second half
        DT      0,1,1,2,2,3,3,4,4,5,5,6      ; CHROMATIC, first half
        DT      6,7,7,8,8,9,9,10,10,11,11,12      ; CHROMATIC, second half

        ORG     0400h
DUTYH   ADDWF   PCL,F
        DT      0,4,8,12,17,21,25,29,34,38,42,47
        DT      51,55,59,64,68,72,76,81,85,89,93,98
        DT      102,106,111,115,119,123,128,132,136,140,145,149
        DT      153,157,162,166,170,175,179,183,187,192,196,200
        DT      204,209,213,217,221,226,230,234,239,243,247,251
        DT      255
DUTYL   ADDWF   PCL,F
        DT      0,1,2,3,0,1,2,3,1,2,3,0
        DT      1,2,3,0,1,2,3,0,1,2,3,1
        DT      2,3,0,1,2,3,0,1,2,3,0,1
        DT      2,3,1,2,3,0,1,2,3,0,1,2
        DT      3,0,1,2,3,1,2,3,0,1,2,3
        DT      3

        END
