// Generated by panelkit from tools/panels/Projection.py. Do not edit; edit the spec.
//
// Everything the panel's C++ needs to agree with res/Projection.svg: the millimetre
// grid, the widget positions and the whole silkscreen. Rack's nanosvg discards
// <text>, so labels cannot live in the SVG -- they are drawn at runtime from
// the table below, generated from the same spec that drew the artwork.
//
// Every declaration here is `static`, i.e. private to the translation unit, so
// the three panels in this plugin cannot collide. That also means no
// translation unit may include two of these.
#pragma once
#include "../PanelTheme.hpp"

namespace panel {

// --- identity --------------------------------------------------------------
static const int   HP = 12;
static const float W  = 60.9600f;  // mm
static const float H  = 128.5000f;  // mm

// --- the read-out well: the spec's numbers, not the widget's ---------------
// A display used to be positioned by hand in the module's C++, in the same
// millimetres the spec had already chosen -- two copies of one number, and
// they drifted. The widget takes them from here now.
static const float GLASS_X = 4.2000f;
static const float GLASS_Y = 9.8000f;
static const float GLASS_W = 52.5600f;
static const float GLASS_H = 32.0000f;

// --- silkscreen ------------------------------------------------------------
static const Label LABELS[] = {
	{ 30.4800f,   5.5000f, 10.50f, 1.50f, PAPER    , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "PROJECTION"},
	{ 11.5600f,   8.2500f,  7.40f, 0.00f, LIME     , NVG_ALIGN_LEFT | NVG_ALIGN_BASELINE, true,  "$"},
	{ 13.7637f,   8.0000f,  4.60f, 0.40f, SAGE     , NVG_ALIGN_LEFT | NVG_ALIGN_BASELINE, false, "MOON TECHNOLOGIES"},
	{ 56.7600f,   8.0000f,  4.60f, 0.40f, SAGE     , NVG_ALIGN_RIGHT | NVG_ALIGN_BASELINE, false, "FORM 1120-W"},
	{ 30.4800f,  45.3000f,  6.00f, 0.60f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "SIGNAL"},
	{  9.2900f,  48.3618f,  6.20f, 0.00f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "L"},
	{ 21.5600f,  48.3618f,  6.20f, 0.00f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "R"},
	{ 36.0100f,  61.6587f,  7.00f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "SENS"},
	{ 50.4600f,  61.6587f,  7.00f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "TILT"},
	{ 30.4800f,  66.4587f,  6.00f, 0.60f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "PICTURE"},
	{ 10.5000f,  82.5656f,  7.00f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "MODE"},
	{ 23.8200f,  82.5656f,  7.00f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "SCALE"},
	{ 37.1400f,  82.5656f,  7.00f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "WARP"},
	{ 50.4600f,  82.5656f,  7.00f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "HUE"},
	{ 10.5000f, 109.3043f,  7.00f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "TRAIL"},
	{ 23.8200f, 109.3043f,  7.00f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "SAT"},
	{ 37.1400f,  96.0074f,  6.20f, 0.00f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "FLASH"},
	{ 50.4600f,  96.0074f,  6.20f, 0.00f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "FREEZE"},
	{ 10.1550f, 113.4100f,  6.20f, 0.00f, MINT     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "LOW"},
	{ 23.7050f, 113.4100f,  6.20f, 0.00f, MINT     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "MID"},
	{ 37.2550f, 113.4100f,  6.20f, 0.00f, MINT     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "HIGH"},
	{ 50.8050f, 113.4100f,  6.20f, 0.00f, MINT     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "ONSET"},
};

/** Draws this panel's silkscreen. `static` so each module keeps its own,
    bound to its own table. */
static inline void addLabels(app::ModuleWidget* mw) {
	addLabels(mw, LABELS, sizeof(LABELS) / sizeof(LABELS[0]));
}

// --- widget positions, by the names used in tools/panels/Projection.py -----
// Positions are mm; feed them to mm() or createParamCentered.
static const Vec AUDIO_L_POS = Vec(9.2900, 53.5518);
static const Vec AUDIO_R_POS = Vec(21.5600, 53.5518);
static const Vec SENS_POS = Vec(36.0100, 53.5518);
static const Vec TILT_POS = Vec(50.4600, 53.5518);
static const Vec MODE_POS = Vec(10.5000, 73.0587);
static const Vec SCALE_POS = Vec(23.8200, 73.0587);
static const Vec WARP_POS = Vec(37.1400, 73.0587);
static const Vec HUE_POS = Vec(50.4600, 73.0587);
static const Vec MODE_CV_POS = Vec(10.5000, 89.1556);
static const Vec SCALE_CV_POS = Vec(23.8200, 89.1556);
static const Vec WARP_CV_POS = Vec(37.1400, 89.1556);
static const Vec HUE_CV_POS = Vec(50.4600, 89.1556);
static const Vec TRAIL_POS = Vec(10.5000, 101.1974);
static const Vec SAT_POS = Vec(23.8200, 101.1974);
static const Vec FLASH_POS = Vec(37.1400, 101.1974);
static const Vec FREEZE_POS = Vec(50.4600, 101.1974);
static const Vec LOW_OUT_POS = Vec(10.1550, 118.6000);
static const Vec MID_OUT_POS = Vec(23.7050, 118.6000);
static const Vec HIGH_OUT_POS = Vec(37.2550, 118.6000);
static const Vec ONSET_OUT_POS = Vec(50.8050, 118.6000);

} // namespace panel
