// Generated by panelkit from tools/panels/Obfuscation.py. Do not edit; edit the spec.
//
// Everything the panel's C++ needs to agree with res/Obfuscation.svg: the millimetre
// grid, the widget positions and the whole silkscreen. Rack's nanosvg discards
// <text>, so labels cannot live in the SVG -- they are drawn at runtime from
// the table below, generated from the same spec that drew the artwork.
//
// Every declaration here is `static`, i.e. private to the translation unit, so
// the three panels in this plugin cannot collide. That also means no
// translation unit may include two of these.
#pragma once
#include "../PanelTheme.hpp"

namespace panel {

// --- identity --------------------------------------------------------------
static const int   HP = 12;
static const float W  = 60.9600f;  // mm
static const float H  = 128.5000f;  // mm
//: What the module is, as the masthead's second line says it.
static const char* const WHAT = "DISPERSION FILTER";

// --- the read-out well: the spec's numbers, not the widget's ---------------
// A display used to be positioned by hand in the module's C++, in the same
// millimetres the spec had already chosen -- two copies of one number, and
// they drifted. The widget takes them from here now.
static const float GLASS_X = 3.6000f;
static const float GLASS_Y = 9.8000f;
static const float GLASS_W = 53.7600f;
static const float GLASS_H = 32.0000f;

// --- controls on the glass: where each is drawn and where it is grabbed --
// One rectangle per Field in the spec, in panel mm. Place the widget with
// createField<Screen...>(FIELD_X, ...) -- or createMenuField for a "menu" --
// and draw the value in
// inGlass(FIELD_X), the same rectangle in the display's own pixels.
static const Rect FIELD_FREQ_FIELD = Rect(Vec(4.4000f, 10.6000f), Vec(17.0533f, 4.6500f));  // value: ScreenKnob
static const Rect FIELD_PINCH = Rect(Vec(21.9533f, 10.6000f), Vec(17.0533f, 4.6500f));  // value: ScreenKnob
static const Rect FIELD_STAGES = Rect(Vec(39.5067f, 10.6000f), Vec(17.0533f, 4.6500f));  // value: ScreenKnob
static const Rect FIELD_RANDOM = Rect(Vec(4.4000f, 36.3500f), Vec(17.0533f, 4.6500f));  // toggle: ScreenSwitch
static const Rect FIELD_MODE = Rect(Vec(21.9533f, 36.3500f), Vec(17.0533f, 4.6500f));  // toggle: ScreenSwitch

/** A field's rectangle in the display's pixels, for a display placed on the glass. */
static inline Rect inGlass(const Rect& f) {
	return mmRect(f.pos.x - GLASS_X, f.pos.y - GLASS_Y, f.size.x, f.size.y);
}

// --- silkscreen ------------------------------------------------------------
static const Label LABELS[] = {
	{ 30.4800f,   5.5000f, 10.50f, 1.50f, PAPER    , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "OBFUSCATION"},
	{  1.4000f,   8.2500f,  7.40f, 0.00f, LIME     , NVG_ALIGN_LEFT | NVG_ALIGN_BASELINE, 1,     "$"},
	{ 30.4800f,   8.0000f,  5.40f, 0.40f, LIME     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "DISPERSION FILTER"},
	{  2.1717f,  60.0500f,  4.60f, 0.40f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 2,     "MOON TECHNOLOGIES"},
	{ 58.7883f,  60.0500f,  4.60f, 0.40f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 3,     "FORM 1099-B"},
	{ 30.4800f,  45.3000f,  6.00f, 0.60f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "THE MATRIX"},
	{ 13.0247f,  65.2069f,  7.00f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "FREQ"},
	{ 32.3997f,  65.2069f,  7.00f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "SPREAD"},
	{ 13.0247f,  78.5952f,  6.20f, 0.00f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "FREQ"},
	{ 32.3997f,  78.5952f,  6.20f, 0.00f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "PINCH"},
	{ 51.7453f,  78.5952f,  6.20f, 0.00f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "STAGES"},
	{ 30.4800f,  94.4752f,  6.00f, 0.60f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "FINISHING"},
	{  9.1000f, 109.1821f,  7.00f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "DRIVE"},
	{ 23.3533f, 109.1821f,  7.00f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "BRIGHT"},
	{ 37.6067f, 109.1821f,  7.00f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "CLIP"},
	{ 51.8600f, 109.1821f,  7.00f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "BOOST"},
	{ 10.1550f, 113.4100f,  6.20f, 0.00f, SAGE     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "IN"},
	{ 23.7050f, 113.4100f,  6.20f, 0.00f, SAGE     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "CLOCK"},
	{ 37.2550f, 113.4100f,  6.20f, 0.00f, SAGE     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "FREEZE"},
	{ 50.8050f, 113.4100f,  6.20f, 0.00f, MINT     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "OUT"},
};

/** Draws this panel's silkscreen. `static` so each module keeps its own,
    bound to its own table. */
static inline void addLabels(app::ModuleWidget* mw) {
	addLabels(mw, LABELS, sizeof(LABELS) / sizeof(LABELS[0]));
}

// --- widget positions, by the names used in tools/panels/Obfuscation.py -----
// Positions are mm; feed them to mm() or createParamCentered.
static const Vec FREQ_POS = Vec(13.0247, 54.5000);
static const Vec SPREAD_POS = Vec(32.3997, 54.5000);
static const Vec FIRE_LED_POS = Vec(39.3069, 64.3534);
static const Vec FREQ_CV_POS = Vec(13.0247, 71.0634);
static const Vec PINCH_CV_POS = Vec(32.3997, 71.0634);
static const Vec STAGES_CV_POS = Vec(51.7453, 71.0634);
static const Vec FREQ_IN_POS = Vec(13.0247, 85.1852);
static const Vec PINCH_IN_POS = Vec(32.3997, 85.1852);
static const Vec STAGES_IN_POS = Vec(51.7453, 85.1852);
static const Vec DRIVE_POS = Vec(9.1000, 101.0752);
static const Vec BRIGHT_POS = Vec(23.3533, 101.0752);
static const Vec CLIP_POS = Vec(37.6067, 101.0752);
static const Vec BOOST_POS = Vec(51.8600, 101.0752);
static const Vec IN_POS = Vec(10.1550, 118.6000);
static const Vec CLOCK_POS = Vec(23.7050, 118.6000);
static const Vec GATE_POS = Vec(37.2550, 118.6000);
static const Vec OUT_POS = Vec(50.8050, 118.6000);

} // namespace panel
