// Generated by panelkit from tools/panels/Dependents.py. Do not edit; edit the spec.
//
// Everything the panel's C++ needs to agree with res/Dependents.svg: the millimetre
// grid, the widget positions and the whole silkscreen. Rack's nanosvg discards
// <text>, so labels cannot live in the SVG -- they are drawn at runtime from
// the table below, generated from the same spec that drew the artwork.
//
// Every declaration here is `static`, i.e. private to the translation unit, so
// the three panels in this plugin cannot collide. That also means no
// translation unit may include two of these.
#pragma once
#include "../PanelTheme.hpp"

namespace panel {

// --- identity --------------------------------------------------------------
static const int   HP = 14;
static const float W  = 71.1200f;  // mm
static const float H  = 128.5000f;  // mm
//: What the module is, as the masthead's second line says it.
static const char* const WHAT = "CHORD WAVESHAPER";

// --- the read-out well: the spec's numbers, not the widget's ---------------
// A display used to be positioned by hand in the module's C++, in the same
// millimetres the spec had already chosen -- two copies of one number, and
// they drifted. The widget takes them from here now.
static const float GLASS_X = 3.6000f;
static const float GLASS_Y = 9.8000f;
static const float GLASS_W = 63.9200f;
static const float GLASS_H = 33.0000f;

// --- controls on the glass: where each is drawn and where it is grabbed --
// One rectangle per Field in the spec, in panel mm. Place the widget with
// createField<Screen...>(FIELD_X, ...) -- or createMenuField for a "menu" --
// and draw the value in
// inGlass(FIELD_X), the same rectangle in the display's own pixels.
static const Rect FIELD_ROOT_FIELD = Rect(Vec(4.4000f, 10.6000f), Vec(20.4400f, 4.0571f));  // value: ScreenKnob
static const Rect FIELD_ROOT_QUANT = Rect(Vec(25.3400f, 10.6000f), Vec(9.9700f, 4.0571f));  // toggle: ScreenSwitch
static const Rect FIELD_ROOT_SCALE = Rect(Vec(35.8100f, 10.6000f), Vec(15.2050f, 4.0571f));  // select: ScreenSelect
static const Rect FIELD_NORM = Rect(Vec(51.5150f, 10.6000f), Vec(15.2050f, 4.0571f));  // toggle: ScreenSwitch
static const Rect FIELD_CHORD_A = Rect(Vec(4.4000f, 15.1571f), Vec(30.9100f, 4.0571f));  // select: ScreenSelect
static const Rect FIELD_CHORD_B = Rect(Vec(35.8100f, 15.1571f), Vec(30.9100f, 4.0571f));  // select: ScreenSelect
static const Rect FIELD_H1 = Rect(Vec(4.4000f, 19.7143f), Vec(4.7350f, 22.2857f));  // value: ScreenKnob
static const Rect FIELD_H2 = Rect(Vec(9.6350f, 19.7143f), Vec(4.7350f, 22.2857f));  // value: ScreenKnob
static const Rect FIELD_H3 = Rect(Vec(14.8700f, 19.7143f), Vec(4.7350f, 22.2857f));  // value: ScreenKnob
static const Rect FIELD_H4 = Rect(Vec(20.1050f, 19.7143f), Vec(4.7350f, 22.2857f));  // value: ScreenKnob
static const Rect FIELD_H5 = Rect(Vec(25.3400f, 19.7143f), Vec(4.7350f, 22.2857f));  // value: ScreenKnob
static const Rect FIELD_H6 = Rect(Vec(30.5750f, 19.7143f), Vec(4.7350f, 22.2857f));  // value: ScreenKnob
static const Rect FIELD_H7 = Rect(Vec(35.8100f, 19.7143f), Vec(4.7350f, 22.2857f));  // value: ScreenKnob
static const Rect FIELD_H8 = Rect(Vec(41.0450f, 19.7143f), Vec(4.7350f, 22.2857f));  // value: ScreenKnob
static const Rect FIELD_H9 = Rect(Vec(46.2800f, 19.7143f), Vec(4.7350f, 22.2857f));  // value: ScreenKnob
static const Rect FIELD_H10 = Rect(Vec(51.5150f, 19.7143f), Vec(4.7350f, 22.2857f));  // value: ScreenKnob
static const Rect FIELD_H11 = Rect(Vec(56.7500f, 19.7143f), Vec(4.7350f, 22.2857f));  // value: ScreenKnob
static const Rect FIELD_H12 = Rect(Vec(61.9850f, 19.7143f), Vec(4.7350f, 22.2857f));  // value: ScreenKnob

/** A field's rectangle in the display's pixels, for a display placed on the glass. */
static inline Rect inGlass(const Rect& f) {
	return mmRect(f.pos.x - GLASS_X, f.pos.y - GLASS_Y, f.size.x, f.size.y);
}

// --- silkscreen ------------------------------------------------------------
static const Label LABELS[] = {
	{ 35.5600f,   5.5000f, 10.50f, 1.50f, PAPER    , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "DEPENDENTS"},
	{  1.4000f,   8.2500f,  7.40f, 0.00f, LIME     , NVG_ALIGN_LEFT | NVG_ALIGN_BASELINE, 1,     "$"},
	{ 35.5600f,   8.0000f,  5.40f, 0.40f, LIME     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "CHORD WAVESHAPER"},
	{  2.1717f,  60.0500f,  4.60f, 0.40f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 2,     "MOON TECHNOLOGIES"},
	{ 68.9483f,  60.0500f,  4.60f, 0.40f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 3,     "FORM 8812"},
	{ 35.5600f,  46.3000f,  6.00f, 0.60f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "QUALIFYING CHILD"},
	{ 19.3450f,  66.2069f,  7.00f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "ROOT"},
	{ 38.1000f,  66.2069f,  7.00f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "MORPH"},
	{ 54.3750f,  66.2069f,  7.00f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "TILT"},
	{ 19.3450f,  80.8638f,  7.00f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "CHORDS"},
	{ 38.1000f,  80.8638f,  7.00f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "MIX"},
	{ 54.3750f,  80.8638f,  7.00f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "LEVEL"},
	{ 35.5600f,  85.6638f,  6.00f, 0.60f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "SCHEDULE"},
	{  7.8900f,  98.0156f,  6.20f, 0.00f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "MORPH"},
	{ 18.9580f,  98.0156f,  6.20f, 0.00f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "TILT"},
	{ 30.0260f,  98.0156f,  6.20f, 0.00f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "CHORD A"},
	{ 41.0940f,  98.0156f,  6.20f, 0.00f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "CHORD B"},
	{ 52.1620f,  98.0156f,  6.20f, 0.00f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "CHORDS"},
	{ 63.2300f,  98.0156f,  6.20f, 0.00f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "LEVEL"},
	{ 15.2350f, 113.4100f,  6.20f, 0.00f, SAGE     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "IN"},
	{ 28.7850f, 113.4100f,  6.20f, 0.00f, SAGE     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "V/OCT"},
	{ 42.3350f, 113.4100f,  6.20f, 0.00f, MINT     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "ROOT"},
	{ 55.8850f, 113.4100f,  6.20f, 0.00f, MINT     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "OUT"},
};

/** Draws this panel's silkscreen. `static` so each module keeps its own,
    bound to its own table. */
static inline void addLabels(app::ModuleWidget* mw) {
	addLabels(mw, LABELS, sizeof(LABELS) / sizeof(LABELS[0]));
}

// --- widget positions, by the names used in tools/panels/Dependents.py -----
// Positions are mm; feed them to mm() or createParamCentered.
static const Vec ROOT_POS = Vec(19.3450, 55.5000);
static const Vec MORPH_POS = Vec(38.1000, 55.5000);
static const Vec TILT_POS = Vec(54.3750, 55.5000);
static const Vec DRIVE_POS = Vec(19.3450, 72.7569);
static const Vec MIX_POS = Vec(38.1000, 72.7569);
static const Vec LEVEL_POS = Vec(54.3750, 72.7569);
static const Vec MORPH_CV_POS = Vec(7.8900, 90.4838);
static const Vec TILT_CV_POS = Vec(18.9580, 90.4838);
static const Vec CHORD_A_CV_POS = Vec(30.0260, 90.4838);
static const Vec CHORD_B_CV_POS = Vec(41.0940, 90.4838);
static const Vec DRIVE_CV_POS = Vec(52.1620, 90.4838);
static const Vec LEVEL_CV_POS = Vec(63.2300, 90.4838);
static const Vec MORPH_IN_POS = Vec(7.8900, 104.6056);
static const Vec TILT_IN_POS = Vec(18.9580, 104.6056);
static const Vec CHORD_A_IN_POS = Vec(30.0260, 104.6056);
static const Vec CHORD_B_IN_POS = Vec(41.0940, 104.6056);
static const Vec DRIVE_IN_POS = Vec(52.1620, 104.6056);
static const Vec LEVEL_IN_POS = Vec(63.2300, 104.6056);
static const Vec IN_POS = Vec(15.2350, 118.6000);
static const Vec VOCT_POS = Vec(28.7850, 118.6000);
static const Vec SUB_POS = Vec(42.3350, 118.6000);
static const Vec OUT_POS = Vec(55.8850, 118.6000);

} // namespace panel
