// Generated by panelkit from tools/panels/Dependents.py. Do not edit; edit the spec.
//
// Everything the panel's C++ needs to agree with res/Dependents.svg: the millimetre
// grid, the widget positions and the whole silkscreen. Rack's nanosvg discards
// <text>, so labels cannot live in the SVG -- they are drawn at runtime from
// the table below, generated from the same spec that drew the artwork.
//
// Every declaration here is `static`, i.e. private to the translation unit, so
// the three panels in this plugin cannot collide. That also means no
// translation unit may include two of these.
#pragma once
#include "../PanelTheme.hpp"

namespace panel {

// --- identity --------------------------------------------------------------
static const int   HP = 16;
static const float W  = 81.2800f;  // mm
static const float H  = 128.5000f;  // mm

// --- silkscreen ------------------------------------------------------------
static const Label LABELS[] = {
	{ 40.6400f,   5.5000f, 10.50f, 1.50f, PAPER    , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "DEPENDENTS"},
	{ 11.5600f,   8.2500f,  7.40f, 0.00f, LIME     , NVG_ALIGN_LEFT | NVG_ALIGN_BASELINE, true,  "$"},
	{ 13.7637f,   8.0000f,  4.60f, 0.40f, SAGE     , NVG_ALIGN_LEFT | NVG_ALIGN_BASELINE, false, "MOON TECHNOLOGIES"},
	{ 77.0800f,   8.0000f,  4.60f, 0.40f, SAGE     , NVG_ALIGN_RIGHT | NVG_ALIGN_BASELINE, false, "FORM 8812"},
	{ 40.6400f,  13.3000f,  6.00f, 0.60f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "QUALIFYING CHILD"},
	{ 13.1000f,  33.5149f,  7.00f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "ROOT"},
	{ 29.3800f,  33.5149f,  6.20f, 0.00f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "QUANT"},
	{ 43.1800f,  33.5149f,  7.00f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "SCALE"},
	{ 56.9800f,  33.5149f,  7.00f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "CHORD A"},
	{ 70.7800f,  33.5149f,  7.00f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "CHORD B"},
	{ 13.1000f,  49.3152f,  7.00f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "MORPH"},
	{ 29.3800f,  49.3152f,  7.00f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "TILT"},
	{ 43.1800f,  49.3152f,  7.00f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "CHORDS"},
	{ 56.9800f,  49.3152f,  7.00f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "MIX"},
	{ 70.7800f,  49.3152f,  7.00f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "LEVEL"},
	{ 40.6400f,  54.7337f,  6.00f, 0.60f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "SCHEDULE"},
	{  9.2900f,  67.5655f,  6.20f, 0.00f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "MORPH"},
	{ 20.2067f,  67.5655f,  6.20f, 0.00f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "TILT"},
	{ 31.1233f,  67.5655f,  6.20f, 0.00f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "CHORD A"},
	{ 42.0400f,  67.5655f,  6.20f, 0.00f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "CHORD B"},
	{ 52.9567f,  67.5655f,  6.20f, 0.00f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "CHORDS"},
	{ 63.8733f,  67.5655f,  6.20f, 0.00f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "LEVEL"},
	{ 73.2100f,  67.5655f,  6.20f, 0.00f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "HOLD"},
	{ 40.6400f,  84.0641f,  6.00f, 0.60f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "ITEMIZED HARMONICS"},
	{ 40.6400f,  95.0159f,  6.20f, 0.00f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "1 - 6"},
	{ 40.6400f, 106.5362f,  6.20f, 0.00f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "7 - 12"},
	{ 20.3150f, 112.8851f,  6.20f, 0.00f, SAGE     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "IN"},
	{ 33.8650f, 112.8851f,  6.20f, 0.00f, SAGE     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "V/OCT"},
	{ 47.4150f, 112.8851f,  6.20f, 0.00f, MINT     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "ROOT"},
	{ 60.9650f, 112.8851f,  6.20f, 0.00f, MINT     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "OUT"},
};

/** Draws this panel's silkscreen. `static` so each module keeps its own,
    bound to its own table. */
static inline void addLabels(app::ModuleWidget* mw) {
	addLabels(mw, LABELS, sizeof(LABELS) / sizeof(LABELS[0]));
}

// --- widget positions, by the names used in tools/panels/Dependents.py -----
// Positions are mm; feed them to mm() or createParamCentered.
static const Vec ROOT_POS = Vec(13.1000, 22.8080);
static const Vec ROOT_QUANT_POS = Vec(29.3800, 22.8080);
static const Vec ROOT_SCALE_POS = Vec(43.1800, 22.8080);
static const Vec CHORD_A_POS = Vec(56.9800, 22.8080);
static const Vec CHORD_B_POS = Vec(70.7800, 22.8080);
static const Vec MORPH_POS = Vec(13.1000, 41.2083);
static const Vec TILT_POS = Vec(29.3800, 41.2083);
static const Vec DRIVE_POS = Vec(43.1800, 41.2083);
static const Vec MIX_POS = Vec(56.9800, 41.2083);
static const Vec LEVEL_POS = Vec(70.7800, 41.2083);
static const Vec MORPH_CV_POS = Vec(9.2900, 60.0337);
static const Vec TILT_CV_POS = Vec(20.2067, 60.0337);
static const Vec CHORD_A_CV_POS = Vec(31.1233, 60.0337);
static const Vec CHORD_B_CV_POS = Vec(42.0400, 60.0337);
static const Vec DRIVE_CV_POS = Vec(52.9567, 60.0337);
static const Vec LEVEL_CV_POS = Vec(63.8733, 60.0337);
static const Vec NORM_POS = Vec(73.2100, 60.0337);
static const Vec MORPH_IN_POS = Vec(9.2900, 74.1555);
static const Vec TILT_IN_POS = Vec(20.2067, 74.1555);
static const Vec CHORD_A_IN_POS = Vec(31.1233, 74.1555);
static const Vec CHORD_B_IN_POS = Vec(42.0400, 74.1555);
static const Vec DRIVE_IN_POS = Vec(52.9567, 74.1555);
static const Vec LEVEL_IN_POS = Vec(63.8733, 74.1555);
static const Vec H1_POS = Vec(11.4525, 88.8841);
static const Vec H2_POS = Vec(23.1275, 88.8841);
static const Vec H3_POS = Vec(34.8025, 88.8841);
static const Vec H4_POS = Vec(46.4775, 88.8841);
static const Vec H5_POS = Vec(58.1525, 88.8841);
static const Vec H6_POS = Vec(69.8275, 88.8841);
static const Vec H7_POS = Vec(11.4525, 100.4044);
static const Vec H8_POS = Vec(23.1275, 100.4044);
static const Vec H9_POS = Vec(34.8025, 100.4044);
static const Vec H10_POS = Vec(46.4775, 100.4044);
static const Vec H11_POS = Vec(58.1525, 100.4044);
static const Vec H12_POS = Vec(69.8275, 100.4044);
static const Vec IN_POS = Vec(20.3150, 118.6000);
static const Vec VOCT_POS = Vec(33.8650, 118.6000);
static const Vec SUB_POS = Vec(47.4150, 118.6000);
static const Vec OUT_POS = Vec(60.9650, 118.6000);

} // namespace panel
