// Generated by panelkit from tools/panels/Dependents.py. Do not edit; edit the spec.
//
// Everything the panel's C++ needs to agree with res/Dependents.svg: the millimetre
// grid, the widget positions and the whole silkscreen. Rack's nanosvg discards
// <text>, so labels cannot live in the SVG -- they are drawn at runtime from
// the table below, generated from the same spec that drew the artwork.
//
// Every declaration here is `static`, i.e. private to the translation unit, so
// the three panels in this plugin cannot collide. That also means no
// translation unit may include two of these.
#pragma once
#include "../PanelTheme.hpp"

namespace panel {

// --- identity --------------------------------------------------------------
static const int   HP = 16;
static const float W  = 81.2800f;  // mm
static const float H  = 128.5000f;  // mm

// --- silkscreen ------------------------------------------------------------
static const Label LABELS[] = {
	{ 40.6400f,   5.5000f, 10.50f, 1.50f, PAPER    , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "DEPENDENTS"},
	{ 11.5600f,   8.2500f,  7.40f, 0.00f, LIME     , NVG_ALIGN_LEFT | NVG_ALIGN_BASELINE, true,  "$"},
	{ 13.7637f,   8.0000f,  4.60f, 0.40f, SAGE     , NVG_ALIGN_LEFT | NVG_ALIGN_BASELINE, false, "MOON TECHNOLOGIES"},
	{ 77.0800f,   8.0000f,  4.60f, 0.40f, SAGE     , NVG_ALIGN_RIGHT | NVG_ALIGN_BASELINE, false, "FORM 8812"},
	{ 40.6400f,  13.3000f,  6.00f, 0.60f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "QUALIFYING CHILD"},
	{ 11.7000f,  33.2069f,  7.00f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "ROOT"},
	{ 28.6800f,  33.2069f,  6.20f, 0.00f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "QUANT"},
	{ 43.1800f,  33.2069f,  7.00f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "SCALE"},
	{ 57.6800f,  33.2069f,  7.00f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "CHORD A"},
	{ 72.1800f,  33.2069f,  7.00f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "CHORD B"},
	{ 11.7000f,  48.7922f,  7.00f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "MORPH"},
	{ 28.6800f,  48.7922f,  7.00f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "TILT"},
	{ 43.1800f,  48.7922f,  7.00f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "CHORDS"},
	{ 57.6800f,  48.7922f,  7.00f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "MIX"},
	{ 72.1800f,  48.7922f,  7.00f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "LEVEL"},
	{ 40.6400f,  54.5207f,  6.00f, 0.60f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "SCHEDULE"},
	{  7.8900f,  67.3525f,  6.20f, 0.00f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "MORPH"},
	{ 19.2733f,  67.3525f,  6.20f, 0.00f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "TILT"},
	{ 30.6567f,  67.3525f,  6.20f, 0.00f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "CHORD A"},
	{ 42.0400f,  67.3525f,  6.20f, 0.00f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "CHORD B"},
	{ 53.4233f,  67.3525f,  6.20f, 0.00f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "CHORDS"},
	{ 64.8067f,  67.3525f,  6.20f, 0.00f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "LEVEL"},
	{ 74.6100f,  67.3525f,  6.20f, 0.00f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "HOLD"},
	{ 40.6400f,  84.1610f,  6.00f, 0.60f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "ITEMIZED HARMONICS"},
	{ 40.6400f,  95.1128f,  6.20f, 0.00f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "1 - 6"},
	{ 40.6400f, 106.9431f,  6.20f, 0.00f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "7 - 12"},
	{ 20.3150f, 113.4100f,  6.20f, 0.00f, SAGE     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "IN"},
	{ 33.8650f, 113.4100f,  6.20f, 0.00f, SAGE     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "V/OCT"},
	{ 47.4150f, 113.4100f,  6.20f, 0.00f, MINT     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "ROOT"},
	{ 60.9650f, 113.4100f,  6.20f, 0.00f, MINT     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "OUT"},
};

/** Draws this panel's silkscreen. `static` so each module keeps its own,
    bound to its own table. */
static inline void addLabels(app::ModuleWidget* mw) {
	addLabels(mw, LABELS, sizeof(LABELS) / sizeof(LABELS[0]));
}

// --- widget positions, by the names used in tools/panels/Dependents.py -----
// Positions are mm; feed them to mm() or createParamCentered.
static const Vec ROOT_POS = Vec(11.7000, 22.5000);
static const Vec ROOT_QUANT_POS = Vec(28.6800, 22.5000);
static const Vec ROOT_SCALE_POS = Vec(43.1800, 22.5000);
static const Vec CHORD_A_POS = Vec(57.6800, 22.5000);
static const Vec CHORD_B_POS = Vec(72.1800, 22.5000);
static const Vec MORPH_POS = Vec(11.7000, 40.6853);
static const Vec TILT_POS = Vec(28.6800, 40.6853);
static const Vec DRIVE_POS = Vec(43.1800, 40.6853);
static const Vec MIX_POS = Vec(57.6800, 40.6853);
static const Vec LEVEL_POS = Vec(72.1800, 40.6853);
static const Vec MORPH_CV_POS = Vec(7.8900, 59.8207);
static const Vec TILT_CV_POS = Vec(19.2733, 59.8207);
static const Vec CHORD_A_CV_POS = Vec(30.6567, 59.8207);
static const Vec CHORD_B_CV_POS = Vec(42.0400, 59.8207);
static const Vec DRIVE_CV_POS = Vec(53.4233, 59.8207);
static const Vec LEVEL_CV_POS = Vec(64.8067, 59.8207);
static const Vec NORM_POS = Vec(74.6100, 59.8207);
static const Vec MORPH_IN_POS = Vec(7.8900, 73.9425);
static const Vec TILT_IN_POS = Vec(19.2733, 73.9425);
static const Vec CHORD_A_IN_POS = Vec(30.6567, 73.9425);
static const Vec CHORD_B_IN_POS = Vec(42.0400, 73.9425);
static const Vec DRIVE_IN_POS = Vec(53.4233, 73.9425);
static const Vec LEVEL_IN_POS = Vec(64.8067, 73.9425);
static const Vec H1_POS = Vec(11.4525, 88.9810);
static const Vec H2_POS = Vec(23.1275, 88.9810);
static const Vec H3_POS = Vec(34.8025, 88.9810);
static const Vec H4_POS = Vec(46.4775, 88.9810);
static const Vec H5_POS = Vec(58.1525, 88.9810);
static const Vec H6_POS = Vec(69.8275, 88.9810);
static const Vec H7_POS = Vec(11.4525, 100.8113);
static const Vec H8_POS = Vec(23.1275, 100.8113);
static const Vec H9_POS = Vec(34.8025, 100.8113);
static const Vec H10_POS = Vec(46.4775, 100.8113);
static const Vec H11_POS = Vec(58.1525, 100.8113);
static const Vec H12_POS = Vec(69.8275, 100.8113);
static const Vec IN_POS = Vec(20.3150, 118.6000);
static const Vec VOCT_POS = Vec(33.8650, 118.6000);
static const Vec SUB_POS = Vec(47.4150, 118.6000);
static const Vec OUT_POS = Vec(60.9650, 118.6000);

} // namespace panel
