// Generated by panelkit from tools/panels/Toll.py. Do not edit; edit the spec.
//
// Everything the panel's C++ needs to agree with res/Toll.svg: the millimetre
// grid, the widget positions and the whole silkscreen. Rack's nanosvg discards
// <text>, so labels cannot live in the SVG -- they are drawn at runtime from
// the table below, generated from the same spec that drew the artwork.
//
// Every declaration here is `static`, i.e. private to the translation unit, so
// the three panels in this plugin cannot collide. That also means no
// translation unit may include two of these.
#pragma once
#include "../PanelTheme.hpp"

namespace panel {

// --- identity --------------------------------------------------------------
static const int   HP = 10;
static const float W  = 50.8000f;  // mm
static const float H  = 128.5000f;  // mm
//: What the module is, as the masthead's second line says it.
static const char* const WHAT = "STRUCK-METAL VOICE";

// --- silkscreen ------------------------------------------------------------
static const Label LABELS[] = {
	{ 25.4000f,   5.5000f, 10.50f, 1.50f, PAPER    , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "TOLL"},
	{  1.4000f,   8.2500f,  7.40f, 0.00f, LIME     , NVG_ALIGN_LEFT | NVG_ALIGN_BASELINE, 1,     "$"},
	{ 25.4000f,   8.0000f,  5.40f, 0.40f, LIME     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "STRUCK-METAL VOICE"},
	{  2.1717f,  60.0491f,  4.60f, 0.40f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 2,     "MOON TECHNOLOGIES"},
	{ 48.6283f,  29.0393f,  4.60f, 0.40f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 3,     "FORM 2290"},
	{ 25.4000f,  14.0000f,  6.00f, 0.60f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "HIGHWAY USE"},
	{ 11.7000f,  18.2459f,  6.20f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "TRIG"},
	{ 28.0000f,  18.2459f,  6.20f, 0.00f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "V/OCT"},
	{ 41.7000f,  18.2459f,  6.20f, 0.00f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "VEL"},
	{ 11.7000f,  51.7620f,  7.00f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "TUNE"},
	{ 28.0000f,  51.7620f,  7.00f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "SET"},
	{ 41.7000f,  51.7620f,  7.00f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "BUZZ"},
	{ 11.7000f,  69.9141f,  7.00f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "DECAY"},
	{ 28.0000f,  69.9141f,  7.00f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "DAMP"},
	{ 41.7000f,  69.9141f,  7.00f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "BEND"},
	{ 11.7000f,  88.0661f,  7.00f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "STRIKE"},
	{ 28.0000f,  88.0661f,  7.00f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "HARD"},
	{ 41.7000f,  88.0661f,  7.00f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "SPREAD"},
	{ 11.7000f,  93.8230f,  6.20f, 0.00f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "SPRD"},
	{ 28.0000f,  93.8230f,  6.20f, 0.00f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "BEND"},
	{ 41.7000f,  93.8230f,  6.20f, 0.00f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "CHOKE"},
	{ 11.1260f, 113.3100f,  6.20f, 0.00f, SAGE     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "STRK"},
	{ 25.4000f, 113.3100f,  6.20f, 0.00f, SAGE     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "DECAY"},
	{ 39.6740f, 113.3100f,  6.20f, 0.00f, MINT     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "OUT"},
};

/** Draws this panel's silkscreen. `static` so each module keeps its own,
    bound to its own table. */
static inline void addLabels(app::ModuleWidget* mw) {
	addLabels(mw, LABELS, sizeof(LABELS) / sizeof(LABELS[0]));
}

// --- widget positions, by the names used in tools/panels/Toll.py -----
// Positions are mm; feed them to mm() or createParamCentered.
static const Vec TRIG_POS = Vec(11.7000, 23.9200);
static const Vec VOCT_POS = Vec(28.0000, 23.9200);
static const Vec VEL_POS = Vec(41.7000, 23.9200);
static const Vec HIT_LED_POS = Vec(16.8597, 17.4900);
static const Vec TUNE_POS = Vec(11.7000, 40.9551);
static const Vec SET_POS = Vec(28.0000, 40.9551);
static const Vec BUZZ_POS = Vec(41.7000, 40.9551);
static const Vec DECAY_POS = Vec(11.7000, 61.7072);
static const Vec DAMP_POS = Vec(28.0000, 61.7072);
static const Vec BEND_POS = Vec(41.7000, 61.7072);
static const Vec STRIKE_POS = Vec(11.7000, 79.8592);
static const Vec HARD_POS = Vec(28.0000, 79.8592);
static const Vec SPREAD_POS = Vec(41.7000, 79.8592);
static const Vec SPREAD_CV_POS = Vec(11.7000, 99.1130);
static const Vec BEND_CV_POS = Vec(28.0000, 99.1130);
static const Vec CHOKE_POS = Vec(41.7000, 99.1130);
static const Vec STRIKE_CV_POS = Vec(11.1260, 118.6000);
static const Vec DECAY_CV_POS = Vec(25.4000, 118.6000);
static const Vec OUT_POS = Vec(39.6740, 118.6000);

} // namespace panel
