#include "../plugin.hpp"
#include "Panel.hpp"
#include "Voice.hpp"

using namespace toll;


struct TollModule : Module {
	enum ParamId {
		TUNE_PARAM, SET_PARAM, BUZZ_PARAM,
		DECAY_PARAM, DAMP_PARAM, BEND_PARAM,
		STRIKE_PARAM, HARD_PARAM, SPREAD_PARAM,
		PARAMS_LEN
	};
	enum InputId {
		TRIG_INPUT, VOCT_INPUT, STRIKE_CV_INPUT, DECAY_CV_INPUT,
		SPREAD_CV_INPUT, BEND_CV_INPUT, CHOKE_INPUT, INPUTS_LEN
	};
	enum OutputId { OUT_OUTPUT, OUTPUTS_LEN };
	enum LightId { HIT_LIGHT, LIGHTS_LEN };

	Toll voice;
	dsp::SchmittTrigger trig;
	dsp::ClockDivider lightDivider;
	bool litSince = false;
	float ledLevel = 0.f;

	TollModule() {
		config(PARAMS_LEN, INPUTS_LEN, OUTPUTS_LEN, LIGHTS_LEN);

		configParam(TUNE_PARAM, 0.f, 1.f, 0.42f, "Tune");
		configSwitch(SET_PARAM, 0.f, 3.f, 2.f, "Partials",
			{"Membrane (a drum head)", "Bar (a metallophone)",
			 "Bell (a tuned bell)", "Harmonic (not an object)"});
		configParam(BUZZ_PARAM, 0.f, 1.f, 0.2f, "Buzz", "%", 0.f, 100.f);
		configParam(DECAY_PARAM, 0.f, 1.f, 0.55f, "Decay");
		configParam(DAMP_PARAM, 0.f, 1.f, 0.35f, "Damping", "%", 0.f, 100.f);
		configParam(BEND_PARAM, 0.f, 1.f, 0.25f, "Bend", "%", 0.f, 100.f);
		configParam(STRIKE_PARAM, 0.f, 1.f, 0.42f, "Strike position", "%", 0.f, 100.f);
		configParam(HARD_PARAM, 0.f, 1.f, 0.60f, "Mallet hardness", "%", 0.f, 100.f);
		configParam(SPREAD_PARAM, 0.f, 1.f, 0.f, "Partial spread", "%", 0.f, 100.f);

		configInput(TRIG_INPUT, "Trigger");
		configInput(VOCT_INPUT, "V/oct");
		configInput(STRIKE_CV_INPUT, "Strike position CV");
		configInput(DECAY_CV_INPUT, "Decay CV");
		configInput(SPREAD_CV_INPUT, "Spread CV");
		configInput(BEND_CV_INPUT, "Bend CV");
		configInput(CHOKE_INPUT, "Choke gate");
		configOutput(OUT_OUTPUT, "Audio");
		configLight(HIT_LIGHT, "Struck");

		lightDivider.setDivision(32);
		onSampleRateChange({APP->engine->getSampleRate(), 0.f});
	}

	void onSampleRateChange(const SampleRateChangeEvent& e) override {
		voice.reset();
		voice.setRate(e.sampleRate);
	}

	void onReset(const ResetEvent& e) override {
		Module::onReset(e);
		voice.reset();
		litSince = false;
		ledLevel = 0.f;
	}

	void process(const ProcessArgs& args) override {
		bool hit = trig.process(inputs[TRIG_INPUT].getVoltage(), 0.1f, 1.f);
		if (hit) litSince = true;

		float volts = inputs[VOCT_INPUT].isConnected() ? inputs[VOCT_INPUT].getVoltage() : 0.f;

		// The four CV jacks add to their knobs at a tenth of a volt per
		// percent, so a +-5 V modulation covers the whole of a control and a
		// unipolar 0-10 V one reaches from its bottom to its top.
		float strikeCv = inputs[STRIKE_CV_INPUT].isConnected()
			? inputs[STRIKE_CV_INPUT].getVoltage() * 0.1f : 0.f;
		float decayCv = inputs[DECAY_CV_INPUT].isConnected()
			? inputs[DECAY_CV_INPUT].getVoltage() * 0.1f : 0.f;

		float spreadCv = inputs[SPREAD_CV_INPUT].isConnected()
			? inputs[SPREAD_CV_INPUT].getVoltage() * 0.1f : 0.f;
		float bendCv = inputs[BEND_CV_INPUT].isConnected()
			? inputs[BEND_CV_INPUT].getVoltage() * 0.1f : 0.f;

		float pos = clamp(params[STRIKE_PARAM].getValue() + strikeCv, 0.f, 1.f);
		float dec = clamp(params[DECAY_PARAM].getValue() + decayCv, 0.f, 1.f);
		float spr = clamp(params[SPREAD_PARAM].getValue() + spreadCv, 0.f, 1.f);
		float bnd = clamp(params[BEND_PARAM].getValue() + bendCv, 0.f, 1.f);
		// A plain level, not an edge: holding CHOKE holds the damping on.
		bool choke = inputs[CHOKE_INPUT].getVoltage() >= 1.f;
		int set = (int)clamp(std::round(params[SET_PARAM].getValue()), 0.f, 3.f);

		float y = voice.process(hit, 1.f, set,
			params[TUNE_PARAM].getValue(), volts,
			dec, params[DAMP_PARAM].getValue(), pos,
			params[HARD_PARAM].getValue(), spr, bnd,
			params[BUZZ_PARAM].getValue(), choke);

		outputs[OUT_OUTPUT].setVoltage(clamp(y, -12.f, 12.f));

		if (lightDivider.process()) {
			float dt = args.sampleTime * lightDivider.getDivision();
			ledLevel = litSince ? 1.f : ledLevel * std::exp(-dt / 0.12f);
			litSince = false;
			lights[HIT_LIGHT].setBrightness(ledLevel);
		}
	}
};


// ---------------------------------------------------------------------------
// Look and feel comes entirely from src/PanelTheme.hpp and src/Toll/Panel.hpp,
// generated by tools/panels/Toll.py -- see ../../panelkit/README.md.

struct TollWidget : ModuleWidget {
	TollWidget(TollModule* module) {
		setModule(module);
		setPanel(createPanel(asset::plugin(pluginInstance, "res/Toll.svg")));

		panel::addScrews(this);
		panel::addLabels(this);

		addInput(createInputCentered<panel::PortTrigInMain>(panel::mm(panel::TRIG_POS.x, panel::TRIG_POS.y), module, TollModule::TRIG_INPUT));
		addInput(createInputCentered<panel::PortIn>(panel::mm(panel::VOCT_POS.x, panel::VOCT_POS.y), module, TollModule::VOCT_INPUT));
		addChild(createLightCentered<SmallLight<panel::PaperLight> >(
			panel::mm(panel::HIT_LED_POS.x, panel::HIT_LED_POS.y), module, TollModule::HIT_LIGHT));

		addParam(createParamCentered<RoundLargeBlackKnob>(panel::mm(panel::TUNE_POS.x, panel::TUNE_POS.y), module, TollModule::TUNE_PARAM));
		addParam(createParamCentered<RoundBlackKnob>(panel::mm(panel::SET_POS.x, panel::SET_POS.y), module, TollModule::SET_PARAM));
		addParam(createParamCentered<RoundBlackKnob>(panel::mm(panel::BUZZ_POS.x, panel::BUZZ_POS.y), module, TollModule::BUZZ_PARAM));

		addParam(createParamCentered<RoundBlackKnob>(panel::mm(panel::DECAY_POS.x, panel::DECAY_POS.y), module, TollModule::DECAY_PARAM));
		addParam(createParamCentered<RoundBlackKnob>(panel::mm(panel::DAMP_POS.x, panel::DAMP_POS.y), module, TollModule::DAMP_PARAM));
		addParam(createParamCentered<RoundBlackKnob>(panel::mm(panel::BEND_POS.x, panel::BEND_POS.y), module, TollModule::BEND_PARAM));

		addParam(createParamCentered<RoundBlackKnob>(panel::mm(panel::STRIKE_POS.x, panel::STRIKE_POS.y), module, TollModule::STRIKE_PARAM));
		addParam(createParamCentered<RoundBlackKnob>(panel::mm(panel::HARD_POS.x, panel::HARD_POS.y), module, TollModule::HARD_PARAM));
		addParam(createParamCentered<RoundBlackKnob>(panel::mm(panel::SPREAD_POS.x, panel::SPREAD_POS.y), module, TollModule::SPREAD_PARAM));

		addInput(createInputCentered<panel::PortIn>(panel::mm(panel::SPREAD_CV_POS.x, panel::SPREAD_CV_POS.y), module, TollModule::SPREAD_CV_INPUT));
		addInput(createInputCentered<panel::PortIn>(panel::mm(panel::BEND_CV_POS.x, panel::BEND_CV_POS.y), module, TollModule::BEND_CV_INPUT));
		// TRIG and CHOKE are gates; V/OCT and the three CV jacks are levels.
		addInput(createInputCentered<panel::PortTrigIn>(panel::mm(panel::CHOKE_POS.x, panel::CHOKE_POS.y), module, TollModule::CHOKE_INPUT));
		addInput(createInputCentered<panel::PortIn>(panel::mm(panel::STRIKE_CV_POS.x, panel::STRIKE_CV_POS.y), module, TollModule::STRIKE_CV_INPUT));
		addInput(createInputCentered<panel::PortIn>(panel::mm(panel::DECAY_CV_POS.x, panel::DECAY_CV_POS.y), module, TollModule::DECAY_CV_INPUT));
		addOutput(createOutputCentered<panel::PortOutMain>(panel::mm(panel::OUT_POS.x, panel::OUT_POS.y), module, TollModule::OUT_OUTPUT));
	}
};


Model* modelToll = createModel<TollModule, TollWidget>("Toll");
