// Generated by panelkit from tools/panels/ScheduleA.py. Do not edit; edit the spec.
//
// Everything the panel's C++ needs to agree with res/ScheduleA.svg: the millimetre
// grid, the widget positions and the whole silkscreen. Rack's nanosvg discards
// <text>, so labels cannot live in the SVG -- they are drawn at runtime from
// the table below, generated from the same spec that drew the artwork.
//
// Every declaration here is `static`, i.e. private to the translation unit, so
// the three panels in this plugin cannot collide. That also means no
// translation unit may include two of these.
#pragma once
#include "../PanelTheme.hpp"

namespace panel {

// --- identity --------------------------------------------------------------
static const int   HP = 16;
static const float W  = 81.2800f;  // mm
static const float H  = 128.5000f;  // mm

// --- panel metrics, mirrored from tools/panels/ScheduleA.py ---
static const int   NUM_SLOTS      = 8;

// --- silkscreen ------------------------------------------------------------
static const Label LABELS[] = {
	{ 11.5600f,   5.5000f, 10.50f, 1.50f, PAPER    , NVG_ALIGN_LEFT | NVG_ALIGN_BASELINE, false, "SCHEDULE A"},
	{ 69.7200f,   5.5000f,  6.00f, 0.00f, SAGE     , NVG_ALIGN_RIGHT | NVG_ALIGN_BASELINE, false, "ITEMIZED LIENS"},
	{ 11.5600f,   8.2500f,  7.40f, 0.00f, LIME     , NVG_ALIGN_LEFT | NVG_ALIGN_BASELINE, true,  "$"},
	{ 13.7637f,   8.0000f,  4.60f, 0.40f, SAGE     , NVG_ALIGN_LEFT | NVG_ALIGN_BASELINE, false, "MOON TECHNOLOGIES"},
	{ 77.0800f,   8.0000f,  4.60f, 0.40f, SAGE     , NVG_ALIGN_RIGHT | NVG_ALIGN_BASELINE, false, "FORM 1099-A"},
	{ 40.6400f,  14.0000f,  6.00f, 0.60f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "ITEMIZED"},
	{ 20.4760f,  17.5698f,  6.20f, 0.00f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "SPEED"},
	{ 33.1520f,  17.5698f,  6.20f, 0.00f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "GAIN"},
	{ 45.8280f,  17.5698f,  6.20f, 0.00f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "START"},
	{ 58.5040f,  17.5698f,  6.20f, 0.00f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "LENGTH"},
	{ 71.1800f,  17.5698f,  6.20f, 0.00f, MINT_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "OUT"},
};

/** Draws this panel's silkscreen. `static` so each module keeps its own,
    bound to its own table. */
static inline void addLabels(app::ModuleWidget* mw) {
	addLabels(mw, LABELS, sizeof(LABELS) / sizeof(LABELS[0]));
}

// --- widget positions, by the names used in tools/panels/ScheduleA.py -----
// Positions are mm; feed them to mm() or createParamCentered.
static const Vec STEP1_POS = Vec(7.8000, 23.7947);
static const Vec SPEED1_POS = Vec(20.4760, 23.7947);
static const Vec GAIN1_POS = Vec(33.1520, 23.7947);
static const Vec START1_POS = Vec(45.8280, 23.7947);
static const Vec LEN1_POS = Vec(58.5040, 23.7947);
static const Vec OUT1_POS = Vec(71.1800, 23.7947);
static const Vec STEP2_POS = Vec(7.8000, 36.5954);
static const Vec SPEED2_POS = Vec(20.4760, 36.5954);
static const Vec GAIN2_POS = Vec(33.1520, 36.5954);
static const Vec START2_POS = Vec(45.8280, 36.5954);
static const Vec LEN2_POS = Vec(58.5040, 36.5954);
static const Vec OUT2_POS = Vec(71.1800, 36.5954);
static const Vec STEP3_POS = Vec(7.8000, 49.3961);
static const Vec SPEED3_POS = Vec(20.4760, 49.3961);
static const Vec GAIN3_POS = Vec(33.1520, 49.3961);
static const Vec START3_POS = Vec(45.8280, 49.3961);
static const Vec LEN3_POS = Vec(58.5040, 49.3961);
static const Vec OUT3_POS = Vec(71.1800, 49.3961);
static const Vec STEP4_POS = Vec(7.8000, 62.1967);
static const Vec SPEED4_POS = Vec(20.4760, 62.1967);
static const Vec GAIN4_POS = Vec(33.1520, 62.1967);
static const Vec START4_POS = Vec(45.8280, 62.1967);
static const Vec LEN4_POS = Vec(58.5040, 62.1967);
static const Vec OUT4_POS = Vec(71.1800, 62.1967);
static const Vec STEP5_POS = Vec(7.8000, 74.9974);
static const Vec SPEED5_POS = Vec(20.4760, 74.9974);
static const Vec GAIN5_POS = Vec(33.1520, 74.9974);
static const Vec START5_POS = Vec(45.8280, 74.9974);
static const Vec LEN5_POS = Vec(58.5040, 74.9974);
static const Vec OUT5_POS = Vec(71.1800, 74.9974);
static const Vec STEP6_POS = Vec(7.8000, 87.7980);
static const Vec SPEED6_POS = Vec(20.4760, 87.7980);
static const Vec GAIN6_POS = Vec(33.1520, 87.7980);
static const Vec START6_POS = Vec(45.8280, 87.7980);
static const Vec LEN6_POS = Vec(58.5040, 87.7980);
static const Vec OUT6_POS = Vec(71.1800, 87.7980);
static const Vec STEP7_POS = Vec(7.8000, 100.5987);
static const Vec SPEED7_POS = Vec(20.4760, 100.5987);
static const Vec GAIN7_POS = Vec(33.1520, 100.5987);
static const Vec START7_POS = Vec(45.8280, 100.5987);
static const Vec LEN7_POS = Vec(58.5040, 100.5987);
static const Vec OUT7_POS = Vec(71.1800, 100.5987);
static const Vec STEP8_POS = Vec(7.8000, 113.3993);
static const Vec SPEED8_POS = Vec(20.4760, 113.3993);
static const Vec GAIN8_POS = Vec(33.1520, 113.3993);
static const Vec START8_POS = Vec(45.8280, 113.3993);
static const Vec LEN8_POS = Vec(58.5040, 113.3993);
static const Vec OUT8_POS = Vec(71.1800, 113.3993);

} // namespace panel
