// Generated by panelkit from tools/panels/Calculation.py. Do not edit; edit the spec.
//
// Everything the panel's C++ needs to agree with res/Calculation.svg: the millimetre
// grid, the widget positions and the whole silkscreen. Rack's nanosvg discards
// <text>, so labels cannot live in the SVG -- they are drawn at runtime from
// the table below, generated from the same spec that drew the artwork.
//
// Every declaration here is `static`, i.e. private to the translation unit, so
// the three panels in this plugin cannot collide. That also means no
// translation unit may include two of these.
#pragma once
#include "../PanelTheme.hpp"

namespace panel {

// --- identity --------------------------------------------------------------
static const int   HP = 9;
static const float W  = 45.7200f;  // mm
static const float H  = 128.5000f;  // mm
//: What the module is, as the masthead's second line says it.
static const char* const WHAT = "PHRASE COUNTER";

// --- the read-out well: the spec's numbers, not the widget's ---------------
// A display used to be positioned by hand in the module's C++, in the same
// millimetres the spec had already chosen -- two copies of one number, and
// they drifted. The widget takes them from here now.
static const float GLASS_X = 3.6000f;
static const float GLASS_Y = 9.8000f;
static const float GLASS_W = 38.5200f;
static const float GLASS_H = 24.4000f;

// --- controls on the glass: where each is drawn and where it is grabbed --
// One rectangle per Field in the spec, in panel mm. Place the widget with
// createField<Screen...>(FIELD_X, ...) -- or createMenuField for a "menu" --
// and draw the value in
// inGlass(FIELD_X), the same rectangle in the display's own pixels.
static const Rect FIELD_N = Rect(Vec(4.4000f, 10.6000f), Vec(21.3283f, 4.1600f));  // value: ScreenKnob
static const Rect FIELD_START_BTN = Rect(Vec(4.4000f, 15.2600f), Vec(11.9733f, 4.1600f));  // button: ScreenButton
static const Rect FIELD_STOP_BTN = Rect(Vec(16.8733f, 15.2600f), Vec(11.9733f, 4.1600f));  // button: ScreenButton
static const Rect FIELD_RESET_BTN = Rect(Vec(29.3467f, 15.2600f), Vec(11.9733f, 4.1600f));  // button: ScreenButton
static const Rect FIELD_MULT1 = Rect(Vec(4.4000f, 19.9200f), Vec(8.8550f, 4.1600f));  // select: ScreenSelect
static const Rect FIELD_MULT2 = Rect(Vec(4.4000f, 24.5800f), Vec(8.8550f, 4.1600f));  // select: ScreenSelect
static const Rect FIELD_MULT3 = Rect(Vec(4.4000f, 29.2400f), Vec(8.8550f, 4.1600f));  // select: ScreenSelect
static const Rect FIELD_MULT4 = Rect(Vec(23.1100f, 19.9200f), Vec(8.8550f, 4.1600f));  // select: ScreenSelect
static const Rect FIELD_MULT5 = Rect(Vec(23.1100f, 24.5800f), Vec(8.8550f, 4.1600f));  // select: ScreenSelect
static const Rect FIELD_MULT6 = Rect(Vec(23.1100f, 29.2400f), Vec(8.8550f, 4.1600f));  // select: ScreenSelect

/** A field's rectangle in the display's pixels, for a display placed on the glass. */
static inline Rect inGlass(const Rect& f) {
	return mmRect(f.pos.x - GLASS_X, f.pos.y - GLASS_Y, f.size.x, f.size.y);
}

// --- silkscreen ------------------------------------------------------------
static const Label LABELS[] = {
	{ 22.8600f,   5.5000f,  7.97f, 1.50f, PAPER    , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "CALCULATION"},
	{  1.4000f,   8.2500f,  7.40f, 0.00f, LIME     , NVG_ALIGN_LEFT | NVG_ALIGN_BASELINE, 1,     "$"},
	{ 22.8600f,   8.0000f,  5.40f, 0.40f, LIME     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "PHRASE COUNTER"},
	{  2.1717f,  30.9652f,  4.60f, 0.40f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 2,     "MOON TECHNOLOGIES"},
	{ 43.5483f,  35.2460f,  4.60f, 0.40f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 3,     "WORKSHEET"},
	{ 22.8600f,  37.7000f,  6.00f, 0.60f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "LINES"},
	{  7.8900f,  40.7618f,  6.20f, 0.00f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "CV"},
	{ 20.5400f,  40.7618f,  6.20f, 0.00f, MINT_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "TRIG"},
	{ 37.8300f,  40.7618f,  6.20f, 0.00f, MINT_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "GATE"},
	{ 32.2400f, 105.6877f,  6.20f, 0.00f, MINT_DARK, NVG_ALIGN_RIGHT | NVG_ALIGN_BASELINE, 0,     "RUN"},
	{  6.4900f, 113.4100f,  6.20f, 0.00f, SAGE     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "CLOCK"},
	{ 17.4033f, 113.4100f,  6.20f, 0.00f, SAGE     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "START"},
	{ 28.3167f, 113.4100f,  6.20f, 0.00f, SAGE     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "STOP"},
	{ 39.2300f, 113.4100f,  6.20f, 0.00f, SAGE     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "RESET"},
};

/** Draws this panel's silkscreen. `static` so each module keeps its own,
    bound to its own table. */
static inline void addLabels(app::ModuleWidget* mw) {
	addLabels(mw, LABELS, sizeof(LABELS) / sizeof(LABELS[0]));
}

// --- widget positions, by the names used in tools/panels/Calculation.py -----
// Positions are mm; feed them to mm() or createParamCentered.
static const Vec CV1_POS = Vec(7.8900, 45.9518);
static const Vec TRIG1_POS = Vec(20.5400, 45.9518);
static const Vec FIRE1_LED_POS = Vec(29.1850, 45.9518);
static const Vec GATE1_POS = Vec(37.8300, 45.9518);
static const Vec CV2_POS = Vec(7.8900, 55.7818);
static const Vec TRIG2_POS = Vec(20.5400, 55.7818);
static const Vec FIRE2_LED_POS = Vec(29.1850, 55.7818);
static const Vec GATE2_POS = Vec(37.8300, 55.7818);
static const Vec CV3_POS = Vec(7.8900, 65.6118);
static const Vec TRIG3_POS = Vec(20.5400, 65.6118);
static const Vec FIRE3_LED_POS = Vec(29.1850, 65.6118);
static const Vec GATE3_POS = Vec(37.8300, 65.6118);
static const Vec CV4_POS = Vec(7.8900, 75.4418);
static const Vec TRIG4_POS = Vec(20.5400, 75.4418);
static const Vec FIRE4_LED_POS = Vec(29.1850, 75.4418);
static const Vec GATE4_POS = Vec(37.8300, 75.4418);
static const Vec CV5_POS = Vec(7.8900, 85.2718);
static const Vec TRIG5_POS = Vec(20.5400, 85.2718);
static const Vec FIRE5_LED_POS = Vec(29.1850, 85.2718);
static const Vec GATE5_POS = Vec(37.8300, 85.2718);
static const Vec CV6_POS = Vec(7.8900, 95.1018);
static const Vec TRIG6_POS = Vec(20.5400, 95.1018);
static const Vec FIRE6_LED_POS = Vec(29.1850, 95.1018);
static const Vec GATE6_POS = Vec(37.8300, 95.1018);
static const Vec RUN_POS = Vec(37.8300, 104.9318);
static const Vec CLOCK_POS = Vec(6.4900, 118.6000);
static const Vec START_POS = Vec(17.4033, 118.6000);
static const Vec STOP_POS = Vec(28.3167, 118.6000);
static const Vec RESET_POS = Vec(39.2300, 118.6000);

} // namespace panel
