// Generated by panelkit from tools/panels/PaymentSchedule.py. Do not edit; edit the spec.
//
// Everything the panel's C++ needs to agree with res/PaymentSchedule.svg: the millimetre
// grid, the widget positions and the whole silkscreen. Rack's nanosvg discards
// <text>, so labels cannot live in the SVG -- they are drawn at runtime from
// the table below, generated from the same spec that drew the artwork.
//
// Every declaration here is `static`, i.e. private to the translation unit, so
// the three panels in this plugin cannot collide. That also means no
// translation unit may include two of these.
#pragma once
#include "../PanelTheme.hpp"

namespace panel {

// --- identity --------------------------------------------------------------
static const int   HP = 22;
static const float W  = 111.7600f;  // mm
static const float H  = 128.5000f;  // mm
//: What the module is, as the masthead's second line says it.
static const char* const WHAT = "8-STEP SEQUENCER";

// --- silkscreen ------------------------------------------------------------
static const Label LABELS[] = {
	{ 11.5600f,   5.5000f, 10.50f, 1.50f, PAPER    , NVG_ALIGN_LEFT | NVG_ALIGN_BASELINE, 0,     "PAYMENT SCHEDULE"},
	{100.2000f,   5.5000f,  6.00f, 0.00f, SAGE     , NVG_ALIGN_RIGHT | NVG_ALIGN_BASELINE, 0,     "INSTALMENT VOUCHER"},
	{  1.4000f,   8.2500f,  7.40f, 0.00f, LIME     , NVG_ALIGN_LEFT | NVG_ALIGN_BASELINE, 1,     "$"},
	{ 55.8800f,   8.0000f,  5.40f, 0.40f, LIME     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "8-STEP SEQUENCER"},
	{  2.1717f,  60.0500f,  4.60f, 0.40f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 2,     "MOON TECHNOLOGIES"},
	{109.5883f,  60.0500f,  4.60f, 0.40f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 3,     "FORM 1040-V"},
	{ 55.8800f,  13.3000f,  6.00f, 0.60f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "STEPS"},
	{ 55.8800f,  16.3618f,  6.20f, 0.00f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "CV IN"},
	{  9.1000f,  42.3892f,  7.00f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "1"},
	{ 22.4657f,  42.3892f,  7.00f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "2"},
	{ 35.8314f,  42.3892f,  7.00f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "3"},
	{ 49.1971f,  42.3892f,  7.00f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "4"},
	{ 62.5629f,  42.3892f,  7.00f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "5"},
	{ 75.9286f,  42.3892f,  7.00f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "6"},
	{ 89.2943f,  42.3892f,  7.00f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "7"},
	{102.6600f,  42.3892f,  7.00f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "8"},
	{ 55.8800f,  59.7821f,  6.20f, 0.00f, MINT_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "GATE OUT"},
	{ 55.8800f,  75.9527f,  6.00f, 0.60f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "OPERATIONS"},
	{  6.0290f,  90.6596f,  5.80f, 0.00f, LIME_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "UP"},
	{ 17.9665f,  90.6596f,  7.00f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "STEPS"},
	{ 31.0437f,  90.6596f,  6.20f, 0.00f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "DIR"},
	{ 42.6187f,  90.6596f,  6.20f, 0.00f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "DIR CV"},
	{ 57.9537f,  90.6596f,  7.00f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "SCALE"},
	{ 69.8187f,  90.6596f,  5.80f, 0.00f, LIME_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "DN"},
	{ 81.6837f,  90.6596f,  7.00f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "ROOT"},
	{ 94.7610f,  90.6596f,  6.20f, 0.00f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "QUANT"},
	{104.8110f,  90.6596f,  6.20f, 0.00f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "RANGE"},
	{ 11.9100f, 107.1095f,  7.00f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "ATTEN"},
	{ 27.6400f, 107.1095f,  7.00f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "GATE LEN"},
	{ 43.3700f, 107.1095f,  6.60f, 0.00f, LIME_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "TAP"},
	{ 56.9200f, 107.1095f,  6.20f, 0.00f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "TAP IN"},
	{ 70.4700f, 107.1095f,  6.60f, 0.00f, LIME_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "REC"},
	{ 84.0200f, 107.1095f,  6.60f, 0.00f, LIME_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "CLR"},
	{ 99.7500f, 107.1095f,  6.60f, 0.00f, LIME_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "RUN"},
	{  6.4900f, 113.4100f,  6.20f, 0.00f, SAGE     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "CLOCK"},
	{ 20.9025f, 113.4100f,  6.20f, 0.00f, SAGE     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "RESET"},
	{ 33.2547f, 113.4100f,  6.20f, 0.00f, SAGE     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "SWITCH IN"},
	{ 45.6069f, 113.4100f,  6.20f, 0.00f, SAGE     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "RUN"},
	{ 57.1398f, 113.4100f,  6.20f, 0.00f, SAGE     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "CYCLE"},
	{ 68.6727f, 113.4100f,  6.20f, 0.00f, MINT     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "CV OUT"},
	{ 80.2056f, 113.4100f,  6.20f, 0.00f, MINT     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "TRIG"},
	{ 91.7385f, 113.4100f,  6.20f, 0.00f, MINT     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "EOC"},
	{104.0907f, 113.4100f,  6.20f, 0.00f, MINT     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "LOOP GATE"},
};

/** Draws this panel's silkscreen. `static` so each module keeps its own,
    bound to its own table. */
static inline void addLabels(app::ModuleWidget* mw) {
	addLabels(mw, LABELS, sizeof(LABELS) / sizeof(LABELS[0]));
}

// --- widget positions, by the names used in tools/panels/PaymentSchedule.py -----
// Positions are mm; feed them to mm() or createParamCentered.
static const Vec B_IN1_POS = Vec(9.1000, 21.5518);
static const Vec B_IN2_POS = Vec(22.4657, 21.5518);
static const Vec B_IN3_POS = Vec(35.8314, 21.5518);
static const Vec B_IN4_POS = Vec(49.1971, 21.5518);
static const Vec B_IN5_POS = Vec(62.5629, 21.5518);
static const Vec B_IN6_POS = Vec(75.9286, 21.5518);
static const Vec B_IN7_POS = Vec(89.2943, 21.5518);
static const Vec B_IN8_POS = Vec(102.6600, 21.5518);
static const Vec STEP1_POS = Vec(9.1000, 34.2824);
static const Vec STEP2_POS = Vec(22.4657, 34.2824);
static const Vec STEP3_POS = Vec(35.8314, 34.2824);
static const Vec STEP4_POS = Vec(49.1971, 34.2824);
static const Vec STEP5_POS = Vec(62.5629, 34.2824);
static const Vec STEP6_POS = Vec(75.9286, 34.2824);
static const Vec STEP7_POS = Vec(89.2943, 34.2824);
static const Vec STEP8_POS = Vec(102.6600, 34.2824);
static const Vec GATE1_POS = Vec(9.1000, 51.2298);
static const Vec GATE2_POS = Vec(22.4657, 51.2298);
static const Vec GATE3_POS = Vec(35.8314, 51.2298);
static const Vec GATE4_POS = Vec(49.1971, 51.2298);
static const Vec GATE5_POS = Vec(62.5629, 51.2298);
static const Vec GATE6_POS = Vec(75.9286, 51.2298);
static const Vec GATE7_POS = Vec(89.2943, 51.2298);
static const Vec GATE8_POS = Vec(102.6600, 51.2298);
static const Vec B_OUT1_POS = Vec(9.1000, 64.9721);
static const Vec B_OUT2_POS = Vec(22.4657, 64.9721);
static const Vec B_OUT3_POS = Vec(35.8314, 64.9721);
static const Vec B_OUT4_POS = Vec(49.1971, 64.9721);
static const Vec B_OUT5_POS = Vec(62.5629, 64.9721);
static const Vec B_OUT6_POS = Vec(75.9286, 64.9721);
static const Vec B_OUT7_POS = Vec(89.2943, 64.9721);
static const Vec B_OUT8_POS = Vec(102.6600, 64.9721);
static const Vec UP_LIT_POS = Vec(6.0290, 82.5527);
static const Vec STEPS_POS = Vec(17.9665, 82.5527);
static const Vec DIR_POS = Vec(31.0437, 82.5527);
static const Vec DIR_CV_IN_POS = Vec(42.6187, 82.5527);
static const Vec SCALE_POS = Vec(57.9537, 82.5527);
static const Vec DN_LIT_POS = Vec(69.8187, 82.5527);
static const Vec ROOT_POS = Vec(81.6837, 82.5527);
static const Vec QUANT_POS = Vec(94.7610, 82.5527);
static const Vec CV_RANGE_POS = Vec(104.8110, 82.5527);
static const Vec ATTEN_POS = Vec(11.9100, 99.0001);
static const Vec GATE_LEN_POS = Vec(27.6400, 99.0001);
static const Vec TAP_POS = Vec(43.3700, 99.0001);
static const Vec TAP_GATE_IN_POS = Vec(56.9200, 99.0001);
static const Vec RECORD_POS = Vec(70.4700, 99.0001);
static const Vec CLEAR_POS = Vec(84.0200, 99.0001);
static const Vec RUN_POS = Vec(99.7500, 99.0001);
static const Vec CLOCK_IN_POS = Vec(6.4900, 118.6000);
static const Vec RESET_IN_POS = Vec(20.9025, 118.6000);
static const Vec A_IN_POS = Vec(33.2547, 118.6000);
static const Vec RUN_IN_POS = Vec(45.6069, 118.6000);
static const Vec CYCLE_IN_POS = Vec(57.1398, 118.6000);
static const Vec A_OUT_POS = Vec(68.6727, 118.6000);
static const Vec TRIG_OUT_POS = Vec(80.2056, 118.6000);
static const Vec EOC_OUT_POS = Vec(91.7385, 118.6000);
static const Vec LOOP_GATE_OUT_POS = Vec(104.0907, 118.6000);
static const Vec CLOCK_LIT_POS = Vec(11.5396, 113.0982);

} // namespace panel
