// Generated by panelkit from tools/panels/Kickback.py. Do not edit; edit the spec.
//
// Everything the panel's C++ needs to agree with res/Kickback.svg: the millimetre
// grid, the widget positions and the whole silkscreen. Rack's nanosvg discards
// <text>, so labels cannot live in the SVG -- they are drawn at runtime from
// the table below, generated from the same spec that drew the artwork.
//
// Every declaration here is `static`, i.e. private to the translation unit, so
// the three panels in this plugin cannot collide. That also means no
// translation unit may include two of these.
#pragma once
#include "../PanelTheme.hpp"

namespace panel {

// --- identity --------------------------------------------------------------
static const int   HP = 31;
static const float W  = 157.4800f;  // mm
static const float H  = 128.5000f;  // mm

// --- silkscreen ------------------------------------------------------------
static const Label LABELS[] = {
	{ 78.7400f,   5.5000f, 10.50f, 1.50f, PAPER    , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "KICKBACK"},
	{ 11.5600f,   8.2500f,  7.40f, 0.00f, LIME     , NVG_ALIGN_LEFT | NVG_ALIGN_BASELINE, true,  "$"},
	{ 13.7637f,   8.0000f,  4.60f, 0.40f, SAGE     , NVG_ALIGN_LEFT | NVG_ALIGN_BASELINE, false, "MOON TECHNOLOGIES"},
	{153.2800f,   8.0000f,  4.60f, 0.40f, SAGE     , NVG_ALIGN_RIGHT | NVG_ALIGN_BASELINE, false, "FORM 1099-NEC"},
	{ 65.8906f,  13.3000f,  6.00f, 0.60f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "NONEMPLOYEE COMPENSATION"},
	{ 11.8000f,  30.0293f,  6.60f, 0.00f, LIME_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "RUN"},
	{ 25.2706f,  30.0293f,  6.20f, 0.00f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "LEVEL"},
	{ 42.3506f,  17.5459f,  6.20f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "KICK"},
	{ 57.1009f,  17.5459f,  6.20f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "SNARE"},
	{ 72.4810f,  17.5459f,  6.20f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "HAT"},
	{ 86.6014f,  17.5459f,  6.20f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "TOM I"},
	{101.9816f,  17.5459f,  6.20f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "TOM II"},
	{117.9917f,  17.5459f,  6.20f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "TOM III"},
	{ 11.8000f,  49.2337f,  7.00f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "RATE"},
	{ 25.2706f,  49.2337f,  6.20f, 0.00f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "ACCENT"},
	{ 42.3506f,  49.2337f,  7.00f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "TUNE"},
	{ 57.1009f,  49.2337f,  7.00f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "TUNE"},
	{ 72.4810f,  49.2337f,  7.00f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "TONE"},
	{ 86.6014f,  49.2337f,  7.00f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "TUNE"},
	{101.9816f,  49.2337f,  7.00f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "TUNE"},
	{117.9917f,  49.2337f,  7.00f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "TUNE"},
	{ 11.8000f,  53.5429f,  6.20f, 0.00f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "CLK"},
	{ 25.2706f,  53.5429f,  6.20f, 0.00f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "RST"},
	{ 42.3506f,  66.6448f,  6.20f, 0.00f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "MODEL"},
	{ 57.1009f,  66.6448f,  6.20f, 0.00f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "MODE"},
	{ 72.4810f,  66.6448f,  6.20f, 0.00f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "RATTLE"},
	{ 86.6014f,  66.6448f,  6.20f, 0.00f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "STRIKE"},
	{101.9816f,  66.6448f,  6.20f, 0.00f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "STRIKE"},
	{117.9917f,  66.6448f,  6.20f, 0.00f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "STRIKE"},
	{ 11.8000f,  79.4940f,  6.20f, 0.00f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "DIV"},
	{ 25.2706f,  79.4940f,  6.20f, 0.00f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "FILL"},
	{ 80.1711f,  79.4940f,  6.20f, 0.00f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "DECAY"},
	{ 11.8000f,  92.3433f,  6.20f, 0.00f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "SWING"},
	{ 25.2706f,  92.3433f,  6.20f, 0.00f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "SEED"},
	{ 80.1711f,  92.3433f,  6.20f, 0.00f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "BEND"},
	{ 11.8000f, 106.1525f,  6.20f, 0.00f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "HUMAN"},
	{ 25.2706f, 106.1525f,  6.20f, 0.00f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "GATE"},
	{ 33.3606f, 106.1525f,  6.20f, 0.00f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "BURST"},
	{ 80.1711f, 106.1525f,  6.20f, 0.00f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "RATIO"},
	{142.4306f,  13.3000f,  6.00f, 0.60f, MINT     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "GATE"},
	{141.8000f,  19.4459f,  6.20f, 0.00f, MINT     , NVG_ALIGN_RIGHT | NVG_ALIGN_BASELINE, false, "KICK"},
	{141.8000f,  36.0404f,  6.20f, 0.00f, MINT     , NVG_ALIGN_RIGHT | NVG_ALIGN_BASELINE, false, "SNARE"},
	{141.8000f,  52.6349f,  6.20f, 0.00f, MINT     , NVG_ALIGN_RIGHT | NVG_ALIGN_BASELINE, false, "HAT"},
	{141.8000f,  69.2294f,  6.20f, 0.00f, MINT     , NVG_ALIGN_RIGHT | NVG_ALIGN_BASELINE, false, "TOM I"},
	{141.8000f,  85.8239f,  6.20f, 0.00f, MINT     , NVG_ALIGN_RIGHT | NVG_ALIGN_BASELINE, false, "TOM II"},
	{141.8000f, 102.4184f,  6.20f, 0.00f, MINT     , NVG_ALIGN_RIGHT | NVG_ALIGN_BASELINE, false, "TOM III"},
	{ 11.8000f, 113.4100f,  6.20f, 0.00f, MINT     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "CLK"},
	{ 25.2706f, 113.4100f,  6.20f, 0.00f, MINT     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "MIX"},
	{ 42.3506f, 113.4100f,  6.20f, 0.00f, MINT     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "OUT"},
	{ 57.1009f, 113.4100f,  6.20f, 0.00f, MINT     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "OUT"},
	{ 72.4810f, 113.4100f,  6.20f, 0.00f, MINT     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "OUT"},
	{ 86.6014f, 113.4100f,  6.20f, 0.00f, MINT     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "OUT"},
	{101.9816f, 113.4100f,  6.20f, 0.00f, MINT     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "OUT"},
	{117.9917f, 113.4100f,  6.20f, 0.00f, MINT     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "OUT"},
	{147.3900f, 113.4100f,  6.20f, 0.00f, SAGE     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "ACC"},
};

/** Draws this panel's silkscreen. `static` so each module keeps its own,
    bound to its own table. */
static inline void addLabels(app::ModuleWidget* mw) {
	addLabels(mw, LABELS, sizeof(LABELS) / sizeof(LABELS[0]));
}

// --- widget positions, by the names used in tools/panels/Kickback.py -----
// Positions are mm; feed them to mm() or createParamCentered.
static const Vec RUN_POS = Vec(11.8000, 23.2200);
static const Vec LEVEL_POS = Vec(25.2706, 23.2200);
static const Vec KICK_TRIG_POS = Vec(42.3506, 23.2200);
static const Vec SNARE_TRIG_POS = Vec(57.1009, 23.2200);
static const Vec HAT_TRIG_POS = Vec(72.4810, 23.2200);
static const Vec TOM1_TRIG_POS = Vec(86.6014, 23.2200);
static const Vec TOM2_TRIG_POS = Vec(101.9816, 23.2200);
static const Vec TOM3_TRIG_POS = Vec(117.9917, 23.2200);
static const Vec KICK_LED_POS = Vec(47.5103, 16.7900);
static const Vec SNARE_LED_POS = Vec(62.8905, 16.7900);
static const Vec HAT_LED_POS = Vec(77.0108, 16.7900);
static const Vec TOM1_LED_POS = Vec(92.3910, 16.7900);
static const Vec TOM2_LED_POS = Vec(108.4011, 16.7900);
static const Vec TOM3_LED_POS = Vec(125.0411, 16.7900);
static const Vec RATE_POS = Vec(11.8000, 39.8268);
static const Vec ACCENT_POS = Vec(25.2706, 39.8268);
static const Vec KICK_TUNE_POS = Vec(42.3506, 39.8268);
static const Vec SNARE_TUNE_POS = Vec(57.1009, 39.8268);
static const Vec HAT_TUNE_POS = Vec(72.4810, 39.8268);
static const Vec TOM1_TUNE_POS = Vec(86.6014, 39.8268);
static const Vec TOM2_TUNE_POS = Vec(101.9816, 39.8268);
static const Vec TOM3_TUNE_POS = Vec(117.9917, 39.8268);
static const Vec CLK_IN_POS = Vec(11.8000, 58.7329);
static const Vec RST_IN_POS = Vec(25.2706, 58.7329);
static const Vec KICK_MODEL_POS = Vec(42.3506, 58.7329);
static const Vec SNARE_MODE_POS = Vec(57.1009, 58.7329);
static const Vec HAT_RATTLE_POS = Vec(72.4810, 58.7329);
static const Vec TOM1_STRIKE_POS = Vec(86.6014, 58.7329);
static const Vec TOM2_STRIKE_POS = Vec(101.9816, 58.7329);
static const Vec TOM3_STRIKE_POS = Vec(117.9917, 58.7329);
static const Vec DIV_POS = Vec(11.8000, 73.3622);
static const Vec FILL_POS = Vec(25.2706, 73.3622);
static const Vec KICK_DECAY_POS = Vec(42.3506, 73.3622);
static const Vec SNARE_DECAY_POS = Vec(57.1009, 73.3622);
static const Vec HAT_DECAY_POS = Vec(72.4810, 73.3622);
static const Vec TOM1_DECAY_POS = Vec(86.6014, 73.3622);
static const Vec TOM2_DECAY_POS = Vec(101.9816, 73.3622);
static const Vec TOM3_DECAY_POS = Vec(117.9917, 73.3622);
static const Vec SWING_POS = Vec(11.8000, 86.2115);
static const Vec SEED_POS = Vec(25.2706, 86.2115);
static const Vec KICK_BEND_POS = Vec(42.3506, 86.2115);
static const Vec SNARE_BEND_POS = Vec(57.1009, 86.2115);
static const Vec HAT_BEND_POS = Vec(72.4810, 86.2115);
static const Vec TOM1_BEND_POS = Vec(86.6014, 86.2115);
static const Vec TOM2_BEND_POS = Vec(101.9816, 86.2115);
static const Vec TOM3_BEND_POS = Vec(117.9917, 86.2115);
static const Vec HUMAN_POS = Vec(11.8000, 99.5407);
static const Vec GATELEN_POS = Vec(25.2706, 99.5407);
static const Vec KICK_RATIO_POS = Vec(42.3506, 99.5407);
static const Vec SNARE_RATIO_POS = Vec(57.1009, 99.5407);
static const Vec HAT_RATIO_POS = Vec(72.4810, 99.5407);
static const Vec TOM1_RATIO_POS = Vec(86.6014, 99.5407);
static const Vec TOM2_RATIO_POS = Vec(101.9816, 99.5407);
static const Vec TOM3_RATIO_POS = Vec(117.9917, 99.5407);
static const Vec BURST_POS = Vec(33.3606, 99.5407);
static const Vec KICK_GATE_POS = Vec(147.3900, 18.6900);
static const Vec SNARE_GATE_POS = Vec(147.3900, 35.2845);
static const Vec HAT_GATE_POS = Vec(147.3900, 51.8790);
static const Vec TOM1_GATE_POS = Vec(147.3900, 68.4735);
static const Vec TOM2_GATE_POS = Vec(147.3900, 85.0680);
static const Vec TOM3_GATE_POS = Vec(147.3900, 101.6625);
static const Vec CLK_OUT_POS = Vec(11.8000, 118.6000);
static const Vec MIX_OUT_POS = Vec(25.2706, 118.6000);
static const Vec KICK_OUT_POS = Vec(42.3506, 118.6000);
static const Vec SNARE_OUT_POS = Vec(57.1009, 118.6000);
static const Vec HAT_OUT_POS = Vec(72.4810, 118.6000);
static const Vec TOM1_OUT_POS = Vec(86.6014, 118.6000);
static const Vec TOM2_OUT_POS = Vec(101.9816, 118.6000);
static const Vec TOM3_OUT_POS = Vec(117.9917, 118.6000);
static const Vec ACC_IN_POS = Vec(147.3900, 118.6000);

} // namespace panel
