// Generated by panelkit from tools/panels/Ledger.py. Do not edit; edit the spec.
//
// Everything the panel's C++ needs to agree with res/Ledger.svg: the millimetre
// grid, the widget positions and the whole silkscreen. Rack's nanosvg discards
// <text>, so labels cannot live in the SVG -- they are drawn at runtime from
// the table below, generated from the same spec that drew the artwork.
//
// Every declaration here is `static`, i.e. private to the translation unit, so
// the three panels in this plugin cannot collide. That also means no
// translation unit may include two of these.
#pragma once
#include "../PanelTheme.hpp"

namespace panel {

// --- identity --------------------------------------------------------------
static const int   HP = 68;
static const float W  = 345.4400f;  // mm
static const float H  = 128.5000f;  // mm

// --- the read-out well: the spec's numbers, not the widget's ---------------
// A display used to be positioned by hand in the module's C++, in the same
// millimetres the spec had already chosen -- two copies of one number, and
// they drifted. The widget takes them from here now.
static const float GLASS_X = 4.2000f;
static const float GLASS_Y = 9.8000f;
static const float GLASS_W = 337.0400f;
static const float GLASS_H = 52.9000f;

// --- silkscreen ------------------------------------------------------------
static const Label LABELS[] = {
	{ 11.5600f,   5.5000f, 10.50f, 1.50f, PAPER    , NVG_ALIGN_LEFT | NVG_ALIGN_BASELINE, false, "LEDGER"},
	{333.8800f,   5.5000f,  6.00f, 0.00f, SAGE     , NVG_ALIGN_RIGHT | NVG_ALIGN_BASELINE, false, "GENERAL LEDGER"},
	{ 11.5600f,   8.2500f,  7.40f, 0.00f, LIME     , NVG_ALIGN_LEFT | NVG_ALIGN_BASELINE, true,  "$"},
	{ 13.7637f,   8.0000f,  4.60f, 0.40f, SAGE     , NVG_ALIGN_LEFT | NVG_ALIGN_BASELINE, false, "MOON TECHNOLOGIES"},
	{341.2400f,   8.0000f,  4.60f, 0.40f, SAGE     , NVG_ALIGN_RIGHT | NVG_ALIGN_BASELINE, false, "SCHEDULE L"},
	{172.7200f,  66.2000f,  6.00f, 0.60f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "ENTRY · SHAPE · PITCH · GROWTH · BOOKS"},
	{ 17.2337f,  84.9069f,  7.00f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "CHANCE"},
	{ 34.6887f,  84.9069f,  7.00f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "NOTE ±"},
	{ 50.9637f,  84.9069f,  7.00f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "OCTAVE ±"},
	{ 75.8431f,  84.9069f,  7.00f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "LENG"},
	{ 92.1181f,  84.9069f,  7.00f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "RATE"},
	{108.3931f,  84.9069f,  7.00f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "DIRN"},
	{133.2725f,  84.9069f,  7.00f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "TRNS"},
	{149.5475f,  84.9069f,  7.00f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "SHFT"},
	{165.8225f,  84.9069f,  7.00f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "OCTA"},
	{190.7019f,  84.9069f,  7.00f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "EVOLVE"},
	{206.9769f,  84.9069f,  7.00f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "BREATHE"},
	{223.2519f,  84.9069f,  7.00f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "GATE"},
	{239.5269f,  84.9069f,  7.00f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "TIE"},
	{255.8019f,  84.9069f,  7.00f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "SLOP"},
	{280.6813f,  84.9069f,  7.00f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "SCALE"},
	{296.9563f,  84.9069f,  7.00f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "ROOT"},
	{313.2313f,  84.9069f,  7.00f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "WEIGHT"},
	{329.5063f,  84.9069f,  7.00f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "BPM"},
	{ 30.4223f, 108.1828f,  6.60f, 0.00f, LIME_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "1"},
	{ 43.6123f, 108.1828f,  6.60f, 0.00f, LIME_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "2"},
	{ 56.8023f, 108.1828f,  6.60f, 0.00f, LIME_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "3"},
	{ 69.9923f, 108.1828f,  6.60f, 0.00f, LIME_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "4"},
	{ 83.1823f, 108.1828f,  6.60f, 0.00f, LIME_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "5"},
	{ 96.3723f, 108.1828f,  6.60f, 0.00f, LIME_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "6"},
	{109.5623f, 108.1828f,  6.60f, 0.00f, LIME_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "7"},
	{122.7523f, 108.1828f,  6.60f, 0.00f, LIME_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "8"},
	{135.0523f, 108.1828f,  6.20f, 0.00f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "MUTE"},
	{149.9520f, 108.1828f,  6.20f, 0.00f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "SOLO"},
	{164.8516f, 108.1828f,  6.20f, 0.00f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "RESEED"},
	{181.0112f, 108.1828f,  6.20f, 0.00f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "RUN"},
	{195.2809f, 108.1828f,  6.20f, 0.00f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "FREEZE"},
	{211.4404f, 108.1828f,  6.20f, 0.00f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "RESET"},
	{223.1904f, 108.1828f,  6.20f, 0.00f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "TANK"},
	{238.0901f, 108.1828f,  6.20f, 0.00f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "ROLL"},
	{252.9898f, 108.1828f,  6.20f, 0.00f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "FX"},
	{266.6296f, 108.1828f,  6.20f, 0.00f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "SEQ"},
	{280.8994f, 108.1828f,  6.20f, 0.00f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "SONG"},
	{296.2585f, 108.1828f,  6.20f, 0.00f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "CAPTURE"},
	{313.0480f, 108.1828f,  6.20f, 0.00f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "REC"},
	{  7.2900f, 113.4100f,  6.20f, 0.00f, SAGE     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "CLOCK"},
	{ 18.1463f, 113.4100f,  6.20f, 0.00f, SAGE     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "RESET"},
	{ 29.0026f, 113.4100f,  6.20f, 0.00f, SAGE     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "RUN"},
	{ 39.8589f, 113.4100f,  6.20f, 0.00f, SAGE     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "RESEED"},
	{ 50.7152f, 113.4100f,  6.20f, 0.00f, SAGE     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "FREEZE"},
	{ 61.5715f, 113.4100f,  6.20f, 0.00f, SAGE     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "SEED"},
	{ 74.1515f, 113.4100f,  6.20f, 0.00f, SAGE     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "CV A"},
	{ 85.0078f, 113.4100f,  6.20f, 0.00f, SAGE     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "CV B"},
	{ 95.8641f, 113.4100f,  6.20f, 0.00f, SAGE     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "CV C"},
	{106.7204f, 113.4100f,  6.20f, 0.00f, SAGE     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "CV D"},
	{119.3004f, 113.4100f,  6.20f, 0.00f, MINT     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "PITCH 1"},
	{130.1567f, 113.4100f,  6.20f, 0.00f, MINT     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "GATE 1"},
	{141.0130f, 113.4100f,  6.20f, 0.00f, MINT     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "PITCH 2"},
	{151.8693f, 113.4100f,  6.20f, 0.00f, MINT     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "GATE 2"},
	{162.7256f, 113.4100f,  6.20f, 0.00f, MINT     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "PITCH 3"},
	{173.5819f, 113.4100f,  6.20f, 0.00f, MINT     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "GATE 3"},
	{184.4381f, 113.4100f,  6.20f, 0.00f, MINT     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "PITCH 4"},
	{195.2944f, 113.4100f,  6.20f, 0.00f, MINT     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "GATE 4"},
	{206.1507f, 113.4100f,  6.20f, 0.00f, MINT     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "PITCH 5"},
	{217.0070f, 113.4100f,  6.20f, 0.00f, MINT     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "GATE 5"},
	{227.8633f, 113.4100f,  6.20f, 0.00f, MINT     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "PITCH 6"},
	{238.7196f, 113.4100f,  6.20f, 0.00f, MINT     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "GATE 6"},
	{249.5759f, 113.4100f,  6.20f, 0.00f, MINT     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "PITCH 7"},
	{260.4322f, 113.4100f,  6.20f, 0.00f, MINT     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "GATE 7"},
	{271.2885f, 113.4100f,  6.20f, 0.00f, MINT     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "PITCH 8"},
	{282.1448f, 113.4100f,  6.20f, 0.00f, MINT     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "GATE 8"},
	{294.7248f, 113.4100f,  6.20f, 0.00f, MINT     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "VEL"},
	{305.5811f, 113.4100f,  6.20f, 0.00f, MINT     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "MOD"},
	{316.4374f, 113.4100f,  6.20f, 0.00f, MINT     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "CURRENT"},
	{327.2937f, 113.4100f,  6.20f, 0.00f, MINT     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "EOS"},
	{338.1500f, 113.4100f,  6.20f, 0.00f, MINT     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "CLOCK"},
};

/** Draws this panel's silkscreen. `static` so each module keeps its own,
    bound to its own table. */
static inline void addLabels(app::ModuleWidget* mw) {
	addLabels(mw, LABELS, sizeof(LABELS) / sizeof(LABELS[0]));
}

// --- widget positions, by the names used in tools/panels/Ledger.py -----
// Positions are mm; feed them to mm() or createParamCentered.
static const Vec CHANCE_POS = Vec(17.2337, 74.1000);
static const Vec NOTE_POS = Vec(34.6887, 74.1000);
static const Vec OCTAVE_POS = Vec(50.9637, 74.1000);
static const Vec LENG_POS = Vec(75.8431, 74.1000);
static const Vec RATE_POS = Vec(92.1181, 74.1000);
static const Vec DIRN_POS = Vec(108.3931, 74.1000);
static const Vec TRNS_POS = Vec(133.2725, 74.1000);
static const Vec SHFT_POS = Vec(149.5475, 74.1000);
static const Vec OCTA_POS = Vec(165.8225, 74.1000);
static const Vec EVOLVE_POS = Vec(190.7019, 74.1000);
static const Vec BREATHE_POS = Vec(206.9769, 74.1000);
static const Vec GATE_POS = Vec(223.2519, 74.1000);
static const Vec TIE_POS = Vec(239.5269, 74.1000);
static const Vec SLOP_POS = Vec(255.8019, 74.1000);
static const Vec SCALE_POS = Vec(280.6813, 74.1000);
static const Vec ROOT_POS = Vec(296.9563, 74.1000);
static const Vec WEIGHT_POS = Vec(313.2313, 74.1000);
static const Vec BPM_POS = Vec(329.5063, 74.1000);
static const Vec CHANCE_CV_POS = Vec(17.2337, 91.4969);
static const Vec NOTE_CV_POS = Vec(34.6887, 91.4969);
static const Vec OCTAVE_CV_POS = Vec(50.9637, 91.4969);
static const Vec LENG_CV_POS = Vec(75.8431, 91.4969);
static const Vec RATE_CV_POS = Vec(92.1181, 91.4969);
static const Vec DIRN_CV_POS = Vec(108.3931, 91.4969);
static const Vec TRNS_CV_POS = Vec(133.2725, 91.4969);
static const Vec SHFT_CV_POS = Vec(149.5475, 91.4969);
static const Vec OCTA_CV_POS = Vec(165.8225, 91.4969);
static const Vec EVOLVE_CV_POS = Vec(190.7019, 91.4969);
static const Vec BREATHE_CV_POS = Vec(206.9769, 91.4969);
static const Vec GATE_CV_POS = Vec(223.2519, 91.4969);
static const Vec TIE_CV_POS = Vec(239.5269, 91.4969);
static const Vec SLOP_CV_POS = Vec(255.8019, 91.4969);
static const Vec SCALE_CV_POS = Vec(280.6813, 91.4969);
static const Vec ROOT_CV_POS = Vec(296.9563, 91.4969);
static const Vec WEIGHT_CV_POS = Vec(313.2313, 91.4969);
static const Vec TRK1_POS = Vec(30.4223, 101.3369);
static const Vec TRK2_POS = Vec(43.6123, 101.3369);
static const Vec TRK3_POS = Vec(56.8023, 101.3369);
static const Vec TRK4_POS = Vec(69.9923, 101.3369);
static const Vec TRK5_POS = Vec(83.1823, 101.3369);
static const Vec TRK6_POS = Vec(96.3723, 101.3369);
static const Vec TRK7_POS = Vec(109.5623, 101.3369);
static const Vec TRK8_POS = Vec(122.7523, 101.3369);
static const Vec MUTE_POS = Vec(135.0523, 101.3369);
static const Vec SOLO_POS = Vec(149.9520, 101.3369);
static const Vec RSED_POS = Vec(164.8516, 101.3369);
static const Vec RUN_POS = Vec(181.0112, 101.3369);
static const Vec FRZE_POS = Vec(195.2809, 101.3369);
static const Vec RSET_POS = Vec(211.4404, 101.3369);
static const Vec PG_TANK_POS = Vec(223.1904, 101.3369);
static const Vec PG_ROLL_POS = Vec(238.0901, 101.3369);
static const Vec PG_FX_POS = Vec(252.9898, 101.3369);
static const Vec PG_SEQ_POS = Vec(266.6296, 101.3369);
static const Vec PG_SONG_POS = Vec(280.8994, 101.3369);
static const Vec CAPT_POS = Vec(296.2585, 101.3369);
static const Vec REC_POS = Vec(313.0480, 101.3369);
static const Vec MUTE_LED_POS = Vec(140.2120, 107.4269);
static const Vec SOLO_LED_POS = Vec(155.1116, 107.4269);
static const Vec RSED_LED_POS = Vec(171.2712, 107.4269);
static const Vec RUN_LED_POS = Vec(185.5409, 107.4269);
static const Vec FRZE_LED_POS = Vec(201.7004, 107.4269);
static const Vec PG_TANK_LED_POS = Vec(228.3501, 107.4269);
static const Vec PG_ROLL_LED_POS = Vec(243.2498, 107.4269);
static const Vec PG_FX_LED_POS = Vec(256.8896, 107.4269);
static const Vec PG_SEQ_LED_POS = Vec(271.1594, 107.4269);
static const Vec PG_SONG_LED_POS = Vec(286.0591, 107.4269);
static const Vec CAPT_LED_POS = Vec(303.3080, 107.4269);
static const Vec REC_LED_POS = Vec(317.5777, 107.4269);
static const Vec CLK_IN_POS = Vec(7.2900, 118.6000);
static const Vec RST_IN_POS = Vec(18.1463, 118.6000);
static const Vec RUN_IN_POS = Vec(29.0026, 118.6000);
static const Vec RESEED_IN_POS = Vec(39.8589, 118.6000);
static const Vec FREEZE_IN_POS = Vec(50.7152, 118.6000);
static const Vec SEED_IN_POS = Vec(61.5715, 118.6000);
static const Vec CV_A_POS = Vec(74.1515, 118.6000);
static const Vec CV_B_POS = Vec(85.0078, 118.6000);
static const Vec CV_C_POS = Vec(95.8641, 118.6000);
static const Vec CV_D_POS = Vec(106.7204, 118.6000);
static const Vec PITCH1_POS = Vec(119.3004, 118.6000);
static const Vec GATE1_POS = Vec(130.1567, 118.6000);
static const Vec PITCH2_POS = Vec(141.0130, 118.6000);
static const Vec GATE2_POS = Vec(151.8693, 118.6000);
static const Vec PITCH3_POS = Vec(162.7256, 118.6000);
static const Vec GATE3_POS = Vec(173.5819, 118.6000);
static const Vec PITCH4_POS = Vec(184.4381, 118.6000);
static const Vec GATE4_POS = Vec(195.2944, 118.6000);
static const Vec PITCH5_POS = Vec(206.1507, 118.6000);
static const Vec GATE5_POS = Vec(217.0070, 118.6000);
static const Vec PITCH6_POS = Vec(227.8633, 118.6000);
static const Vec GATE6_POS = Vec(238.7196, 118.6000);
static const Vec PITCH7_POS = Vec(249.5759, 118.6000);
static const Vec GATE7_POS = Vec(260.4322, 118.6000);
static const Vec PITCH8_POS = Vec(271.2885, 118.6000);
static const Vec GATE8_POS = Vec(282.1448, 118.6000);
static const Vec VEL_POS = Vec(294.7248, 118.6000);
static const Vec MOD_POS = Vec(305.5811, 118.6000);
static const Vec CURRENT_POS = Vec(316.4374, 118.6000);
static const Vec EOS_POS = Vec(327.2937, 118.6000);
static const Vec CLK_OUT_POS = Vec(338.1500, 118.6000);

} // namespace panel
