// Generated by panelkit from tools/panels/Installment.py. Do not edit; edit the spec.
//
// Everything the panel's C++ needs to agree with res/Installment.svg: the millimetre
// grid, the widget positions and the whole silkscreen. Rack's nanosvg discards
// <text>, so labels cannot live in the SVG -- they are drawn at runtime from
// the table below, generated from the same spec that drew the artwork.
//
// Every declaration here is `static`, i.e. private to the translation unit, so
// the three panels in this plugin cannot collide. That also means no
// translation unit may include two of these.
#pragma once
#include "../PanelTheme.hpp"

namespace panel {

// --- identity --------------------------------------------------------------
static const int   HP = 16;
static const float W  = 81.2800f;  // mm
static const float H  = 128.5000f;  // mm

// --- silkscreen ------------------------------------------------------------
static const Label LABELS[] = {
	{ 40.6400f,   5.5000f, 10.50f, 1.50f, PAPER    , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "INSTALLMENT"},
	{ 11.5600f,   8.2500f,  7.40f, 0.00f, LIME     , NVG_ALIGN_LEFT | NVG_ALIGN_BASELINE, true,  "$"},
	{ 13.7637f,   8.0000f,  4.60f, 0.40f, SAGE     , NVG_ALIGN_LEFT | NVG_ALIGN_BASELINE, false, "MOON TECHNOLOGIES"},
	{ 77.0800f,   8.0000f,  4.60f, 0.40f, SAGE     , NVG_ALIGN_RIGHT | NVG_ALIGN_BASELINE, false, "FORM 9465"},
	{ 40.6400f,  13.7000f,  6.00f, 0.60f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "PAYMENT PLAN"},
	{  8.0000f,  27.0000f,  6.20f, 0.00f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "MODE"},
	{ 29.7600f,  27.0000f,  6.60f, 0.00f, LIME_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "LOOP"},
	{ 51.5200f,  27.0000f,  6.20f, 0.00f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "MODE"},
	{ 73.2800f,  27.0000f,  6.60f, 0.00f, LIME_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "LOOP"},
	{  8.0000f,  41.0588f,  7.00f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "ATTACK"},
	{ 29.7600f,  41.0588f,  7.00f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "RELEASE"},
	{ 51.5200f,  41.0588f,  7.00f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "ATTACK"},
	{ 73.2800f,  41.0588f,  7.00f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "RELEASE"},
	{  8.0000f,  54.5515f,  6.20f, 0.00f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "RANGE"},
	{ 29.7600f,  54.5515f,  7.00f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "BIAS"},
	{ 51.5200f,  54.5515f,  6.20f, 0.00f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "RANGE"},
	{ 73.2800f,  54.5515f,  7.00f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "BIAS"},
	{ 40.6400f,  62.2441f,  6.00f, 0.60f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "AUTOPAY"},
	{ 18.8800f,  65.2559f,  6.20f, 0.00f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "CV AMT"},
	{ 62.4000f,  65.2559f,  6.20f, 0.00f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "CV AMT"},
	{ 18.8800f,  85.8055f,  6.20f, 0.00f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "GATE"},
	{ 31.6400f,  98.5404f,  7.00f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "DUTY"},
	{ 49.6400f,  85.8055f,  6.20f, 0.00f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "CV"},
	{ 62.4000f,  85.8055f,  6.20f, 0.00f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "GATE"},
	{  6.0000f, 112.8651f,  6.20f, 0.00f, MINT     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "ENV1"},
	{ 17.5467f, 112.8651f,  6.20f, 0.00f, MINT     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "SQU1"},
	{ 29.0933f, 112.8651f,  6.20f, 0.00f, MINT     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "EOC1"},
	{ 40.6400f, 112.8651f,  6.20f, 0.00f, MINT     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "ENV2"},
	{ 52.1867f, 112.8651f,  6.20f, 0.00f, MINT     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "SQU2"},
	{ 63.7333f, 112.8651f,  6.20f, 0.00f, MINT     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "EOC2"},
	{ 75.2800f, 112.8651f,  6.20f, 0.00f, MINT     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "PWM"},
};

/** Draws this panel's silkscreen. `static` so each module keeps its own,
    bound to its own table. */
static inline void addLabels(app::ModuleWidget* mw) {
	addLabels(mw, LABELS, sizeof(LABELS) / sizeof(LABELS[0]));
}

// --- widget positions, by the names used in tools/panels/Installment.py -----
// Positions are mm; feed them to mm() or createParamCentered.
static const Vec MODE1_POS = Vec(8.0000, 20.0000);
static const Vec LOOP1_POS = Vec(29.7600, 20.0000);
static const Vec MODE2_POS = Vec(51.5200, 20.0000);
static const Vec LOOP2_POS = Vec(73.2800, 20.0000);
static const Vec ATTACK1_POS = Vec(8.0000, 34.0588);
static const Vec RELEASE1_POS = Vec(29.7600, 34.0588);
static const Vec ATTACK2_POS = Vec(51.5200, 34.0588);
static const Vec RELEASE2_POS = Vec(73.2800, 34.0588);
static const Vec RANGE1_POS = Vec(8.0000, 47.5515);
static const Vec BIAS1_POS = Vec(29.7600, 47.5515);
static const Vec RANGE2_POS = Vec(51.5200, 47.5515);
static const Vec BIAS2_POS = Vec(73.2800, 47.5515);
static const Vec CV1_AMT_POS = Vec(18.8800, 70.0009);
static const Vec CV2_AMT_POS = Vec(62.4000, 70.0009);
static const Vec CV1_IN_POS = Vec(18.8800, 78.1309);
static const Vec CV2_IN_POS = Vec(62.4000, 78.1309);
static const Vec GATE1_IN_POS = Vec(18.8800, 91.5404);
static const Vec PWM_DUTY_POS = Vec(31.6400, 91.5404);
static const Vec PWM_CV_IN_POS = Vec(49.6400, 91.5404);
static const Vec GATE2_IN_POS = Vec(62.4000, 91.5404);
static const Vec ENV1_OUT_POS = Vec(6.0000, 118.6000);
static const Vec INV1_OUT_POS = Vec(17.5467, 118.6000);
static const Vec EOC1_OUT_POS = Vec(29.0933, 118.6000);
static const Vec ENV2_OUT_POS = Vec(40.6400, 118.6000);
static const Vec INV2_OUT_POS = Vec(52.1867, 118.6000);
static const Vec EOC2_OUT_POS = Vec(63.7333, 118.6000);
static const Vec PWM_OUT_POS = Vec(75.2800, 118.6000);

} // namespace panel
