// Generated by panelkit from tools/panels/Installment.py. Do not edit; edit the spec.
//
// Everything the panel's C++ needs to agree with res/Installment.svg: the millimetre
// grid, the widget positions and the whole silkscreen. Rack's nanosvg discards
// <text>, so labels cannot live in the SVG -- they are drawn at runtime from
// the table below, generated from the same spec that drew the artwork.
//
// Every declaration here is `static`, i.e. private to the translation unit, so
// the three panels in this plugin cannot collide. That also means no
// translation unit may include two of these.
#pragma once
#include "../PanelTheme.hpp"

namespace panel {

// --- identity --------------------------------------------------------------
static const int   HP = 16;
static const float W  = 81.2800f;  // mm
static const float H  = 128.5000f;  // mm

// --- silkscreen ------------------------------------------------------------
static const Label LABELS[] = {
	{ 40.6400f,   5.5000f, 10.50f, 1.50f, PAPER    , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "INSTALLMENT"},
	{ 11.5600f,   8.2500f,  7.40f, 0.00f, LIME     , NVG_ALIGN_LEFT | NVG_ALIGN_BASELINE, true,  "$"},
	{ 13.7637f,   8.0000f,  4.60f, 0.40f, SAGE     , NVG_ALIGN_LEFT | NVG_ALIGN_BASELINE, false, "MOON TECHNOLOGIES"},
	{ 77.0800f,   8.0000f,  4.60f, 0.40f, SAGE     , NVG_ALIGN_RIGHT | NVG_ALIGN_BASELINE, false, "FORM 9465"},
	{ 40.6400f,  13.3000f,  6.00f, 0.60f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "PAYMENT PLAN"},
	{ 16.2275f,  27.8118f,  6.20f, 0.00f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "MODE"},
	{ 32.5025f,  27.8118f,  6.60f, 0.00f, LIME_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "LOOP"},
	{ 48.7775f,  27.8118f,  6.20f, 0.00f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "MODE"},
	{ 65.0525f,  27.8118f,  6.60f, 0.00f, LIME_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "LOOP"},
	{ 16.2275f,  45.0949f,  7.00f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "ATTACK"},
	{ 32.5025f,  45.0949f,  7.00f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "RELEASE"},
	{ 48.7775f,  45.0949f,  7.00f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "ATTACK"},
	{ 65.0525f,  45.0949f,  7.00f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "RELEASE"},
	{ 16.2275f,  60.5780f,  6.20f, 0.00f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "RANGE"},
	{ 32.5025f,  60.5780f,  7.00f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "BIAS"},
	{ 48.7775f,  60.5780f,  6.20f, 0.00f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "RANGE"},
	{ 65.0525f,  60.5780f,  7.00f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "BIAS"},
	{ 40.6400f,  66.2042f,  6.00f, 0.60f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "AUTOPAY"},
	{ 14.6550f,  78.5560f,  6.20f, 0.00f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "CV AMT"},
	{ 27.0425f,  78.5560f,  6.20f, 0.00f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "CURVE"},
	{ 40.6400f,  78.5560f,  6.20f, 0.00f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "PWM CV"},
	{ 54.2375f,  78.5560f,  6.20f, 0.00f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "CURVE"},
	{ 66.6250f,  78.5560f,  6.20f, 0.00f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "CV AMT"},
	{ 14.6550f,  92.8240f,  6.20f, 0.00f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "GATE"},
	{ 40.6400f, 106.1209f,  7.00f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "DUTY"},
	{ 66.6250f,  92.8240f,  6.20f, 0.00f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "GATE"},
	{  7.2900f, 112.8851f,  6.20f, 0.00f, MINT     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "ENV1"},
	{ 18.4067f, 112.8851f,  6.20f, 0.00f, MINT     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "SQU1"},
	{ 29.5233f, 112.8851f,  6.20f, 0.00f, MINT     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "EOC1"},
	{ 40.6400f, 112.8851f,  6.20f, 0.00f, MINT     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "ENV2"},
	{ 51.7567f, 112.8851f,  6.20f, 0.00f, MINT     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "SQU2"},
	{ 62.8733f, 112.8851f,  6.20f, 0.00f, MINT     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "EOC2"},
	{ 73.9900f, 112.8851f,  6.20f, 0.00f, MINT     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "PWM"},
};

/** Draws this panel's silkscreen. `static` so each module keeps its own,
    bound to its own table. */
static inline void addLabels(app::ModuleWidget* mw) {
	addLabels(mw, LABELS, sizeof(LABELS) / sizeof(LABELS[0]));
}

// --- widget positions, by the names used in tools/panels/Installment.py -----
// Positions are mm; feed them to mm() or createParamCentered.
static const Vec MODE1_POS = Vec(16.2275, 19.9000);
static const Vec LOOP1_POS = Vec(32.5025, 19.9000);
static const Vec MODE2_POS = Vec(48.7775, 19.9000);
static const Vec LOOP2_POS = Vec(65.0525, 19.9000);
static const Vec ATTACK1_POS = Vec(16.2275, 36.9880);
static const Vec RELEASE1_POS = Vec(32.5025, 36.9880);
static const Vec ATTACK2_POS = Vec(48.7775, 36.9880);
static const Vec RELEASE2_POS = Vec(65.0525, 36.9880);
static const Vec RANGE1_POS = Vec(16.2275, 52.4711);
static const Vec BIAS1_POS = Vec(32.5025, 52.4711);
static const Vec RANGE2_POS = Vec(48.7775, 52.4711);
static const Vec BIAS2_POS = Vec(65.0525, 52.4711);
static const Vec CV1_AMT_POS = Vec(14.6550, 71.0242);
static const Vec CURVE1_POS = Vec(27.0425, 71.0242);
static const Vec PWM_CV_AMT_POS = Vec(40.6400, 71.0242);
static const Vec CURVE2_POS = Vec(54.2375, 71.0242);
static const Vec CV2_AMT_POS = Vec(66.6250, 71.0242);
static const Vec CV1_IN_POS = Vec(14.6550, 85.1460);
static const Vec PWM_CV_IN_POS = Vec(40.6400, 85.1460);
static const Vec CV2_IN_POS = Vec(66.6250, 85.1460);
static const Vec GATE1_IN_POS = Vec(14.6550, 98.0140);
static const Vec PWM_DUTY_POS = Vec(40.6400, 98.0140);
static const Vec GATE2_IN_POS = Vec(66.6250, 98.0140);
static const Vec ENV1_OUT_POS = Vec(7.2900, 118.6000);
static const Vec INV1_OUT_POS = Vec(18.4067, 118.6000);
static const Vec EOC1_OUT_POS = Vec(29.5233, 118.6000);
static const Vec ENV2_OUT_POS = Vec(40.6400, 118.6000);
static const Vec INV2_OUT_POS = Vec(51.7567, 118.6000);
static const Vec EOC2_OUT_POS = Vec(62.8733, 118.6000);
static const Vec PWM_OUT_POS = Vec(73.9900, 118.6000);

} // namespace panel
