// Generated by panelkit from tools/panels/Consolidation.py. Do not edit; edit the spec.
//
// Everything the panel's C++ needs to agree with res/Consolidation.svg: the millimetre
// grid, the widget positions and the whole silkscreen. Rack's nanosvg discards
// <text>, so labels cannot live in the SVG -- they are drawn at runtime from
// the table below, generated from the same spec that drew the artwork.
//
// Every declaration here is `static`, i.e. private to the translation unit, so
// the three panels in this plugin cannot collide. That also means no
// translation unit may include two of these.
#pragma once
#include "../PanelTheme.hpp"

namespace panel {

// --- identity --------------------------------------------------------------
static const int   HP = 14;
static const float W  = 71.1200f;  // mm
static const float H  = 128.5000f;  // mm
//: What the module is, as the masthead's second line says it.
static const char* const WHAT = "MIXER & MULTIPLES";

// --- silkscreen ------------------------------------------------------------
static const Label LABELS[] = {
	{ 35.5600f,   5.5000f, 10.50f, 1.50f, PAPER    , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "CONSOLIDATION"},
	{  1.4000f,   8.2500f,  7.40f, 0.00f, LIME     , NVG_ALIGN_LEFT | NVG_ALIGN_BASELINE, 1,     "$"},
	{ 35.5600f,   8.0000f,  5.40f, 0.40f, LIME     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "MIXER & MULTIPLES"},
	{  2.1717f,  60.0491f,  4.60f, 0.40f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 2,     "MOON TECHNOLOGIES"},
	{ 68.9483f,  60.0491f,  4.60f, 0.40f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 3,     "FORM 1040"},
	{ 35.5600f,  14.0000f,  6.00f, 0.60f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "MIXER"},
	{  9.4300f,  29.3069f,  7.00f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "LVL 1"},
	{ 26.8500f,  29.3069f,  7.00f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "LVL 2"},
	{ 44.2700f,  29.3069f,  7.00f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "LVL 3"},
	{ 61.6900f,  29.3069f,  7.00f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "LVL 4"},
	{ 35.5600f,  42.1291f,  6.20f, 0.00f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "MUTE"},
	{ 35.5600f,  46.2513f,  6.20f, 0.00f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "LEVEL CV"},
	{  9.4300f,  60.1534f,  6.20f, 0.00f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "IN 1"},
	{ 26.8500f,  60.1534f,  6.20f, 0.00f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "IN 2"},
	{ 44.2700f,  60.1534f,  6.20f, 0.00f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "IN 3"},
	{ 61.6900f,  60.1534f,  6.20f, 0.00f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "IN 4"},
	{ 35.5600f,  78.7438f,  6.00f, 0.60f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "MULTIPLES"},
	{ 14.1490f,  81.8056f,  6.20f, 0.00f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "MULT A"},
	{ 14.1490f,  95.7078f,  6.20f, 0.00f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "MULT B"},
	{  6.4900f, 113.3100f,  6.20f, 0.00f, MINT     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "1"},
	{ 18.1180f, 113.3100f,  6.20f, 0.00f, MINT     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "2"},
	{ 29.7460f, 113.3100f,  6.20f, 0.00f, MINT     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "3"},
	{ 41.3740f, 113.3100f,  6.20f, 0.00f, MINT     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "4"},
	{ 53.0020f, 113.3100f,  6.20f, 0.00f, MINT     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "MIX"},
	{ 64.6300f, 113.3100f,  6.20f, 0.00f, MINT     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "INV"},
};

/** Draws this panel's silkscreen. `static` so each module keeps its own,
    bound to its own table. */
static inline void addLabels(app::ModuleWidget* mw) {
	addLabels(mw, LABELS, sizeof(LABELS) / sizeof(LABELS[0]));
}

// --- widget positions, by the names used in tools/panels/Consolidation.py -----
// Positions are mm; feed them to mm() or createParamCentered.
static const Vec LVL1_POS = Vec(9.4300, 21.1000);
static const Vec LVL2_POS = Vec(26.8500, 21.1000);
static const Vec LVL3_POS = Vec(44.2700, 21.1000);
static const Vec LVL4_POS = Vec(61.6900, 21.1000);
static const Vec MUTE1_POS = Vec(9.4300, 35.8673);
static const Vec MUTE2_POS = Vec(26.8500, 35.8673);
static const Vec MUTE3_POS = Vec(44.2700, 35.8673);
static const Vec MUTE4_POS = Vec(61.6900, 35.8673);
static const Vec CV1_POS = Vec(9.4300, 51.5413);
static const Vec CV2_POS = Vec(26.8500, 51.5413);
static const Vec CV3_POS = Vec(44.2700, 51.5413);
static const Vec CV4_POS = Vec(61.6900, 51.5413);
static const Vec IN1_POS = Vec(9.4300, 65.4434);
static const Vec IN2_POS = Vec(26.8500, 65.4434);
static const Vec IN3_POS = Vec(44.2700, 65.4434);
static const Vec IN4_POS = Vec(61.6900, 65.4434);
static const Vec MULT_A_IN_POS = Vec(14.1490, 87.0956);
static const Vec MULT_A_OUT1_POS = Vec(28.4230, 87.0956);
static const Vec MULT_A_OUT2_POS = Vec(42.6970, 87.0956);
static const Vec MULT_A_OUT3_POS = Vec(56.9710, 87.0956);
static const Vec MULT_B_IN_POS = Vec(14.1490, 100.9978);
static const Vec MULT_B_OUT1_POS = Vec(28.4230, 100.9978);
static const Vec MULT_B_OUT2_POS = Vec(42.6970, 100.9978);
static const Vec MULT_B_OUT3_POS = Vec(56.9710, 100.9978);
static const Vec OUT1_POS = Vec(6.4900, 118.6000);
static const Vec OUT2_POS = Vec(18.1180, 118.6000);
static const Vec OUT3_POS = Vec(29.7460, 118.6000);
static const Vec OUT4_POS = Vec(41.3740, 118.6000);
static const Vec OUT_POS = Vec(53.0020, 118.6000);
static const Vec INV_OUT_POS = Vec(64.6300, 118.6000);

} // namespace panel
