// Generated by panelkit from tools/panels/Rebate.py. Do not edit; edit the spec.
//
// Everything the panel's C++ needs to agree with res/Rebate.svg: the millimetre
// grid, the widget positions and the whole silkscreen. Rack's nanosvg discards
// <text>, so labels cannot live in the SVG -- they are drawn at runtime from
// the table below, generated from the same spec that drew the artwork.
//
// Every declaration here is `static`, i.e. private to the translation unit, so
// the three panels in this plugin cannot collide. That also means no
// translation unit may include two of these.
#pragma once
#include "../PanelTheme.hpp"

namespace panel {

// --- identity --------------------------------------------------------------
static const int   HP = 10;
static const float W  = 50.8000f;  // mm
static const float H  = 128.5000f;  // mm
//: What the module is, as the masthead's second line says it.
static const char* const WHAT = "MIDIVERB DIGITAL REVERB";

// --- the read-out well: the spec's numbers, not the widget's ---------------
// A display used to be positioned by hand in the module's C++, in the same
// millimetres the spec had already chosen -- two copies of one number, and
// they drifted. The widget takes them from here now.
static const float GLASS_X = 3.6000f;
static const float GLASS_Y = 9.8000f;
static const float GLASS_W = 43.6000f;
static const float GLASS_H = 26.0000f;

// --- controls on the glass: where each is drawn and where it is grabbed --
// One rectangle per Field in the spec, in panel mm. Place the widget with
// createField<Screen...>(FIELD_X, ...) -- or createMenuField for a "menu" --
// and draw the value in
// inGlass(FIELD_X), the same rectangle in the display's own pixels.
static const Rect FIELD_CHANNEL = Rect(Vec(4.4000f, 10.6000f), Vec(6.5833f, 19.4200f));  // select: ScreenSelect
static const Rect FIELD_UP = Rect(Vec(11.4833f, 10.6000f), Vec(27.8333f, 9.4600f));  // button: ScreenButton
static const Rect FIELD_DOWN = Rect(Vec(11.4833f, 20.5600f), Vec(27.8333f, 9.4600f));  // button: ScreenButton
static const Rect FIELD_DEFEAT = Rect(Vec(39.8167f, 10.6000f), Vec(6.5833f, 19.4200f));  // button: ScreenButton

/** A field's rectangle in the display's pixels, for a display placed on the glass. */
static inline Rect inGlass(const Rect& f) {
	return mmRect(f.pos.x - GLASS_X, f.pos.y - GLASS_Y, f.size.x, f.size.y);
}

// --- silkscreen ------------------------------------------------------------
static const Label LABELS[] = {
	{ 25.4000f,   5.5000f, 10.50f, 1.50f, PAPER    , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "REBATE"},
	{  1.4000f,   8.2500f,  7.40f, 0.00f, LIME     , NVG_ALIGN_LEFT | NVG_ALIGN_BASELINE, 1,     "$"},
	{ 25.4000f,   8.0000f,  5.40f, 0.40f, LIME     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "MIDIVERB DIGITAL REVERB"},
	{  2.1717f,  60.0491f,  4.60f, 0.40f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 2,     "MOON TECHNOLOGIES"},
	{ 48.6283f,  60.0491f,  4.60f, 0.40f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 3,     "FORM 843"},
	{ 25.4000f,  40.0000f,  6.00f, 0.60f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "FRONT PANEL"},
	{ 20.8590f,  48.3143f,  5.80f, 0.00f, LIME_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "-12 dB"},
	{ 31.1196f,  48.3143f,  5.80f, 0.00f, CLAY_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "0 dB"},
	{ 25.4000f,  72.3212f,  7.00f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "MIX"},
	{  6.4900f, 113.3100f,  6.20f, 0.00f, SAGE     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "IN L"},
	{ 19.0967f, 113.3100f,  6.20f, 0.00f, SAGE     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "IN R"},
	{ 31.7033f, 113.3100f,  6.20f, 0.00f, MINT     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "OUT L"},
	{ 44.3100f, 113.3100f,  6.20f, 0.00f, MINT     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "OUT R"},
};

/** Draws this panel's silkscreen. `static` so each module keeps its own,
    bound to its own table. */
static inline void addLabels(app::ModuleWidget* mw) {
	addLabels(mw, LABELS, sizeof(LABELS) / sizeof(LABELS[0]));
}

// --- widget positions, by the names used in tools/panels/Rebate.py -----
// Positions are mm; feed them to mm() or createParamCentered.
static const Vec METER_GREEN_POS = Vec(20.8590, 43.7500);
static const Vec METER_RED_POS = Vec(31.1196, 43.7500);
static const Vec MIX_POS = Vec(25.4000, 61.5143);
static const Vec IN_L_POS = Vec(6.4900, 118.6000);
static const Vec IN_R_POS = Vec(19.0967, 118.6000);
static const Vec OUT_L_POS = Vec(31.7033, 118.6000);
static const Vec OUT_R_POS = Vec(44.3100, 118.6000);

} // namespace panel
