// Generated by panelkit from tools/panels/Racketeer.py. Do not edit; edit the spec.
//
// Everything the panel's C++ needs to agree with res/Racketeer.svg: the millimetre
// grid, the widget positions and the whole silkscreen. Rack's nanosvg discards
// <text>, so labels cannot live in the SVG -- they are drawn at runtime from
// the table below, generated from the same spec that drew the artwork.
//
// Every declaration here is `static`, i.e. private to the translation unit, so
// the three panels in this plugin cannot collide. That also means no
// translation unit may include two of these.
#pragma once
#include "../PanelTheme.hpp"

namespace panel {

// --- identity --------------------------------------------------------------
static const int   HP = 18;
static const float W  = 91.4400f;  // mm
static const float H  = 128.5000f;  // mm

// --- the read-out well: the spec's numbers, not the widget's ---------------
// A display used to be positioned by hand in the module's C++, in the same
// millimetres the spec had already chosen -- two copies of one number, and
// they drifted. The widget takes them from here now.
static const float GLASS_X = 4.2000f;
static const float GLASS_Y = 9.8000f;
static const float GLASS_W = 83.0400f;
static const float GLASS_H = 8.8000f;

// --- silkscreen ------------------------------------------------------------
static const Label LABELS[] = {
	{ 45.7200f,   5.5000f, 10.50f, 1.50f, PAPER    , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "RACKETEER"},
	{ 11.5600f,   8.2500f,  7.40f, 0.00f, LIME     , NVG_ALIGN_LEFT | NVG_ALIGN_BASELINE, true,  "$"},
	{ 13.7637f,   8.0000f,  4.60f, 0.40f, SAGE     , NVG_ALIGN_LEFT | NVG_ALIGN_BASELINE, false, "MOON TECHNOLOGIES"},
	{ 87.2400f,   8.0000f,  4.60f, 0.40f, SAGE     , NVG_ALIGN_RIGHT | NVG_ALIGN_BASELINE, false, "FORM 211"},
	{ 45.7200f,  22.1000f,  6.00f, 0.60f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "RACKET"},
	{ 24.7200f,  43.0154f,  7.00f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "TIME"},
	{ 45.7200f,  43.0154f,  7.00f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "ECHO"},
	{ 66.7200f,  43.0154f,  7.00f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "CUTOFF"},
	{ 16.5325f,  55.4110f,  6.20f, 0.00f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "LAG"},
	{ 28.2075f,  55.4110f,  6.20f, 0.00f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "DRIVE"},
	{ 39.8825f,  55.4110f,  6.20f, 0.00f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "SEED"},
	{ 51.5575f,  55.4110f,  6.20f, 0.00f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "RATE"},
	{ 63.2325f,  55.4110f,  6.20f, 0.00f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "RES"},
	{ 74.9075f,  55.4110f,  6.20f, 0.00f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "THRESH"},
	{ 45.7200f,  61.7049f,  6.00f, 0.60f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "ENFORCEMENT"},
	{  9.3574f,  74.4008f,  6.60f, 0.00f, LIME_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "NOISE"},
	{ 22.9074f,  74.4008f,  6.60f, 0.00f, LIME_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "BOOST"},
	{ 36.4574f,  74.4008f,  6.60f, 0.00f, LIME_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "MUTE"},
	{ 47.9317f,  74.4008f,  6.20f, 0.00f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "CHOP"},
	{ 61.9388f,  74.4008f,  6.20f, 0.00f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "POL"},
	{ 72.6257f,  74.4008f,  6.20f, 0.00f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "FILTER"},
	{ 83.3126f,  74.4008f,  6.20f, 0.00f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "RANGE"},
	{ 45.7200f,  81.8787f,  6.00f, 0.60f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "SKIM"},
	{ 11.8450f,  94.2305f,  6.20f, 0.00f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "TIME"},
	{ 25.3950f,  94.2305f,  6.20f, 0.00f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "ECHO"},
	{ 38.9450f,  94.2305f,  6.20f, 0.00f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "CUTOFF"},
	{ 52.4950f,  94.2305f,  6.20f, 0.00f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "RATE"},
	{ 66.0450f,  94.2305f,  6.20f, 0.00f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "RES"},
	{ 79.5950f,  94.2305f,  6.20f, 0.00f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "LAG"},
	{  7.2900f, 113.4100f,  6.20f, 0.00f, SAGE     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "IN"},
	{ 18.2700f, 113.4100f,  6.20f, 0.00f, SAGE     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "NOISE"},
	{ 29.2500f, 113.4100f,  6.20f, 0.00f, SAGE     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "BOOST"},
	{ 40.2300f, 113.4100f,  6.20f, 0.00f, SAGE     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "MUTE"},
	{ 51.2100f, 113.4100f,  6.20f, 0.00f, MINT     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "ENV"},
	{ 62.1900f, 113.4100f,  6.20f, 0.00f, MINT     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "GATE"},
	{ 73.1700f, 113.4100f,  6.20f, 0.00f, MINT     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "DIRTY"},
	{ 84.1500f, 113.4100f,  6.20f, 0.00f, MINT     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "OUT"},
};

/** Draws this panel's silkscreen. `static` so each module keeps its own,
    bound to its own table. */
static inline void addLabels(app::ModuleWidget* mw) {
	addLabels(mw, LABELS, sizeof(LABELS) / sizeof(LABELS[0]));
}

// --- widget positions, by the names used in tools/panels/Racketeer.py -----
// Positions are mm; feed them to mm() or createParamCentered.
static const Vec LOOP_POS = Vec(52.6272, 21.3685);
static const Vec TIME_POS = Vec(24.7200, 32.3085);
static const Vec ECHO_POS = Vec(45.7200, 32.3085);
static const Vec CUTOFF_POS = Vec(66.7200, 32.3085);
static const Vec LAG_POS = Vec(16.5325, 49.2792);
static const Vec DRIVE_POS = Vec(28.2075, 49.2792);
static const Vec SEED_POS = Vec(39.8825, 49.2792);
static const Vec RATE_POS = Vec(51.5575, 49.2792);
static const Vec RES_POS = Vec(63.2325, 49.2792);
static const Vec THRESH_POS = Vec(74.9075, 49.2792);
static const Vec NOISE_POS = Vec(9.3574, 67.1049);
static const Vec BOOST_POS = Vec(22.9074, 67.1049);
static const Vec MUTE_POS = Vec(36.4574, 67.1049);
static const Vec CHOP_POS = Vec(47.9317, 67.1049);
static const Vec POL_POS = Vec(61.9388, 67.1049);
static const Vec FILT_POS = Vec(72.6257, 67.1049);
static const Vec RANGE_POS = Vec(83.3126, 67.1049);
static const Vec CHOP_LED_POS = Vec(53.0914, 73.6449);
static const Vec TIME_CV_POS = Vec(11.8450, 86.6987);
static const Vec ECHO_CV_POS = Vec(25.3950, 86.6987);
static const Vec CUTOFF_CV_POS = Vec(38.9450, 86.6987);
static const Vec RATE_CV_POS = Vec(52.4950, 86.6987);
static const Vec RES_CV_POS = Vec(66.0450, 86.6987);
static const Vec LAG_CV_POS = Vec(79.5950, 86.6987);
static const Vec TIME_IN_POS = Vec(11.8450, 100.8205);
static const Vec ECHO_IN_POS = Vec(25.3950, 100.8205);
static const Vec CUTOFF_IN_POS = Vec(38.9450, 100.8205);
static const Vec RATE_IN_POS = Vec(52.4950, 100.8205);
static const Vec RES_IN_POS = Vec(66.0450, 100.8205);
static const Vec LAG_IN_POS = Vec(79.5950, 100.8205);
static const Vec IN_POS = Vec(7.2900, 118.6000);
static const Vec NOISE_IN_POS = Vec(18.2700, 118.6000);
static const Vec BOOST_IN_POS = Vec(29.2500, 118.6000);
static const Vec MUTE_IN_POS = Vec(40.2300, 118.6000);
static const Vec ENV_OUT_POS = Vec(51.2100, 118.6000);
static const Vec GATE_OUT_POS = Vec(62.1900, 118.6000);
static const Vec DIRTY_OUT_POS = Vec(73.1700, 118.6000);
static const Vec OUT_POS = Vec(84.1500, 118.6000);

} // namespace panel
