// Generated by panelkit. Do not edit; edit panelkit/emit.py.
//
// The family's shared panel vocabulary: the palette, the millimetre grid, the
// text kit and the hardware. Every panel in the plugin draws through this and
// nothing else -- no module may call nvgFontFaceId, nvgFontSize,
// nvgTextLetterSpacing, nvgTextBounds, nvgText or loadFont itself. `make panel`
// prints every place that does.
//
// This file is included by every src/<Module>/Panel.hpp, which adds that one
// panel's numbers. Include the Panel.hpp, not this.
//
// Everything below has external linkage (inline or template), so it is defined
// once for the whole plugin. Anything that varies per panel belongs in
// Panel.hpp instead, as `static`.
#pragma once
#include <rack.hpp>

#include <cmath>
#include <cstddef>
#include <memory>
#include <string>
#include <vector>

// Declared here rather than pulled in from plugin.hpp, so this header can be
// included from anywhere in the plugin without dragging the module in with it.
extern rack::Plugin* pluginInstance;

namespace panel {

using namespace rack;

// --- geometry --------------------------------------------------------------
/** The standard Eurorack 3U face. Panel width is per-module: see Panel.hpp. */
static const float PANEL_H = 128.5000f;  // mm

// --- palette ---------------------------------------------------------------
// `static` because NVGcolor is not a literal type under C++11, which is what
// the Rack SDK compiles plugins as -- so these cannot be inline variables and
// each translation unit gets its own copy. The values are generated, so the
// copies cannot disagree.
static const NVGcolor INK    = nvgRGB(0x18, 0x1e, 0x15);   // engraving ink: the dark bands, and primary text on the face
static const NVGcolor PAPER  = nvgRGB(0xe4, 0xea, 0xe1);   // the face, and primary text on dark ground
static const NVGcolor FELT   = nvgRGB(0xe7, 0xe1, 0xea);   // section blocks
static const NVGcolor BAND   = nvgRGB(0x18, 0x1e, 0x15);   // masthead and footer bands
static const NVGcolor GLASS  = nvgRGB(0x1b, 0x15, 0x1e);   // displays and widget wells
static const NVGcolor RULE   = nvgRGB(0x7b, 0x9a, 0x6d);   // the guilloche: rules, frames, traces
static const NVGcolor LIME   = nvgRGB(0xaa, 0xbe, 0xa1);   // accent on dark ground; LED emitters
static const NVGcolor MINT   = nvgRGB(0xa9, 0xbd, 0xa0);   // affirmatives: outputs
static const NVGcolor CLAY   = nvgRGB(0x99, 0x93, 0x9c);   // action required
static const NVGcolor SAGE   = nvgRGB(0x7b, 0x9a, 0x6d);   // secondary text on dark ground
static const NVGcolor SAGE_DARK = nvgRGB(0x4e, 0x62, 0x45);   // secondary text on the face
static const NVGcolor LIME_DARK = nvgRGB(0x62, 0x7b, 0x57);   // accent text on the face
static const NVGcolor MINT_DARK = nvgRGB(0x59, 0x66, 0x54);   // output text on the face
static const NVGcolor CLAY_DARK = nvgRGB(0x62, 0x5c, 0x65);   // warning text on the face

inline NVGcolor alpha(NVGcolor c, float a) { c.a = a; return c; }

// --- fonts -----------------------------------------------------------------
// UI is Nunito Bold (the silkscreen), read-outs are Share Tech Mono, and
// numerals in a read-out are DSEG7. DSEG7's cmap carries only [0-9 . : -];
// Rack chains NotoSansJP as a fallback onto every font, so a stray '%' in the
// segment face renders as proportional Japanese sans rather than a tofu box.
inline std::string uiFont()   { return asset::system("res/fonts/Nunito-Bold.ttf"); }
inline std::string monoFont() { return asset::system("res/fonts/ShareTechMono-Regular.ttf"); }
inline std::string segFont()  { return asset::system("res/fonts/DSEG7ClassicMini-Bold.ttf"); }

inline Vec mm(float x, float y) { return mm2px(Vec(x, y)); }
inline Rect mmRect(float x, float y, float w, float h) {
	return Rect(mm2px(Vec(x, y)), mm2px(Vec(w, h)));
}

// --- text ------------------------------------------------------------------
// Rack's nanosvg discards <text>, so every word on a family panel is drawn at
// runtime. That makes text drawing the single most repeated thing the plugins
// do, which is why the whole vocabulary for it lives here rather than being
// re-spelled at each call site.

/** The three faces the family uses. */
enum class Face { Ui, Mono, Seg };

inline std::string facePath(Face f) {
	switch (f) {
		case Face::Mono: return monoFont();
		case Face::Seg:  return segFont();
		default:         return uiFont();
	}
}

/** How one run of text is set.
 *
 * Bundled rather than passed as five arguments because two of these are sticky
 * global state on the NVGcontext: a run that sets letter spacing or an
 * alignment and does not put it back silently restyles whatever draws next.
 * Going through TextStyle makes that impossible to forget. */
struct TextStyle {
	Face face = Face::Ui;
	float size = 10.f;
	float tracking = 0.f;
	NVGcolor ink = PAPER;
	int align = NVG_ALIGN_LEFT | NVG_ALIGN_BASELINE;

	TextStyle() {}
	TextStyle(Face face, float size, NVGcolor ink, int align, float tracking = 0.f)
		: face(face), size(size), tracking(tracking), ink(ink), align(align) {}

	/** A copy in a different ink -- the usual reason a call site wants a variant. */
	TextStyle inked(NVGcolor c) const { TextStyle s = *this; s.ink = c; return s; }
	TextStyle aligned(int a) const { TextStyle s = *this; s.align = a; return s; }
	TextStyle sized(float px) const { TextStyle s = *this; s.size = px; return s; }
};

/** Binds a style to the context. False means the face has not loaded yet and the
    caller must draw nothing: nvgText with no face bound is undefined. */
inline bool bindStyle(NVGcontext* vg, const TextStyle& s) {
	std::shared_ptr<window::Font> font = APP->window->loadFont(facePath(s.face));
	if (!font)
		return false;
	nvgFontFaceId(vg, font->handle);
	nvgFontSize(vg, s.size);
	nvgTextAlign(vg, s.align);
	nvgTextLetterSpacing(vg, s.tracking);
	nvgFillColor(vg, s.ink);
	return true;
}

/** Draws one run, then clears the tracking it set. */
inline float text(NVGcontext* vg, const TextStyle& s, float x, float y, const char* str) {
	if (!bindStyle(vg, s))
		return x;
	float end = nvgText(vg, x, y, str, NULL);
	nvgTextLetterSpacing(vg, 0.f);
	return end;
}

inline float text(NVGcontext* vg, const TextStyle& s, float x, float y,
                  const std::string& str) {
	return text(vg, s, x, y, str.c_str());
}

inline float text(NVGcontext* vg, const TextStyle& s, Vec p, const std::string& str) {
	return text(vg, s, p.x, p.y, str.c_str());
}

/** Width of `str` in `s`, in local units. Leaves no tracking behind. */
inline float textWidth(NVGcontext* vg, const TextStyle& s, const std::string& str) {
	if (!bindStyle(vg, s))
		return 0.f;
	float bounds[4];
	nvgTextBounds(vg, 0, 0, str.c_str(), NULL, bounds);
	nvgTextLetterSpacing(vg, 0.f);
	return bounds[2] - bounds[0];
}

/** Draws a run reflected about its anchor -- the maker's mark, and anything else
    that wants a genuine glyph rather than a traced curve. The alignment flips
    with the axis, so the glyph lands on the side of `x` it would have occupied
    unmirrored. */
inline void textMirrored(NVGcontext* vg, const TextStyle& s, float x, float y,
                         const char* str) {
	TextStyle f = s;
	if (f.align & NVG_ALIGN_LEFT)
		f.align = (f.align & ~NVG_ALIGN_LEFT) | NVG_ALIGN_RIGHT;
	else if (f.align & NVG_ALIGN_RIGHT)
		f.align = (f.align & ~NVG_ALIGN_RIGHT) | NVG_ALIGN_LEFT;
	nvgSave(vg);
	nvgTranslate(vg, x, y);
	nvgScale(vg, -1.f, 1.f);
	text(vg, f, 0.f, 0.f, str);
	nvgRestore(vg);
}

/** The uniform scale of the context's current transform. */
inline float transformScale(NVGcontext* vg) {
	float xf[6];
	nvgCurrentTransform(vg, xf);
	return std::sqrt(std::fabs(xf[0] * xf[3] - xf[1] * xf[2]));
}

/** `str` trimmed to `maxWidth` with a trailing ellipsis, remembered until one of
 * its inputs changes.
 *
 * Both halves matter. The measuring is a binary search over codepoint
 * boundaries, not a character-at-a-time trim: a trim costs one text shaping pass
 * per character dropped, which for a long title is forty-odd passes -- every
 * frame, for every row on screen. The cache then takes the steady-state cost to
 * nothing, since the text of a panel changes far more rarely than it is drawn.
 *
 * The transform scale is part of the key because nvgTextBounds quantizes to the
 * rasterized glyph grid: the same string at the same nominal size measures a
 * shade wider at a different rack zoom, and a stale fit would clip. */
/** All-segments-on ghost behind a numeric read-out: every digit becomes an 8.
    This is what sells a seven-segment display -- without it the unlit segments
    are simply absent and the thing reads as text in an odd face. */
inline std::string segGhost(const std::string& s) {
	std::string g = s;
	for (size_t i = 0; i < g.size(); i++)
		if (g[i] >= '0' && g[i] <= '9')
			g[i] = '8';
	return g;
}

/** Draws a numeral in the segment face over its ghost, then its unit in the text
 * face, and returns the x advance.
 *
 * The family's read-out rule in one function: numerals in DSEG7, words in Share
 * Tech Mono. DSEG7's cmap carries only [0-9 . : -], so a unit MUST leave the
 * segment face or Rack's NotoSansJP fallback renders it as Japanese sans. Note
 * also that DSEG7's '.' has zero advance -- it overprints the previous glyph --
 * so "2.997" occupies four cells, not five, and anything measuring these strings
 * has to measure rather than count. */
inline float segValue(NVGcontext* vg, float x, float y, float size,
                      const std::string& num, const std::string& unit, NVGcolor ink) {
	TextStyle seg(Face::Seg, size, alpha(ink, 0.13f),
	              NVG_ALIGN_LEFT | NVG_ALIGN_BASELINE);
	text(vg, seg, x, y, segGhost(num));
	float end = text(vg, seg.inked(ink), x, y, num);
	if (!unit.empty()) {
		TextStyle u(Face::Mono, size * 0.72f, alpha(ink, 0.7f),
		            NVG_ALIGN_LEFT | NVG_ALIGN_BASELINE);
		end = text(vg, u, end + 1.5f, y, unit);
	}
	return end;
}

struct FittedText {
	const std::string& get(NVGcontext* vg, const TextStyle& style,
	                       const std::string& str, float maxWidth) {
		float sc = transformScale(vg);
		if (maxWidth != cachedWidth || style.size != cachedSize
		    || style.face != cachedFace || sc != cachedScale || str != source) {
			source = str;
			cachedWidth = maxWidth;
			cachedSize = style.size;
			cachedFace = style.face;
			cachedScale = sc;
			result = fit(vg, style, str, maxWidth);
		}
		return result;
	}

	/** The uncached form. Prefer get() anywhere this runs per frame. */
	static std::string fit(NVGcontext* vg, const TextStyle& style,
	                       const std::string& str, float maxWidth) {
		if (textWidth(vg, style, str) <= maxWidth)
			return str;

		// Every index at which a UTF-8 codepoint starts, plus the end. Trimming
		// bytes instead would split multi-byte glyphs.
		std::vector<size_t> stops;
		stops.push_back(0);
		for (size_t i = 1; i <= str.size(); i++)
			if (i == str.size() || ((unsigned char) str[i] & 0xC0) != 0x80)
				stops.push_back(i);

		static const char* const ELLIPSIS = "\xE2\x80\xA6";   // U+2026

		// Largest prefix that still fits once the ellipsis is added. lo is the
		// empty prefix, which is just the ellipsis: if even that overflows we
		// return it rather than an empty line, because a blank row reads as a
		// bug and a lone ellipsis reads as a truncation.
		size_t lo = 0, hi = stops.size() - 1;
		while (lo < hi) {
			size_t mid = lo + (hi - lo + 1) / 2;
			if (textWidth(vg, style, str.substr(0, stops[mid]) + ELLIPSIS) <= maxWidth)
				lo = mid;
			else
				hi = mid - 1;
		}
		return str.substr(0, stops[lo]) + ELLIPSIS;
	}

private:
	std::string source;
	std::string result;
	float cachedWidth = -1.f;
	float cachedSize = -1.f;
	float cachedScale = -1.f;
	Face cachedFace = Face::Ui;
};

// --- shared hardware -------------------------------------------------------
/** Hex-head brass screw. The SVG is exactly 15 x 14.9989 px, matching stock
    ScrewSilver, because SvgScrew takes its box size straight from the SVG. */
struct ScrewHex : app::SvgScrew {
	ScrewHex() {
		setSvg(Svg::load(asset::plugin(pluginInstance, "res/ScrewHex.svg")));
	}
};

/** Brass-collared jacks on the stock PJ301M canvas. The stock chrome collar is
    the loudest off-palette object on a green panel; brass matches the screws.
    The output variant rings the throat in mint. */
struct PortIn : app::SvgPort {
	PortIn() {
		setSvg(Svg::load(asset::plugin(pluginInstance, "res/PortIn.svg")));
	}
};

/** The same jacks, with a thin lime line inside the throat: this one
 *  carries timing -- a clock, a trigger, a gate, a reset -- rather than
 *  a level. The band still says which way it goes. */
struct PortTrigIn : app::SvgPort {
	PortTrigIn() {
		setSvg(Svg::load(asset::plugin(pluginInstance, "res/PortTrigIn.svg")));
	}
};

struct PortTrigOut : app::SvgPort {
	PortTrigOut() {
		setSvg(Svg::load(asset::plugin(pluginInstance, "res/PortTrigOut.svg")));
	}
};
struct PortOut : app::SvgPort {
	PortOut() {
		setSvg(Svg::load(asset::plugin(pluginInstance, "res/PortOut.svg")));
	}
};

/** The main input and the main output: the same jacks with the collar
 *  struck in gold instead of brass. Use them for the one port a patch
 *  reaches for first -- a mix output beside four voice outputs, the two
 *  of a stereo pair -- and nowhere else. A panel where everything is
 *  gold says the same as a panel where nothing is. */
struct PortInMain : app::SvgPort {
	PortInMain() {
		setSvg(Svg::load(asset::plugin(pluginInstance, "res/PortInMain.svg")));
	}
};

struct PortOutMain : app::SvgPort {
	PortOutMain() {
		setSvg(Svg::load(asset::plugin(pluginInstance, "res/PortOutMain.svg")));
	}
};

struct PortTrigInMain : app::SvgPort {
	PortTrigInMain() {
		setSvg(Svg::load(asset::plugin(pluginInstance, "res/PortTrigInMain.svg")));
	}
};

struct PortTrigOutMain : app::SvgPort {
	PortTrigOutMain() {
		setSvg(Svg::load(asset::plugin(pluginInstance, "res/PortTrigOutMain.svg")));
	}
};

//: The plate a MiniDisplay fills, in mm -- the readout widget's own size.
static const float READOUT_W = 8.6000f;
static const float READOUT_H = 2.7000f;

/** A little lit plate that names the control above it.
 *
 *  For a control whose meaning is not fixed: a macro knob that is DECAY
 *  on one program and SPREAD on the next cannot be engraved, and a panel
 *  that engraves it anyway is lying two thirds of the time. The plate
 *  itself is drawn in the panel art as the widget's own well, so this
 *  only writes the word into it.
 *
 *  Point `name` at a `const char*` the module keeps up to date. A null
 *  pointer, or a null string, draws the family's own way of saying
 *  nothing: two dashes. That is deliberate -- a knob the running program
 *  has no use for should say so where the knob is, not go blank and look
 *  broken. */
struct MiniDisplay : widget::Widget {
	//: Point this at a const char* the module keeps up to date.
	const char* const* name = NULL;
	float size = 5.2f;
	FittedText fitted;

	void drawLayer(const DrawArgs& args, int layer) override {
		if (layer != 1) return;
		const char* t = (name && *name) ? *name : "--";
		TextStyle st(Face::Mono, size, LIME,
		             NVG_ALIGN_CENTER | NVG_ALIGN_MIDDLE, 0.f);
		// Ellipsized to the plate: a long name shortens rather than
		// spilling over the two knobs either side of it. Cached, because
		// this runs every frame and the name changes only on a program.
		text(args.vg, st, box.size.x / 2.f, box.size.y / 2.f,
		     fitted.get(args.vg, st, t, box.size.x - 2.f));
	}
};

/** A level arc struck into the seat ring around a knob.
 *
 *  The recessed seat every widget stands in is already a dark band a
 *  little wider than the knob it holds; drawing the meter there costs the
 *  panel no width and no height at all, which is what makes it affordable
 *  on a control that has four of itself in a row. It sweeps the knob's own
 *  travel, so full scale is where the pointer would be at maximum.
 *
 *  Point `value` at a float the module keeps in 0..1. A null pointer draws
 *  nothing, which is what a browser preview and a module-less panel want. */
struct MeterArc : widget::Widget {
	float* value = NULL;
	// px. A knob is 4.80 mm and its well 5.70, which at Rack's 2.9528 px
	// per mm is a band from 14.17 to 16.83 -- the dark seat already drawn
	// around every widget. The arc runs up the middle of it.
	float r = 15.5f;
	NVGcolor ink = LIME;

	void drawLayer(const DrawArgs& args, int layer) override {
		if (layer != 1 || !value) return;
		float v = *value;
		if (!(v > 0.f)) return;
		if (v > 1.f) v = 1.f;
		// Rack turns a knob from -0.83*pi to +0.83*pi, measured from
		// straight up; nvg measures from the positive x axis.
		const float span = 0.83f * M_PI;
		float a0 = -M_PI / 2.f - span;
		nvgBeginPath(args.vg);
		nvgArc(args.vg, box.size.x / 2.f, box.size.y / 2.f, r,
		       a0, a0 + 2.f * span * v, NVG_CW);
		nvgStrokeColor(args.vg, ink);
		nvgStrokeWidth(args.vg, 1.6f);
		nvgLineCap(args.vg, NVG_ROUND);
		nvgStroke(args.vg);
	}
};

/** UP over DOWN, a hair apart: the control for a selector that is a count and not an angle.
 *
 *  A preset knob is the wrong shape for what it does. Nobody turns to the three hundred and
 *  seventeenth sound; they press once for the next one, and a knob makes that a drag you have
 *  to land. This is bound to the same param the knob was, so a patch, a CV map and the param's
 *  own tooltip are all unchanged -- it only moves the value by one, the top button up and the
 *  bottom down, clamped to the param's own range (or wrapped, for a ring of sounds that has no
 *  end). Hold either to repeat, after a beat.
 *
 *  The pair is a knob's height (9.6 mm) and the spec reserves exactly that, so it stands
 *  where the knob stood. Colour comes from the palette and nothing else: the buttons are
 *  SAGE on the dark well, and light to LIME while pressed. */
struct StepPair : app::ParamWidget {
	//: Wrap from the last value to the first (and back) instead of stopping. Ignored
	//: when the param's range is unbounded, which is how an endless encoder is configured.
	bool wrap = false;
	float stepSize = 1.f;

	int held = 0;               // +1 the top button is down, -1 the bottom one, 0 neither
	int hover = 0;              // which half the pointer is over
	double nextAt = 0.0;
	float oldValue = NAN;       // the value when the press began: one undo step per hold

	static constexpr float BTN = 4.5f / 9.6f;       // each button's share of the pair's height

	/** No SVG gives this a size, so it takes the spec's: EXTENT["stepper"] in panelkit/spec.py. */
	StepPair() { box.size = mm(6.8000f, 9.6000f); }

	/** The half (+1 top, -1 bottom) a point inside the widget is over. */
	int halfAt(float y) const { return y < box.size.y / 2.f ? +1 : -1; }

	void nudge(int dir) {
		engine::ParamQuantity* pq = getParamQuantity();
		if (!pq) return;
		const float lo = pq->getMinValue(), hi = pq->getMaxValue(), v = pq->getValue();
		float n = v + dir * stepSize;
		if (wrap && std::isfinite(lo) && std::isfinite(hi))
			n = n > hi ? lo : n < lo ? hi : n;
		pq->setValue(n);        // clamps, and snaps a snapping param
	}

	void onButton(const ButtonEvent& e) override {
		if (e.button == GLFW_MOUSE_BUTTON_LEFT && e.action == GLFW_PRESS && (e.mods & RACK_MOD_MASK) == 0) {
			if (engine::ParamQuantity* pq = getParamQuantity()) {
				e.consume(this);
				oldValue = pq->getValue();
				held = halfAt(e.pos.y);
				nudge(held);
				nextAt = system::getTime() + 0.45;
			}
			return;
		}
		ParamWidget::onButton(e);   // the right-click menu
	}

	void onDragEnd(const DragEndEvent& e) override {
		held = 0;
		engine::ParamQuantity* pq = getParamQuantity();
		if (pq && module && !std::isnan(oldValue) && pq->getValue() != oldValue) {
			history::ParamChange* h = new history::ParamChange;
			h->name = "change preset";
			h->moduleId = module->id;
			h->paramId = paramId;
			h->oldValue = oldValue;
			h->newValue = pq->getValue();
			APP->history->push(h);
		}
		oldValue = NAN;
		ParamWidget::onDragEnd(e);
	}

	void onHover(const HoverEvent& e) override {
		hover = halfAt(e.pos.y);
		ParamWidget::onHover(e);
	}
	void onLeave(const LeaveEvent& e) override { hover = 0; ParamWidget::onLeave(e); }

	void step() override {
		ParamWidget::step();
		if (held && system::getTime() >= nextAt) {
			nudge(held);
			nextAt += 0.07;
		}
	}

	void draw(const DrawArgs& args) override {
		NVGcontext* vg = args.vg;
		const float w = box.size.x, bh = box.size.y * BTN;
		for (int dir = +1; dir >= -1; dir -= 2) {
			const float y = dir > 0 ? 0.f : box.size.y - bh;
			const bool down = held == dir;
			nvgBeginPath(vg);
			nvgRoundedRect(vg, 0.5f, y + 0.5f, w - 1.f, bh - 1.f, 2.2f);
			nvgFillColor(vg, down ? LIME : alpha(SAGE, hover == dir ? 0.46f : 0.30f));
			nvgFill(vg);
			nvgStrokeColor(vg, alpha(RULE, 0.9f));
			nvgStrokeWidth(vg, 0.6f);
			nvgStroke(vg);
			// the arrow: a triangle pointing the way the button steps
			const float cx = w / 2.f, cy = y + bh / 2.f, a = bh * 0.22f, b = bh * 0.17f;
			nvgBeginPath(vg);
			nvgMoveTo(vg, cx, cy - dir * a);
			nvgLineTo(vg, cx + a * 1.35f, cy + dir * b);
			nvgLineTo(vg, cx - a * 1.35f, cy + dir * b);
			nvgClosePath(vg);
			nvgFillColor(vg, down ? INK : PAPER);
			nvgFill(vg);
		}
		ParamWidget::draw(args);
	}
};

/** The pointer a screen field asks for while it is under the mouse: up/down arrows over a
 *  value you hold and drag, a hand over a thing you click. Rack never sets a cursor shape of
 *  its own, so the one set here stays until a field puts the default back. */
struct ScreenCursor {
	static GLFWcursor* shape(int which) {
		static GLFWcursor* arrows = NULL;
		static GLFWcursor* hand = NULL;
		GLFWcursor*& c = which == GLFW_HAND_CURSOR ? hand : arrows;
		if (!c) c = glfwCreateStandardCursor(which);
		return c;
	}
	static void set(int which) {
		if (APP && APP->window && APP->window->win)
			glfwSetCursor(APP->window->win, which ? shape(which) : NULL);
	}
};

/** Something on a screen you can take hold of.
 *
 *  A display that prints a value is the obvious place to change it, so a value printed on a
 *  screen is a control: the field is a ParamWidget whose box is a cell of the glass (FIELD_<NAME>
 *  in Panel.hpp), bound to the same param a knob would be. That keeps everything a param is
 *  owed for free -- the tooltip, the right-click menu with typed entry, MIDI-Map learn, undo,
 *  double-click to reset. The field draws no value of its own; the module's display draws it in
 *  the same rectangle, and this only says, under the pointer, that it can be taken hold of. */
struct ScreenField : app::ParamWidget {
	bool hovered = false;
	bool dragging = false;

	virtual int cursorShape() { return GLFW_VRESIZE_CURSOR; }

	void onEnter(const EnterEvent& e) override {
		hovered = true;
		ScreenCursor::set(cursorShape());
		ParamWidget::onEnter(e);
	}
	void onLeave(const LeaveEvent& e) override {
		hovered = false;
		if (!dragging) ScreenCursor::set(0);
		ParamWidget::onLeave(e);
	}
	void endDrag() {
		dragging = false;
		if (!hovered) ScreenCursor::set(0);
	}
	~ScreenField() {
		if (hovered || dragging) ScreenCursor::set(0);
	}

	/** Drawn on the light layer so it shows at any room brightness, like the display it sits on. */
	void drawLayer(const DrawArgs& args, int layer) override {
		ParamWidget::drawLayer(args, layer);
		if (layer != 1 || !(hovered || dragging)) return;
		NVGcontext* vg = args.vg;
		nvgBeginPath(vg);
		nvgRoundedRect(vg, 0.5f, 0.5f, box.size.x - 1.f, box.size.y - 1.f, 1.6f);
		nvgFillColor(vg, alpha(LIME, dragging ? 0.10f : 0.06f));
		nvgFill(vg);
		nvgStrokeColor(vg, alpha(LIME, dragging ? 0.75f : 0.45f));
		nvgStrokeWidth(vg, 0.7f);
		nvgStroke(vg);
	}
};

/** A value: hold it and drag up or down. The pointer is up/down arrows the whole time, so the
 *  hand reads as moving the number rather than turning something. Ctrl drags fine, Shift
 *  coarse, the same modifiers as a knob; the wheel nudges when Rack's own knob-scroll setting is
 *  on (it is off by default because it would steal the scroll that moves the rack). */
struct ScreenKnob : ScreenField {
	//: Multiplies the drag rate. 1 crosses the whole range in about as far as a knob does.
	float speed = 1.f;
	float oldValue = NAN;
	float snapDelta = 0.f;
	float dragged = 0.f;

	static float modSpeed() {
		int mods = APP->window->getMods() & RACK_MOD_MASK;
		if (mods == RACK_MOD_CTRL) return 1 / 10.f;
		if (mods == GLFW_MOD_SHIFT) return 4.f;
		if (mods == (RACK_MOD_CTRL | GLFW_MOD_SHIFT)) return 1 / 100.f;
		return 1.f;
	}

	/** How far one pixel of travel moves the value. Matched to Rack's linear knob mode
	 *  (sensitivity over a 300-degree sweep), so a field and a knob feel like one hand. */
	virtual float perPixel(engine::ParamQuantity* pq) {
		const float range = pq->isBounded() ? pq->getRange() : 1.f;
		return settings::knobLinearSensitivity * speed * range / (300.f / 360.f);
	}

	/** A click that did not become a drag. A value has nothing to do; a choice opens. */
	virtual void click() {}

	void onDragStart(const DragStartEvent& e) override {
		if (e.button != GLFW_MOUSE_BUTTON_LEFT) return;
		if (engine::ParamQuantity* pq = getParamQuantity()) oldValue = pq->getValue();
		snapDelta = 0.f;
		dragged = 0.f;
		dragging = true;
		ParamWidget::onDragStart(e);
	}

	void onDragMove(const DragMoveEvent& e) override {
		if (e.button != GLFW_MOUSE_BUTTON_LEFT) return;
		engine::ParamQuantity* pq = getParamQuantity();
		if (!pq) return;
		dragged += std::fabs(e.mouseDelta.y) + std::fabs(e.mouseDelta.x);
		float delta = -e.mouseDelta.y * perPixel(pq) * modSpeed();
		if (pq->snapEnabled) {
			snapDelta += delta;
			delta = std::trunc(snapDelta);
			snapDelta -= delta;
		}
		pq->setValue(pq->getValue() + delta);
		ParamWidget::onDragMove(e);
	}

	void onDragEnd(const DragEndEvent& e) override {
		if (e.button != GLFW_MOUSE_BUTTON_LEFT) return;
		pushHistory("move");
		endDrag();
		if (dragged < 4.f) click();
		ParamWidget::onDragEnd(e);
	}

	void pushHistory(const char* what) {
		engine::ParamQuantity* pq = getParamQuantity();
		if (pq && module && !std::isnan(oldValue) && pq->getValue() != oldValue) {
			history::ParamChange* h = new history::ParamChange;
			h->name = std::string(what) + " " + pq->getLabel();
			h->moduleId = module->id;
			h->paramId = paramId;
			h->oldValue = oldValue;
			h->newValue = pq->getValue();
			APP->history->push(h);
		}
		oldValue = NAN;
	}

	void onHoverScroll(const HoverScrollEvent& e) override {
		engine::ParamQuantity* pq = getParamQuantity();
		if (!settings::knobScroll || !pq) { ParamWidget::onHoverScroll(e); return; }
		float d = e.scrollDelta.y;
		if (d == 0.f) return;
		oldValue = pq->getValue();
		if (pq->snapEnabled)
			pq->setValue(pq->getValue() + (d > 0.f ? 1.f : -1.f));
		else
			pq->setValue(pq->getValue() + d * settings::knobScrollSensitivity * speed * modSpeed()
			             * (pq->isBounded() ? pq->getRange() : 1.f));
		pushHistory("scroll");
		e.consume(this);
	}
};

/** One of a set of named options. Hold and drag scrolls through them, a step every
 *  `pxPerStep` pixels, whatever the range; a click lists them, to pick one directly. The names
 *  come from the param's own SwitchQuantity labels, or from `nameOf` when the module computes
 *  them (a program list, say), or else the numbers. */
struct ScreenSelect : ScreenKnob {
	float pxPerStep = 14.f;
	//: Wrap from the last option to the first while dragging, for a ring with no end.
	bool wrap = false;
	std::function<std::string(int)> nameOf;

	float perPixel(engine::ParamQuantity*) override { return 1.f / pxPerStep; }

	void onDragMove(const DragMoveEvent& e) override {
		engine::ParamQuantity* pq = getParamQuantity();
		if (!wrap || !pq || e.button != GLFW_MOUSE_BUTTON_LEFT || !pq->isBounded()) {
			ScreenKnob::onDragMove(e);
			return;
		}
		dragged += std::fabs(e.mouseDelta.y) + std::fabs(e.mouseDelta.x);
		snapDelta += -e.mouseDelta.y * perPixel(pq) * modSpeed();
		float delta = std::trunc(snapDelta);
		snapDelta -= delta;
		if (delta == 0.f) return;
		const float lo = pq->getMinValue(), n = pq->getMaxValue() - lo + 1.f;
		pq->setValue(lo + math::eucMod(std::round(pq->getValue() - lo + delta), n));
	}

	std::string optionName(engine::ParamQuantity* pq, int i) {
		if (nameOf) return nameOf(i);
		if (auto* sq = dynamic_cast<engine::SwitchQuantity*>(pq))
			if (i >= 0 && i < (int) sq->labels.size()) return sq->labels[i];
		return string::f("%d", (int) (pq->getMinValue() + i));
	}

	void click() override {
		engine::ParamQuantity* pq = getParamQuantity();
		if (!pq || !pq->isBounded()) return;
		const float lo = pq->getMinValue();
		const int n = (int) std::round(pq->getMaxValue() - lo) + 1;
		const int cur = (int) std::round(pq->getValue() - lo);
		ui::Menu* menu = createMenu();
		menu->addChild(createMenuLabel(pq->getLabel()));
		const int id = paramId;
		const int64_t moduleId = module ? module->id : -1;
		for (int i = 0; i < n; i++) {
			menu->addChild(createCheckMenuItem(optionName(pq, i), "",
				[=]() { return i == cur; },
				[=]() {
					engine::Module* m = APP->engine->getModule(moduleId);
					if (!m) return;
					engine::ParamQuantity* q = m->paramQuantities[id];
					float before = q->getValue();
					q->setValue(lo + i);
					if (q->getValue() == before) return;
					history::ParamChange* h = new history::ParamChange;
					h->name = std::string("select ") + q->getLabel();
					h->moduleId = moduleId;
					h->paramId = id;
					h->oldValue = before;
					h->newValue = q->getValue();
					APP->history->push(h);
				}));
		}
	}
};

/** A switch on the screen: a click steps it to its next position (Ctrl-click the previous
 *  one), wrapping, like Rack's own switch. `momentary` makes it a button that holds its
 *  maximum while the mouse is down. The pointer is a hand -- this is pressed, not dragged. */
struct ScreenSwitch : ScreenField {
	bool momentary = false;

	int cursorShape() override { return GLFW_HAND_CURSOR; }

	void onDoubleClick(const DoubleClickEvent& e) override {
		// A double click is two presses here, not a reset.
		widget::OpaqueWidget::onDoubleClick(e);
	}

	void onDragStart(const DragStartEvent& e) override {
		ParamWidget::onDragStart(e);
		if (e.button != GLFW_MOUSE_BUTTON_LEFT) return;
		dragging = true;
		engine::ParamQuantity* pq = getParamQuantity();
		if (!pq) return;
		if (momentary) {
			pq->setMax();
			return;
		}
		const float before = pq->getValue();
		if ((APP->window->getMods() & RACK_MOD_MASK) == RACK_MOD_CTRL)
			pq->isMin() ? pq->setMax() : pq->setValue(std::round(before) - 1.f);
		else
			pq->isMax() ? pq->setMin() : pq->setValue(std::round(before) + 1.f);
		if (module && pq->getValue() != before) {
			history::ParamChange* h = new history::ParamChange;
			h->name = std::string("switch ") + pq->getLabel();
			h->moduleId = module->id;
			h->paramId = paramId;
			h->oldValue = before;
			h->newValue = pq->getValue();
			APP->history->push(h);
		}
	}

	void onDragEnd(const DragEndEvent& e) override {
		ParamWidget::onDragEnd(e);
		if (e.button != GLFW_MOUSE_BUTTON_LEFT) return;
		endDrag();
		if (momentary)
			if (engine::ParamQuantity* pq = getParamQuantity()) pq->setMin();
	}
};

/** A button on the screen: held while the mouse is down, like a VCVButton. */
struct ScreenButton : ScreenSwitch {
	ScreenButton() { momentary = true; }
};

/** A word on the screen that opens a menu: for an action rather than a value --
 *  a preset to load, a file to choose -- which has no param to bind to. The
 *  module fills the menu; the field only gives it the family's pointer and
 *  hover, so it reads as one of the screen's controls. */
struct ScreenMenu : widget::OpaqueWidget {
	std::function<void(ui::Menu*)> fill;
	bool hovered = false;

	void onEnter(const EnterEvent& e) override { hovered = true; ScreenCursor::set(GLFW_HAND_CURSOR); }
	void onLeave(const LeaveEvent& e) override { hovered = false; ScreenCursor::set(0); }
	~ScreenMenu() { if (hovered) ScreenCursor::set(0); }

	void onButton(const ButtonEvent& e) override {
		if (e.action == GLFW_PRESS && (e.button == GLFW_MOUSE_BUTTON_LEFT || e.button == GLFW_MOUSE_BUTTON_RIGHT)) {
			e.consume(this);
			if (fill) fill(createMenu());
		}
	}

	void drawLayer(const DrawArgs& args, int layer) override {
		OpaqueWidget::drawLayer(args, layer);
		if (layer != 1 || !hovered) return;
		nvgBeginPath(args.vg);
		nvgRoundedRect(args.vg, 0.5f, 0.5f, box.size.x - 1.f, box.size.y - 1.f, 1.6f);
		nvgFillColor(args.vg, alpha(LIME, 0.06f));
		nvgFill(args.vg);
		nvgStrokeColor(args.vg, alpha(LIME, 0.45f));
		nvgStrokeWidth(args.vg, 0.7f);
		nvgStroke(args.vg);
	}
};

inline ScreenMenu* createMenuField(const Rect& cell, std::function<void(ui::Menu*)> fill) {
	ScreenMenu* o = new ScreenMenu;
	o->box.pos = mm(cell.pos.x, cell.pos.y);
	o->box.size = mm(cell.size.x, cell.size.y);
	o->fill = fill;
	return o;
}

/** Place a field over its cell of the glass. `cell` is the FIELD_<NAME> rectangle from
 *  Panel.hpp, in panel millimetres. */
template <class TField>
TField* createField(const Rect& cell, engine::Module* module, int paramId) {
	TField* o = createParam<TField>(mm(cell.pos.x, cell.pos.y), module, paramId);
	o->box.size = mm(cell.size.x, cell.size.y);
	return o;
}

/** Every stock light derives from GrayModuleLightWidget, which hard-codes a
    #333333 socket that reads as a grey hole punched in a green panel. These
    restyle the socket as well as the emitter. */
template <typename TBase = GrayModuleLightWidget>
struct TSocketLight : TBase {
	TSocketLight() {
		this->bgColor = nvgRGBA(0x1b, 0x15, 0x1e, 0xff);
		this->borderColor = nvgRGBA(0x7b, 0x9a, 0x6d, 0xa0);
	}
};

template <typename TBase = GrayModuleLightWidget>
struct TLimeLight : TSocketLight<TBase> {
	TLimeLight() { this->addBaseColor(LIME); }
};
using LimeLight = TLimeLight<>;
template <typename TBase = GrayModuleLightWidget>
struct TMintLight : TSocketLight<TBase> {
	TMintLight() { this->addBaseColor(MINT); }
};
using MintLight = TMintLight<>;
template <typename TBase = GrayModuleLightWidget>
struct TPaperLight : TSocketLight<TBase> {
	TPaperLight() { this->addBaseColor(PAPER); }
};
using PaperLight = TPaperLight<>;
template <typename TBase = GrayModuleLightWidget>
struct TClayLight : TSocketLight<TBase> {
	TClayLight() { this->addBaseColor(CLAY); }
};
using ClayLight = TClayLight<>;
template <typename TBase = GrayModuleLightWidget>
struct TVerdictLight : TSocketLight<TBase> {
	TVerdictLight() { this->addBaseColor(MINT); this->addBaseColor(CLAY); }
};
using VerdictLight = TVerdictLight<>;

/** A light whose colour the module picks rather than the panel: three base
    colours the caller mixes by setting their brightnesses. For an indicator
    that has to be told apart from its neighbours -- one step of a sequence,
    one slot of a bank -- where a fixed ink can only say on or off. Feed it
    the components of an NVGcolor and it wears that colour; the family socket
    is kept, so it still reads as part of the panel and not as a stock LED. */
template <typename TBase = GrayModuleLightWidget>
struct TRgbLight : TSocketLight<TBase> {
	TRgbLight() {
		this->addBaseColor(nvgRGB(0xff, 0x00, 0x00));
		this->addBaseColor(nvgRGB(0x00, 0xff, 0x00));
		this->addBaseColor(nvgRGB(0x00, 0x00, 0xff));
	}
};
using RgbLight = TRgbLight<>;

/** The four corner screws, at the positions every panel in the family uses.
    Width comes from the widget's own box, so this needs no per-panel number. */
inline void addScrews(app::ModuleWidget* mw) {
	mw->addChild(createWidget<ScrewHex>(Vec(RACK_GRID_WIDTH, 0)));
	mw->addChild(createWidget<ScrewHex>(Vec(mw->box.size.x - 2 * RACK_GRID_WIDTH, 0)));
	mw->addChild(createWidget<ScrewHex>(Vec(RACK_GRID_WIDTH, RACK_GRID_HEIGHT - RACK_GRID_WIDTH)));
	mw->addChild(createWidget<ScrewHex>(Vec(mw->box.size.x - 2 * RACK_GRID_WIDTH,
	                                        RACK_GRID_HEIGHT - RACK_GRID_WIDTH)));
}

// --- silkscreen ------------------------------------------------------------
/** One word on the panel. The table itself is per-panel and lives in
    Panel.hpp; this is only its shape and how it is drawn. */
struct Label {
	float x, y, size, tracking;
	NVGcolor ink;
	int align;
	int turn;          // 0 upright, 1 mirrored (the maker's mark), 2 reads up, 3 reads down
	const char* text;
};

/** The style one silkscreen entry is set in. */
inline TextStyle labelStyle(const Label& l) {
	return TextStyle(Face::Ui, l.size, l.ink, l.align, l.tracking);
}

/** Draws a panel's silkscreen. Rack's nanosvg ignores <text>, so this is the
    only way a label reaches the panel. The table is passed in rather than
    referenced by name so that one definition of this widget serves all three
    panels in the plugin. */
struct Labels : widget::Widget {
	const Label* labels = NULL;
	size_t count = 0;

	void draw(const DrawArgs& args) override {
		for (size_t i = 0; i < count; i++) {
			const Label& l = labels[i];
			Vec p = mm(l.x, l.y);
			if (l.turn == 1)
				textMirrored(args.vg, labelStyle(l), p.x, p.y, l.text);
			else if (l.turn >= 2) {
				nvgSave(args.vg);
				nvgTranslate(args.vg, p.x, p.y);
				nvgRotate(args.vg, (l.turn == 2 ? -M_PI : M_PI) / 2.f);
				text(args.vg, labelStyle(l), 0.f, 0.f, l.text);
				nvgRestore(args.vg);
			}
			else
				text(args.vg, labelStyle(l), p.x, p.y, l.text);
		}
		Widget::draw(args);
	}
};

inline void addLabels(app::ModuleWidget* mw, const Label* labels, size_t count) {
	Labels* l = new Labels;
	l->labels = labels;
	l->count = count;
	l->box.pos = Vec(0, 0);
	l->box.size = mw->box.size;
	mw->addChild(l);
}

} // namespace panel
