// Generated by panelkit from tools/panels/Dividend.py. Do not edit; edit the spec.
//
// Everything the panel's C++ needs to agree with res/Dividend.svg: the millimetre
// grid, the widget positions and the whole silkscreen. Rack's nanosvg discards
// <text>, so labels cannot live in the SVG -- they are drawn at runtime from
// the table below, generated from the same spec that drew the artwork.
//
// Every declaration here is `static`, i.e. private to the translation unit, so
// the three panels in this plugin cannot collide. That also means no
// translation unit may include two of these.
#pragma once
#include "../PanelTheme.hpp"

namespace panel {

// --- identity --------------------------------------------------------------
static const int   HP = 16;
static const float W  = 81.2800f;  // mm
static const float H  = 128.5000f;  // mm

// --- silkscreen ------------------------------------------------------------
static const Label LABELS[] = {
	{ 40.6400f,   5.5000f, 10.50f, 1.50f, PAPER    , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "DIVIDEND"},
	{ 11.5600f,   8.2500f,  7.40f, 0.00f, LIME     , NVG_ALIGN_LEFT | NVG_ALIGN_BASELINE, true,  "$"},
	{ 13.7637f,   8.0000f,  4.60f, 0.40f, SAGE     , NVG_ALIGN_LEFT | NVG_ALIGN_BASELINE, false, "MOON TECHNOLOGIES"},
	{ 77.0800f,   8.0000f,  4.60f, 0.40f, SAGE     , NVG_ALIGN_RIGHT | NVG_ALIGN_BASELINE, false, "FORM 1099-DIV"},
	{ 40.6400f,  23.5000f,  6.00f, 0.60f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "PAYOUT"},
	{ 10.0000f,  43.8000f,  7.00f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "FREQ"},
	{ 25.3200f,  43.8000f,  7.00f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "FINE"},
	{ 40.6400f,  43.8000f,  7.00f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "FORMANT"},
	{ 55.9600f,  43.8000f,  6.20f, 0.00f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "TRACK"},
	{ 71.2800f,  43.8000f,  6.20f, 0.00f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "FM"},
	{ 40.6400f,  51.4927f,  6.00f, 0.60f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "DISTRIBUTION"},
	{ 10.0000f,  64.7927f,  7.00f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "WAVE"},
	{ 30.4267f,  64.7927f,  7.00f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "WINDOW"},
	{ 50.8533f,  64.7927f,  7.00f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "CYCLES"},
	{ 71.2800f,  64.7927f,  6.20f, 0.00f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "L/R"},
	{ 40.6400f,  72.4853f,  6.00f, 0.60f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "WITHHOLDING"},
	{ 10.0000f,  85.7853f,  7.00f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "ON"},
	{ 30.4267f,  85.7853f,  7.00f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "OFF"},
	{ 50.8533f,  85.7853f,  7.00f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "PROB"},
	{ 71.2800f,  85.7853f,  5.80f, 0.00f, LIME_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "HELD"},
	{ 10.0000f,  88.9898f,  6.20f, 0.00f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "FM"},
	{ 30.4267f,  88.9898f,  6.20f, 0.00f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "FMT"},
	{ 50.8533f,  88.9898f,  6.20f, 0.00f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "PROB"},
	{ 71.2800f,  88.9898f,  6.20f, 0.00f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "BURST"},
	{  8.0000f, 112.8651f,  6.20f, 0.00f, SAGE     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "V/OCT"},
	{ 21.0560f, 112.8651f,  6.20f, 0.00f, SAGE     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "SYNC"},
	{ 34.1120f, 112.8651f,  6.20f, 0.00f, MINT     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "OUT L"},
	{ 47.1680f, 112.8651f,  6.20f, 0.00f, MINT     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "OUT R"},
	{ 60.2240f, 112.8651f,  6.20f, 0.00f, MINT     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "TRIG"},
	{ 73.2800f, 112.8651f,  6.20f, 0.00f, MINT     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "ENV"},
};

/** Draws this panel's silkscreen. `static` so each module keeps its own,
    bound to its own table. */
static inline void addLabels(app::ModuleWidget* mw) {
	addLabels(mw, LABELS, sizeof(LABELS) / sizeof(LABELS[0]));
}

// --- widget positions, by the names used in tools/panels/Dividend.py -----
// Positions are mm; feed them to mm() or createParamCentered.
static const Vec FREQ_POS = Vec(10.0000, 33.3000);
static const Vec FINE_POS = Vec(25.3200, 33.3000);
static const Vec FORMANT_POS = Vec(40.6400, 33.3000);
static const Vec TRACK_POS = Vec(55.9600, 33.3000);
static const Vec FM_MODE_POS = Vec(71.2800, 33.3000);
static const Vec WAVE_POS = Vec(10.0000, 57.7927);
static const Vec WINDOW_POS = Vec(30.4267, 57.7927);
static const Vec CYCLES_POS = Vec(50.8533, 57.7927);
static const Vec STEREO_POS = Vec(71.2800, 57.7927);
static const Vec BURST_ON_POS = Vec(10.0000, 78.7853);
static const Vec BURST_OFF_POS = Vec(30.4267, 78.7853);
static const Vec PROB_POS = Vec(50.8533, 78.7853);
static const Vec HELD_POS = Vec(71.2800, 78.7853);
static const Vec FM_CV_POS = Vec(10.0000, 93.7347);
static const Vec FMT_CV_POS = Vec(30.4267, 93.7347);
static const Vec PROB_CV_POS = Vec(50.8533, 93.7347);
static const Vec BURST_CV_POS = Vec(71.2800, 93.7347);
static const Vec FM_IN_POS = Vec(10.0000, 101.8647);
static const Vec FMT_IN_POS = Vec(30.4267, 101.8647);
static const Vec PROB_IN_POS = Vec(50.8533, 101.8647);
static const Vec BURST_IN_POS = Vec(71.2800, 101.8647);
static const Vec VOCT_POS = Vec(8.0000, 118.6000);
static const Vec SYNC_POS = Vec(21.0560, 118.6000);
static const Vec OUT_L_POS = Vec(34.1120, 118.6000);
static const Vec OUT_R_POS = Vec(47.1680, 118.6000);
static const Vec TRIG_POS = Vec(60.2240, 118.6000);
static const Vec ENV_POS = Vec(73.2800, 118.6000);

} // namespace panel
