// Generated by panelkit from tools/panels/Gross.py. Do not edit; edit the spec.
//
// Everything the panel's C++ needs to agree with res/Gross.svg: the millimetre
// grid, the widget positions and the whole silkscreen. Rack's nanosvg discards
// <text>, so labels cannot live in the SVG -- they are drawn at runtime from
// the table below, generated from the same spec that drew the artwork.
//
// Every declaration here is `static`, i.e. private to the translation unit, so
// the three panels in this plugin cannot collide. That also means no
// translation unit may include two of these.
#pragma once
#include "../PanelTheme.hpp"

namespace panel {

// --- identity --------------------------------------------------------------
static const int   HP = 20;
static const float W  = 101.6000f;  // mm
static const float H  = 128.5000f;  // mm

// --- the read-out well: the spec's numbers, not the widget's ---------------
// A display used to be positioned by hand in the module's C++, in the same
// millimetres the spec had already chosen -- two copies of one number, and
// they drifted. The widget takes them from here now.
static const float GLASS_X = 3.6000f;
static const float GLASS_Y = 9.8000f;
static const float GLASS_W = 94.4000f;
static const float GLASS_H = 10.0000f;

// --- silkscreen ------------------------------------------------------------
static const Label LABELS[] = {
	{ 50.8000f,   5.5000f, 10.50f, 1.50f, PAPER    , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "GROSS"},
	{ 11.5600f,   8.2500f,  7.40f, 0.00f, LIME     , NVG_ALIGN_LEFT | NVG_ALIGN_BASELINE, true,  "$"},
	{ 13.7637f,   8.0000f,  4.60f, 0.40f, SAGE     , NVG_ALIGN_LEFT | NVG_ALIGN_BASELINE, false, "MOON TECHNOLOGIES"},
	{ 97.4000f,   8.0000f,  4.60f, 0.40f, SAGE     , NVG_ALIGN_RIGHT | NVG_ALIGN_BASELINE, false, "SCHEDULE C"},
	{ 63.0100f,  23.3000f,  6.00f, 0.60f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "GROSS RECEIPTS"},
	{ 33.5200f,  40.6069f,  7.00f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "LOW"},
	{ 47.6450f,  40.6069f,  7.00f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "MID"},
	{ 61.7700f,  40.6069f,  7.00f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "MID F"},
	{ 75.8950f,  40.6069f,  7.00f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "HIGH"},
	{ 91.2000f,  40.6069f,  7.00f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "DRIVE"},
	{ 63.0100f,  47.8069f,  6.00f, 0.60f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "ADJUSTMENTS"},
	{ 33.5200f,  63.1003f,  7.00f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "OFFSET"},
	{ 48.0416f,  63.1003f,  7.00f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "DYN"},
	{ 63.4568f,  63.1003f,  7.00f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "ATTACK"},
	{ 77.9784f,  63.1003f,  7.00f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "RELEASE"},
	{ 92.5000f,  63.1003f,  7.00f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "CURVE"},
	{ 45.4975f,  79.2887f,  6.20f, 0.00f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "KNEE+"},
	{ 57.1725f,  79.2887f,  6.20f, 0.00f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "KNEE-"},
	{ 68.8475f,  79.2887f,  6.20f, 0.00f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "SHAPE+"},
	{ 80.5225f,  79.2887f,  6.20f, 0.00f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "SHAPE-"},
	{ 63.0100f,  86.4887f,  6.00f, 0.60f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "NET"},
	{ 38.5975f, 101.1956f,  7.00f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "WET"},
	{ 54.8725f, 101.1956f,  7.00f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "POST"},
	{ 71.1475f, 101.1956f,  7.00f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "TONE"},
	{ 87.4225f, 101.1956f,  7.00f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "LO CUT"},
	{ 13.8100f,  23.3000f,  6.00f, 0.60f, SAGE     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "CV"},
	{ 13.8100f,  26.3618f,  6.20f, 0.00f, SAGE     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "DRIVE"},
	{ 13.8100f,  48.0797f,  6.20f, 0.00f, SAGE     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "BIAS"},
	{ 13.8100f,  69.7976f,  6.20f, 0.00f, SAGE     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "WET"},
	{ 13.8100f,  91.5156f,  6.20f, 0.00f, SAGE     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "TONE"},
	{ 23.7000f, 113.4100f,  6.20f, 0.00f, SAGE     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "IN L"},
	{ 37.2500f, 113.4100f,  6.20f, 0.00f, SAGE     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "IN R"},
	{ 50.8000f, 113.4100f,  6.20f, 0.00f, MINT     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "ENV"},
	{ 64.3500f, 113.4100f,  6.20f, 0.00f, MINT     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "OUT L"},
	{ 77.9000f, 113.4100f,  6.20f, 0.00f, MINT     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, false, "OUT R"},
};

/** Draws this panel's silkscreen. `static` so each module keeps its own,
    bound to its own table. */
static inline void addLabels(app::ModuleWidget* mw) {
	addLabels(mw, LABELS, sizeof(LABELS) / sizeof(LABELS[0]));
}

// --- widget positions, by the names used in tools/panels/Gross.py -----
// Positions are mm; feed them to mm() or createParamCentered.
static const Vec LOW_POS = Vec(33.5200, 31.2000);
static const Vec MID_POS = Vec(47.6450, 31.2000);
static const Vec MIDF_POS = Vec(61.7700, 31.2000);
static const Vec HIGH_POS = Vec(75.8950, 31.2000);
static const Vec DRIVE_POS = Vec(91.2000, 31.2000);
static const Vec OFFSET_POS = Vec(33.5200, 54.4069);
static const Vec DYN_POS = Vec(48.0416, 54.4069);
static const Vec ATTACK_POS = Vec(63.4568, 54.4069);
static const Vec RELEASE_POS = Vec(77.9784, 54.4069);
static const Vec CURVE_POS = Vec(92.5000, 54.4069);
static const Vec ENV_LED_POS = Vec(52.8152, 62.2469);
static const Vec KP_POS = Vec(45.4975, 73.1569);
static const Vec KN_POS = Vec(57.1725, 73.1569);
static const Vec GP_POS = Vec(68.8475, 73.1569);
static const Vec GN_POS = Vec(80.5225, 73.1569);
static const Vec WET_POS = Vec(38.5975, 93.0887);
static const Vec POST_POS = Vec(54.8725, 93.0887);
static const Vec TONE_POS = Vec(71.1475, 93.0887);
static const Vec LOCUT_POS = Vec(87.4225, 93.0887);
static const Vec DRIVE_IN_POS = Vec(9.4900, 31.5518);
static const Vec DRIVE_CV_POS = Vec(18.7000, 31.5518);
static const Vec BIAS_IN_POS = Vec(9.4900, 53.2697);
static const Vec BIAS_CV_POS = Vec(18.7000, 53.2697);
static const Vec WET_IN_POS = Vec(9.4900, 74.9876);
static const Vec WET_CV_POS = Vec(18.7000, 74.9876);
static const Vec TONE_IN_POS = Vec(9.4900, 96.7056);
static const Vec TONE_CV_POS = Vec(18.7000, 96.7056);
static const Vec IN_L_POS = Vec(23.7000, 118.6000);
static const Vec IN_R_POS = Vec(37.2500, 118.6000);
static const Vec ENV_OUT_POS = Vec(50.8000, 118.6000);
static const Vec OUT_L_POS = Vec(64.3500, 118.6000);
static const Vec OUT_R_POS = Vec(77.9000, 118.6000);

} // namespace panel
