// Generated by panelkit from tools/panels/Contagion.py. Do not edit; edit the spec.
//
// Everything the panel's C++ needs to agree with res/Contagion.svg: the millimetre
// grid, the widget positions and the whole silkscreen. Rack's nanosvg discards
// <text>, so labels cannot live in the SVG -- they are drawn at runtime from
// the table below, generated from the same spec that drew the artwork.
//
// Every declaration here is `static`, i.e. private to the translation unit, so
// the three panels in this plugin cannot collide. That also means no
// translation unit may include two of these.
#pragma once
#include "../PanelTheme.hpp"

namespace panel {

// --- identity --------------------------------------------------------------
static const int   HP = 37;
static const float W  = 187.9600f;  // mm
static const float H  = 128.5000f;  // mm
//: What the module is, as the masthead's second line says it.
static const char* const WHAT = "VIRUS C SYNTHESIZER";

// --- the read-out well: the spec's numbers, not the widget's ---------------
// A display used to be positioned by hand in the module's C++, in the same
// millimetres the spec had already chosen -- two copies of one number, and
// they drifted. The widget takes them from here now.
static const float GLASS_X = 3.6000f;
static const float GLASS_Y = 9.8000f;
static const float GLASS_W = 180.7600f;
static const float GLASS_H = 24.5000f;

// --- controls on the glass: where each is drawn and where it is grabbed --
// One rectangle per Field in the spec, in panel mm. Place the widget with
// createField<Screen...>(FIELD_X, ...) -- or createMenuField for a "menu" --
// and draw the value in
// inGlass(FIELD_X), the same rectangle in the display's own pixels.
static const Rect FIELD_PRESET_LCD = Rect(Vec(4.4000f, 13.9429f), Vec(39.4244f, 6.1857f));  // menu: ScreenMenu
static const Rect FIELD_PRESET = Rect(Vec(4.4000f, 20.6286f), Vec(5.4887f, 6.1857f));  // button: ScreenButton
static const Rect FIELD_CATEGORY = Rect(Vec(19.3717f, 20.6286f), Vec(5.4887f, 6.1857f));  // button: ScreenButton
static const Rect FIELD_INCAT = Rect(Vec(31.3490f, 20.6286f), Vec(5.4887f, 6.1857f));  // button: ScreenButton
static const Rect FIELD_TEMPO = Rect(Vec(67.2810f, 10.6000f), Vec(20.4603f, 2.8429f));  // value: ScreenKnob
static const Rect FIELD_PARAM = Rect(Vec(47.3188f, 20.6286f), Vec(5.4887f, 6.1857f));  // button: ScreenButton
static const Rect FIELD_VALUE = Rect(Vec(61.2923f, 20.6286f), Vec(5.4887f, 6.1857f));  // button: ScreenButton
static const Rect FIELD_PAGE = Rect(Vec(75.2659f, 20.6286f), Vec(5.4887f, 6.1857f));  // button: ScreenButton
static const Rect FIELD_K_SINGLE = Rect(Vec(4.4000f, 27.3143f), Vec(10.4792f, 2.8429f));  // button: ScreenButton
static const Rect FIELD_K_MULTI = Rect(Vec(16.3773f, 27.3143f), Vec(10.4792f, 2.8429f));  // button: ScreenButton
static const Rect FIELD_K_MULTISGL = Rect(Vec(28.3547f, 27.3143f), Vec(10.4792f, 2.8429f));  // button: ScreenButton
static const Rect FIELD_K_EDIT = Rect(Vec(40.3320f, 27.3143f), Vec(10.4792f, 2.8429f));  // button: ScreenButton
static const Rect FIELD_K_GLOBAL = Rect(Vec(52.3093f, 27.3143f), Vec(10.4792f, 2.8429f));  // button: ScreenButton
static const Rect FIELD_K_UNDO = Rect(Vec(64.2867f, 27.3143f), Vec(10.4792f, 2.8429f));  // button: ScreenButton
static const Rect FIELD_K_STORE = Rect(Vec(76.2640f, 27.3143f), Vec(11.4773f, 2.8429f));  // button: ScreenButton
static const Rect FIELD_K_ARP_ON = Rect(Vec(4.4000f, 30.6571f), Vec(15.4698f, 2.8429f));  // button: ScreenButton
static const Rect FIELD_K_ARP_EDIT = Rect(Vec(21.3679f, 30.6571f), Vec(15.4698f, 2.8429f));  // button: ScreenButton
static const Rect FIELD_K_DLY_EDIT = Rect(Vec(38.3358f, 30.6571f), Vec(15.4698f, 2.8429f));  // button: ScreenButton
static const Rect FIELD_K_FLT_EDIT = Rect(Vec(55.3037f, 30.6571f), Vec(15.4698f, 2.8429f));  // button: ScreenButton
static const Rect FIELD_K_RANDOM = Rect(Vec(72.2716f, 30.6571f), Vec(15.4698f, 2.8429f));  // button: ScreenButton
static const Rect FIELD_LFO_EDIT = Rect(Vec(90.2376f, 13.9429f), Vec(7.4849f, 2.8429f));  // button: ScreenButton
static const Rect FIELD_LFO_SEL = Rect(Vec(98.2224f, 13.9429f), Vec(21.4584f, 2.8429f));  // select: ScreenSelect
static const Rect FIELD_LFO_SHAPE = Rect(Vec(98.2224f, 17.2857f), Vec(27.4471f, 2.8429f));  // select: ScreenSelect
static const Rect FIELD_OSC_EDIT = Rect(Vec(90.2376f, 20.6286f), Vec(7.4849f, 2.8429f));  // button: ScreenButton
static const Rect FIELD_OSC_SEL = Rect(Vec(98.2224f, 20.6286f), Vec(16.4679f, 2.8429f));  // select: ScreenSelect
static const Rect FIELD_K_SYNC = Rect(Vec(115.1903f, 20.6286f), Vec(4.4906f, 2.8429f));  // button: ScreenButton
static const Rect FIELD_K_OSC3_ON = Rect(Vec(120.1809f, 20.6286f), Vec(5.4887f, 2.8429f));  // button: ScreenButton
static const Rect FIELD_FX_EDIT = Rect(Vec(90.2376f, 23.9714f), Vec(7.4849f, 2.8429f));  // button: ScreenButton
static const Rect FIELD_FX_SEL = Rect(Vec(98.2224f, 23.9714f), Vec(16.4679f, 2.8429f));  // select: ScreenSelect
static const Rect FIELD_K_SEL1 = Rect(Vec(90.2376f, 27.3143f), Vec(7.4849f, 2.8429f));  // button: ScreenButton
static const Rect FIELD_FLT1_MODE = Rect(Vec(98.2224f, 27.3143f), Vec(21.4584f, 2.8429f));  // select: ScreenSelect
static const Rect FIELD_K_SEL2 = Rect(Vec(90.2376f, 30.6571f), Vec(7.4849f, 2.8429f));  // button: ScreenButton
static const Rect FIELD_FLT2_MODE = Rect(Vec(98.2224f, 30.6571f), Vec(21.4584f, 2.8429f));  // select: ScreenSelect
static const Rect FIELD_LFO_AMOUNT = Rect(Vec(128.1658f, 13.9429f), Vec(55.3942f, 12.8714f));  // button: ScreenButton
static const Rect FIELD_TRANS = Rect(Vec(128.1658f, 27.3143f), Vec(5.4887f, 6.1857f));  // button: ScreenButton

/** A field's rectangle in the display's pixels, for a display placed on the glass. */
static inline Rect inGlass(const Rect& f) {
	return mmRect(f.pos.x - GLASS_X, f.pos.y - GLASS_Y, f.size.x, f.size.y);
}

// --- silkscreen ------------------------------------------------------------
static const Label LABELS[] = {
	{ 93.9800f,   5.5000f, 10.50f, 1.50f, PAPER    , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "CONTAGION"},
	{  1.4000f,   8.2500f,  7.40f, 0.00f, LIME     , NVG_ALIGN_LEFT | NVG_ALIGN_BASELINE, 1,     "$"},
	{ 93.9800f,   8.0000f,  5.40f, 0.40f, LIME     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "VIRUS C SYNTHESIZER"},
	{  2.1717f,  29.4034f,  4.60f, 0.40f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 2,     "MOON TECHNOLOGIES"},
	{185.7883f,  53.7491f,  4.60f, 0.40f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 3,     "FORM 8300"},
	{ 81.0000f,  38.5000f,  6.00f, 0.60f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "LFOS/MOD · OSCILLATORS · MIXER"},
	{  9.1000f,  53.8069f,  7.00f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "RATE"},
	{ 24.9000f,  53.8069f,  7.00f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "SHAPE"},
	{ 38.3968f,  53.8069f,  7.00f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "WAVE/PW"},
	{ 51.8936f,  53.8069f,  7.00f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "SEMITONE"},
	{ 66.8024f,  53.8069f,  7.00f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "DETUNE 2/3"},
	{ 82.4120f,  53.8069f,  7.00f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "FM AMOUNT"},
	{ 98.9128f,  53.8069f,  7.00f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "OSC BAL"},
	{112.4096f,  53.8069f,  7.00f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "SUB OSC"},
	{125.9064f,  53.8069f,  7.00f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "OSC VOL"},
	{139.4032f,  53.8069f,  7.00f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "NOISE"},
	{152.9000f,  53.8069f,  7.00f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "RING MOD"},
	{ 81.0000f,  61.3069f,  6.00f, 0.60f, SAGE_DARK, NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "EFFECTS · DELAY/REVERB · FILTERS · SOFT · ENVELOPES"},
	{  9.1000f,  79.2138f,  7.00f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "TYPE/MIX"},
	{ 25.3474f,  79.2138f,  7.00f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "INTENSITY"},
	{ 41.5947f,  79.2138f,  7.00f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "SEND"},
	{ 55.0077f,  79.2138f,  7.00f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "TIME"},
	{ 69.1214f,  79.2138f,  7.00f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "FDBK/DAMP"},
	{ 84.5352f,  79.2138f,  7.00f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "CUTOFF"},
	{ 99.2482f,  79.2138f,  7.00f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "CUTOFF 2"},
	{112.6611f,  79.2138f,  7.00f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "RESO"},
	{126.0741f,  79.2138f,  7.00f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "ENV AMT"},
	{139.4870f,  79.2138f,  7.00f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "FLT BAL"},
	{152.9000f,  79.2138f,  7.00f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "PART"},
	{  9.1000f,  94.4206f,  7.00f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "SOFT 1"},
	{ 25.3474f,  94.4206f,  7.00f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "SOFT 2/VALUE"},
	{ 41.5947f,  94.4206f,  7.00f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "VOLUME"},
	{ 55.0077f,  94.4206f,  7.00f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "ATTACK"},
	{ 69.1214f,  94.4206f,  7.00f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "DECAY"},
	{ 84.5352f,  94.4206f,  7.00f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "SUSTAIN"},
	{ 99.2482f,  94.4206f,  7.00f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "RELEASE"},
	{112.6611f,  94.4206f,  7.00f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "ATTACK"},
	{126.0741f,  94.4206f,  7.00f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "DECAY"},
	{139.4870f,  94.4206f,  7.00f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "SUSTAIN"},
	{152.9000f,  94.4206f,  7.00f, 0.00f, INK      , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "RELEASE"},
	{173.3800f,  38.5000f,  6.00f, 0.60f, MINT     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "OUT"},
	{168.2900f,  41.5618f,  6.20f, 0.00f, MINT     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "1 L"},
	{178.4700f,  41.5618f,  6.20f, 0.00f, MINT     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "1 R"},
	{168.2900f,  63.1012f,  6.20f, 0.00f, MINT     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "2 L"},
	{178.4700f,  63.1012f,  6.20f, 0.00f, MINT     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "2 R"},
	{168.2900f,  84.6406f,  6.20f, 0.00f, MINT     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "3 L"},
	{178.4700f,  84.6406f,  6.20f, 0.00f, MINT     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "3 R"},
	{  6.4900f, 100.7100f,  6.20f, 0.00f, SAGE     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "IN L"},
	{ 19.9500f, 100.7100f,  6.20f, 0.00f, SAGE     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "IN R"},
	{ 33.4100f, 100.7100f,  6.20f, 0.00f, SAGE     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "PITCH"},
	{ 46.8700f, 100.7100f,  6.20f, 0.00f, SAGE     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "GATE"},
	{ 60.3300f, 100.7100f,  6.20f, 0.00f, SAGE     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "VEL"},
	{ 73.7900f, 100.7100f,  6.20f, 0.00f, SAGE     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "BEND"},
	{ 87.2500f, 100.7100f,  6.20f, 0.00f, SAGE     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "MOD"},
	{100.7100f, 100.7100f,  6.20f, 0.00f, SAGE     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "TOUCH"},
	{114.1700f, 100.7100f,  6.20f, 0.00f, SAGE     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "SUSTAIN"},
	{127.6300f, 100.7100f,  6.20f, 0.00f, SAGE     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "CLOCK"},
	{141.0900f, 100.7100f,  6.20f, 0.00f, SAGE     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "RUN"},
	{154.5500f, 100.7100f,  6.20f, 0.00f, SAGE     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "RESET"},
	{168.0100f, 100.7100f,  6.20f, 0.00f, SAGE     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "CV 1"},
	{181.4700f, 100.7100f,  6.20f, 0.00f, SAGE     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "CV 2"},
	{  6.4900f, 113.3100f,  6.20f, 0.00f, SAGE     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "CV 3"},
	{ 19.9500f, 113.3100f,  6.20f, 0.00f, SAGE     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "CV 4"},
	{ 33.4100f, 113.3100f,  6.20f, 0.00f, SAGE     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "CV 5"},
	{ 46.8700f, 113.3100f,  6.20f, 0.00f, SAGE     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "CV 6"},
	{ 60.3300f, 113.3100f,  6.20f, 0.00f, SAGE     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "CV 7"},
	{ 73.7900f, 113.3100f,  6.20f, 0.00f, SAGE     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "CV 8"},
	{ 87.2500f, 113.3100f,  6.20f, 0.00f, SAGE     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "PART -"},
	{100.7100f, 113.3100f,  6.20f, 0.00f, SAGE     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "PART +"},
	{114.1700f, 113.3100f,  6.20f, 0.00f, SAGE     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "PARAM <"},
	{127.6300f, 113.3100f,  6.20f, 0.00f, SAGE     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "PARAM >"},
	{141.0900f, 113.3100f,  6.20f, 0.00f, SAGE     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "VALUE -"},
	{154.5500f, 113.3100f,  6.20f, 0.00f, SAGE     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "VALUE +"},
	{168.0100f, 113.3100f,  6.20f, 0.00f, SAGE     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "ARP ON"},
	{181.4700f, 113.3100f,  6.20f, 0.00f, SAGE     , NVG_ALIGN_CENTER | NVG_ALIGN_BASELINE, 0,     "RANDOM"},
};

/** Draws this panel's silkscreen. `static` so each module keeps its own,
    bound to its own table. */
static inline void addLabels(app::ModuleWidget* mw) {
	addLabels(mw, LABELS, sizeof(LABELS) / sizeof(LABELS[0]));
}

// --- widget positions, by the names used in tools/panels/Contagion.py -----
// Positions are mm; feed them to mm() or createParamCentered.
static const Vec RATE_POS = Vec(9.1000, 45.6000);
static const Vec SHAPE_POS = Vec(24.9000, 45.6000);
static const Vec WAVE_POS = Vec(38.3968, 45.6000);
static const Vec SEMITONE_POS = Vec(51.8936, 45.6000);
static const Vec DETUNE_POS = Vec(66.8024, 45.6000);
static const Vec FM_POS = Vec(82.4120, 45.6000);
static const Vec OSC_BAL_POS = Vec(98.9128, 45.6000);
static const Vec SUB_POS = Vec(112.4096, 45.6000);
static const Vec OSC_VOL_POS = Vec(125.9064, 45.6000);
static const Vec NOISE_POS = Vec(139.4032, 45.6000);
static const Vec RING_POS = Vec(152.9000, 45.6000);
static const Vec FX_MIX_POS = Vec(9.1000, 69.7069);
static const Vec FX_INT_POS = Vec(25.3474, 69.7069);
static const Vec DLY_SEND_POS = Vec(41.5947, 69.7069);
static const Vec DLY_TIME_POS = Vec(55.0077, 69.7069);
static const Vec DLY_FB_POS = Vec(69.1214, 69.7069);
static const Vec CUTOFF_POS = Vec(84.5352, 69.7069);
static const Vec CUTOFF2_POS = Vec(99.2482, 69.7069);
static const Vec RESO_POS = Vec(112.6611, 69.7069);
static const Vec ENV_AMT_POS = Vec(126.0741, 69.7069);
static const Vec FLT_BAL_POS = Vec(139.4870, 69.7069);
static const Vec PART_POS = Vec(152.9000, 69.7069);
static const Vec SOFT1_POS = Vec(9.1000, 86.2138);
static const Vec SOFT2_POS = Vec(25.3474, 86.2138);
static const Vec VOLUME_POS = Vec(41.5947, 86.2138);
static const Vec F_ATT_POS = Vec(55.0077, 86.2138);
static const Vec F_DEC_POS = Vec(69.1214, 86.2138);
static const Vec F_SUS_POS = Vec(84.5352, 86.2138);
static const Vec F_REL_POS = Vec(99.2482, 86.2138);
static const Vec A_ATT_POS = Vec(112.6611, 86.2138);
static const Vec A_DEC_POS = Vec(126.0741, 86.2138);
static const Vec A_SUS_POS = Vec(139.4870, 86.2138);
static const Vec A_REL_POS = Vec(152.9000, 86.2138);
static const Vec OUT1L_POS = Vec(168.2900, 46.8518);
static const Vec OUT1R_POS = Vec(178.4700, 46.8518);
static const Vec OUT2L_POS = Vec(168.2900, 68.3912);
static const Vec OUT2R_POS = Vec(178.4700, 68.3912);
static const Vec OUT3L_POS = Vec(168.2900, 89.9306);
static const Vec OUT3R_POS = Vec(178.4700, 89.9306);
static const Vec IN_L_POS = Vec(6.4900, 106.0000);
static const Vec IN_R_POS = Vec(19.9500, 106.0000);
static const Vec NOTE_V_POS = Vec(33.4100, 106.0000);
static const Vec NOTE_GATE_POS = Vec(46.8700, 106.0000);
static const Vec NOTE_VEL_POS = Vec(60.3300, 106.0000);
static const Vec BEND_POS = Vec(73.7900, 106.0000);
static const Vec MOD_POS = Vec(87.2500, 106.0000);
static const Vec TOUCH_POS = Vec(100.7100, 106.0000);
static const Vec SUSTAIN_POS = Vec(114.1700, 106.0000);
static const Vec CLK_POS = Vec(127.6300, 106.0000);
static const Vec RUN_POS = Vec(141.0900, 106.0000);
static const Vec RST_POS = Vec(154.5500, 106.0000);
static const Vec CV1_POS = Vec(168.0100, 106.0000);
static const Vec CV2_POS = Vec(181.4700, 106.0000);
static const Vec CV3_POS = Vec(6.4900, 118.6000);
static const Vec CV4_POS = Vec(19.9500, 118.6000);
static const Vec CV5_POS = Vec(33.4100, 118.6000);
static const Vec CV6_POS = Vec(46.8700, 118.6000);
static const Vec CV7_POS = Vec(60.3300, 118.6000);
static const Vec CV8_POS = Vec(73.7900, 118.6000);
static const Vec G_PART_DN_POS = Vec(87.2500, 118.6000);
static const Vec G_PART_UP_POS = Vec(100.7100, 118.6000);
static const Vec G_PARAM_DN_POS = Vec(114.1700, 118.6000);
static const Vec G_PARAM_UP_POS = Vec(127.6300, 118.6000);
static const Vec G_VALUE_DN_POS = Vec(141.0900, 118.6000);
static const Vec G_VALUE_UP_POS = Vec(154.5500, 118.6000);
static const Vec G_ARP_POS = Vec(168.0100, 118.6000);
static const Vec G_RANDOM_POS = Vec(181.4700, 118.6000);

} // namespace panel
